### PR TITLE
mMarFoi2 EAR

### PR DESCRIPTION
**Pull request by gitcruz**
## Assembly review request

- ToLID: mMarFoi2
- Species: Martes foina
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by gitcruz** [comment]
Hi @diegomics,

I don't understand the automatic bot error. This time I am pretty sure I uploaded just one EAR. Of course, this is inside two folders called Martes_foina/mMarFoi2/ 

Please let me know if the PR is good and we can assign a reviewer.

Thanks

**Comment by diegomics** [comment]
Hi @gitcruz 
As you can see below, you are trying to merge two files, one for _Coenonympha oedippus_ and the other for _Martes foina_:

Screenshot 2024-10-25 at 16 43 00

Please remove Coenonympha oedippus from this PR :)

**Comment by diegomics** [comment]
Ok

**Comment by bistace** [comment]
Yes

**Comment by bistace** [comment]
Hello @gitcruz,

very nice assembly! 

The HiC map is hard to review because there are a lot of intra-chromosomal contacts. However I don't see anything out of place, the telomeres are present at the extremities and coverage also looks normal across the entire chromosomes. To me this looks good to go!

**Comment by diegomics** [comment]
Thanks @bistace, yes the assembly looks good.
I'm wondering if the small portion near the gap on SUPER_4 @ 46 Kbp should be place in the zone near the gap on SUPER_4 @ 127,3

**Comment by gitcruz** [comment]
Dear all,

Thanks @bistace for the review! 

@diegomics  I agree on your comment about  SUPER_4 @ 46 Kbp. Despite of being already contigged is likely repetitive sequence (based on ONT coverage) that better fits into the gap at 127,3 Kb.

We will produce a final savestate and place it inside the same folder. Do you think is necessary to produce a new EAR?

Please please accept the PR and merge it when you can. I think we  have this genome and its complete mitochondrion ready to submit.

Thanks!
Fernando

**Comment by talioto** [comment]
It's a tricky region. There are reads spanning from the left side of the gap at 46 to the right side of the gap at 127. I will browse the alignments some more to see where to make the break and join. But after the BG24 sessions today.

**Comment by diegomics** [comment]
@gitcruz please share the savestate, so we can move forward and approve it to save time ;)

**Comment by talioto** [comment]
I took care of it. Here is the [savestate](https://ccnag-my.sharepoint.com/:u:/g/personal/tyler_alioto_cnag_eu/ERz_jHNesEBMs0wlcleU32QBwaFsm1zqmMnq7JFWE0mF5A?e=NLmGR5).

After examining BAM with IGV, I will make precise edit in tpf after pretext-to-tpf, before rapid_join.pl
SUPER_4: 45944201-46296785 => 127401600 in + orientation

**Comment by talioto** [comment]
Oh and I localized the unloc on SUPER_8 and the unloc on SUPER_Y. No more unlocs or unplaced!

**Review by bistace — APPROVED** [review]
Very nice, seems good to me!

**Comment by gitcruz** [comment]
Dear @diegomics,

In this case is it strictly necessary to generate a new EAR recomputing all
stats?

Thanks.
Fernando

**Comment by diegomics** [comment]
You don't need to regenerate the pretext map and the blobplot, only update gfastats (result should be different) and merqury and busco (not sure it will be different but maybe). And only on the curated assembly!

**Comment by gitcruz** [comment]
makes sense, Thanks!

**Comment by gitcruz** [comment]
Hi @diegomics, 

I uploaded the updated EAR. Could you merge the PR with the main branch?

Thanks,
Fernando

**Pull request merged**
