### PR TITLE
add icDenFora10, Dendarus foraminosus

### PR DESCRIPTION
**Pull request by duprats**
## Assembly review request

- ToLID: icDenFora10
- Species: Dendarus foraminosus
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @duprats , thanks for sending the EAR of _Dendarus foraminosus_.
I added the corresponding tag to the PR and will contact a supervisor and a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @tbrown91, do you agree to [supervise](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) this assembly?
Please reply to this message only with **OK** to give acknowledge.

**Comment by tbrown91** [comment]
yes

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-07-31 12:57

All Eligible Candidates:

Github ID  | Full Name       | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
-------------------------------------------------------------------------------------------------------------------------      
epaule     | Michael Paulini | Sanger      | 1             | 2024-07-25  | Y      | N    | 1001          | 1051          
tommathers | Tom Mathers     | Sanger      | 2             | 2024-07-08  | Y      | N    | 1000          | 1050          
additive3  | Jo Wood         | Sanger      | 2             | 2024-06-15  | Y      | N    | 999           | 1049          
tbrown91   | Tom Brown       | IZW         | 9             | 2024-07-05  | Y      | N    | 999           | 999           
diegomics  | Diego De Panis  | IZW         | 9             | 2024-07-05  | Y      | N    | 997           | 997           

Selected reviewer: Michael Paulini (epaule)
The decision was based on:
- different institution ('Sanger')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1051)
```

**Comment by diegomics** [comment]
Hi @epaule, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 07-AUG-2024 at 13:02 CET.

**Comment by epaule** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).
Contact the PR assignee for any issues.

**Comment by epaule** [comment]
Generally, I think it looks good.

But i am wondering if you want to assign the sex chromosomes, as a.) the coverage drops very nicely to 50% and there would be also comparators with XY in the Tenebrionidae.

Also the HiC looks a bit like it was from a different sample?

**Comment by duprats** [comment]
Hi,   that's right 
- scaffold SUPER_9     maps  to    OZ014547.1 (Tenebrio molitor, chromosome: X)
- HiC reads were from female sample while pacbio rd is from male sample

**Comment by epaule** [comment]
Do you want to rename the chromosomes? Else I would sign it off

**Comment by duprats** [comment]
yes ,

**Comment by duprats** [comment]
Do you need a new map and a new report  with new names ?  orat the time of submission to ena

**Comment by epaule** [comment]
personally, i don't mind, but i think it would be good to create a new report, so if someone ever goes back into the repo knows.

**Comment by duprats** [comment]
ok, I understand

**Comment by tbrown91** [comment]
Hello both @duprats @epaule 

Just checking in to see if this is ready to be closed. Are you still generating the HiC map? Otherwise I think we can consider this genome finished and ready to be uploaded to ENA

**Comment by duprats** [comment]
Hello, I've just create a new report with chromosomes  renamed . so  ready to be closed.

**Comment by epaule** [comment]
Generally fine, just would like that the chromosome naming changed from SUP_ to icDenFora10_ (and the sec chromosomes don't have any prefix). If that is as intended, I would sign it off.

**Review by epaule — APPROVED** [review]
if you are fine with the current sequence ids, it is good to go

**Comment by duprats** [comment]
there is no "SUP_" name

**Pull request merged**
