### PR TITLE
added Culex perexiguus / idCulPerx1

### PR DESCRIPTION
**Pull request by epaule**
## Assembly review request

- ToLID: idCulPerx1
- Species: Culex perexiguus
- Project: ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by epaule** [comment]
that annotation was done by @tommathers

**Comment by diegomics** [comment]
Hi @epaule, thanks for sending the EAR of _Culex perexiguus_.
I added the corresponding tag to the PR and will contact a supervisor and a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @tbrown91, do you agree to [supervise](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) this assembly?
Please reply to this message only with **OK** to give acknowledge.

**Comment by tbrown91** [comment]
OK

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-06-18 11:55

All Eligible Candidates:

Github ID | Full Name             | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
------------------------------------------------------------------------------------------------------------------------------
jesgomez  | Jessica Gomez Garrido | CNAG        | 1             | 2024-06-03  | Y      | N    | 1006          | 1056          
tbrown91  | Tom Brown             | IZW         | 8             | 2024-02-21  | Y      | N    | 994           | 994           

Selected reviewer: Jessica Gomez Garrido (jesgomez)
The decision was based on:
- different institution ('CNAG')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1056)
- Highest adjusted calling score.
```

**Comment by diegomics** [comment]
Hi @jesgomez, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 25-JUN-2024 at 11:57 CET.

**Comment by diegomics** [comment]
@epaule I'm fixing your PR title from `added Culex laticinctus / idCulLati1` to `added Culex perexiguus / idCulPerx1`

**Comment by jesgomez** [comment]
> Hi @jesgomez, do you agree to review this assembly? Please reply to this message only with **Yes** or **No** by 25-JUN-2024 at 11:57 CET.

Yes

**Review by jesgomez — CHANGES_REQUESTED** [review]
I took a look at the assembly and I think in general it looks good. A bit gappy due to a not too high contig N50 but in the pretext file I can see a good reconstruction of the three chromosomes. Congratulations!
I would just suggest to have a deeper look at the contigs that are tagged as something different to arthropoda or no-hit in the blobplot. Can you confirm that they are not contaminants? Specially the ones that show up in the left part of the plot (GC content lower than 0.3).  I see in the curator notes that there was already some decontamination performed with FCS-GX, but I think it's worth taking also a look at the blobtools tagged sequences. Thanks.

**Comment by tbrown91** [comment]
Some small things I noticed:

SUPER_1 88.5Mb - There is clearly sequence missing here from the centromere. Could the be scaffold_13? all these regions across the 3 chromosomes have very high mapping and interaction, so I'm not really sure how one can be confident they are placed in the correct chromosome
SUPER_1 96.0Mb - localises to SUPER_3 @ 76.1MB
SUPER_1 133.9Mb - localises to SUPER_2 unloc?
SUPER_2 71.8Mb - localised to SUPER_2 @ 26.9Mb - not sure about the one
SUPER_2 71.8Mb - Seems to also localise somewhere in SUPER_3, but not in 2. I can't find a specific location, so may unlocalised or unscaffolded
SUPER_3 30.9Mb - localises to SUPER_2 @ 138Mb
SUPER_3 32.9Mb - localises to SUPER_2 @ 54.5Mb
SUPER_3 41.1Mb - 42.5Mb - orientation looks wrong for at least one contig (41.48-41.64) maybe you can see better in higlass

I can't really tell much from the HiC map or the coverage track if there are duplications. Maybe there are some, but perhaps it's not possible to be certain - e.g. SUPER_3 @ 23.6Mb

Once again, it's pretty amazing that these assemblies get into chromosomes so well given how fragmented they are. @epaule @tommathers please look through @jesgomez's comments - particularly regarding contaminants - and a look through my suggestions if you have time.

I'm sure you guys will be pretty happy to get rid of the culex species

**Comment by tommathers** [comment]
Hi. Thanks both for the suggestions. I will have look through and update the assembly. I am on holiday next week so will get back to you week commencing 29th June.

**Comment by tbrown91** [comment]
image

**Comment by diegomics** [comment]
I'm replacing @jesgomez for the rest of the review since she's on leave for a few months. This review will still be computed to Jèssica.

**Comment by tbrown91** [comment]
Hi @tommathers 

Have you been able to give this assembly any thought? I am just back from vacation myself, so am slowly working through my outstanding items

**Comment by tommathers** [comment]
Hi @tbrown91. Finished the changes last week. The person that generates the EAR reports is now on holiday so will update this in a couple of weeks when he is back and we have a new EAR.

**Comment by tommathers** [comment]
New EAR now uploaded for checking :)

**Comment by tommathers** [comment]
@jesgomez - good catch on the contamination, I had missed it when looking at the map as buried in the small shrapnel.

**Comment by tommathers** [comment]
@tbrown91 I implemented your suggestions. Couple of clarifications on the more ambiguous bits:

_SUPER_1 88.5Mb - There is clearly sequence missing here from the centromere. Could the be scaffold_13? all these regions across the 3 chromosomes have very high mapping and interaction, so I'm not really sure how one can be confident they are placed in the correct chromosome_ 

**Have left this in shrapnel as HIC signal does not unambiguously place it.** 

_SUPER_2 71.8Mb - Seems to also localise somewhere in SUPER_3, but not in 2. I can't find a specific location, so may unlocalised or unscaffolded Have moved to shrapnel._ 

**Have moved to shrapnel.** 

_I can't really tell much from the HiC map or the coverage track if there are duplications. Maybe there are some, but perhaps it's not possible to be certain - e.g. SUPER_3 @ 23.6Mb_

**Have removed  additional small haplotigs**

**Comment by diegomics** [comment]
Hi @tommathers, thanks for updating the EAR. Is the pretext file linked also up-to-date? I'm still seeing some of the small things pointed out, e.g.:
Screenshot 2024-08-15 at 13 48 48

**Comment by tommathers** [comment]
Whoops, sorry. Think I made the map for the ear with an older fasta than than the one used for our internal check. Will upload again when I have remade the map.

**Review by diegomics — APPROVED** [review]
Hi @tommathers @epaule I'm happy with the current state of the assembly. I can tell this one was pretty challenging, congrats to all the Sanger team!

**Comment by diegomics** [comment]
I will add a new reviewed species for you to the table when @tbrown91 approves and merges the PR ;)

**Review by tbrown91 — APPROVED** [review]

**Pull request merged**
