### PR TITLE
Da che taga1 ear

### PR DESCRIPTION
**Pull request by csantos-alvess**
## Assembly review request

- ToLID: daCheTaga1
- Species: Cheirolophus tagananensis
- Project: ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by diegomics** [comment]
Hi @ldemirdj please accept and approve the review, it's the same one you did, we are just merging it correctly this time :) Sorry the inconvenience

**Comment by ldemirdj** [comment]
Yes

**Comment by diegomics** [comment]
This PR correspond to #91
Thanks all and sorry again!
Merging...

**Pull request merged**
