### PR TITLE
added daCheTaga1

### PR DESCRIPTION
**Pull request by csantos-alvess**
## Assembly review request

- ToLID: daCheTaga1
- Species: Cheirolophus tagananensis
- Project:  ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by ldemirdj** [comment]
Yes

**Comment by diegomics** [comment]
Hi @csantos-alvess :)
I'll take a proper look after @ldemirdj review, but something I noticed when checking very quickly at this:
SUPER_12 ends prematurely? It looks like it should be extended until the gap in SUPER_13 @ 209
Also, is this HiC-phased with curation using both haps?
Thx!

**Comment by csantos-alvess** [comment]
Hi @diegomics,
Thank you for your comment. Yes, I totally agree with you. There is telo signal @ 28.1 Kbp in SUPER_13 and I should have made a break there. I will correct it and generate a new map and a new report as soon as I get the comments from @ldemirdj. 
Yes, we have a phased map for this one. 
Thanks

**Comment by ldemirdj** [comment]
Hi @csantos-alvess and @diegomics, 

Thank you for submitting this assembly, it looks very good. I would only make the following modifications to properly align the telomeres at the ends and beginning of the scaffolds, ensuring a more accurate representation of the chromosomal structure:

- Edit 1: Inversion and relocation of the region SUPER_15 (23.52 Mbp to 0.00 bp) to SUPER_14 (24.43 Mbp).
- Edit 2: Inversion and relocation of the region SUPER_11 (29.10 Mbp to 0.00 bp) to SUPER_10 (31.82 Mbp).
- Edit 3: Inversion and relocation of the region SUPER_4 (39.41 Mbp to 0.00 bp) to SUPER_3 (47.05 Mbp).
- Edit 4: Inversion and relocation of the region SUPER_7 (36.48 Mbp to 0.00 bp) to SUPER_6 (36.59 Mbp).

Additionally, I totally agree with you. There is a telomeric signal at 28.1 Kbp in SUPER_13, and I would have made a break there.

Best,

Lola

**Comment by additive3** [comment]
Hi @ldemirdj 

> 
    Edit 1: Inversion and relocation of the region SUPER_15 (23.52 Mbp to 0.00 bp) to SUPER_14 (24.43 Mbp).
    Edit 2: Inversion and relocation of the region SUPER_11 (29.10 Mbp to 0.00 bp) to SUPER_10 (31.82 Mbp).
    Edit 3: Inversion and relocation of the region SUPER_4 (39.41 Mbp to 0.00 bp) to SUPER_3 (47.05 Mbp).
    Edit 4: Inversion and relocation of the region SUPER_7 (36.48 Mbp to 0.00 bp) to SUPER_6 (36.59 Mbp).

Not sure what you are infering here?

**Comment by ldemirdj** [comment]
Hi @additive3, I'm not entirely sure, but when we completely reverse these scaffolds (4 ; 7 ; 11 ; 15), telemetric repeats seem to appear at both the beginning and the end, where they weren't present initially. I hope my explanation is clear. Thanks ! 
Lola

**Comment by diegomics** [comment]
@csantos-alvess @ldemirdj @additive3 Do you think something similar to SUPER_12 and SUPER_13 can be happening in SUPER_14 and SUPER_15? We don't have Telo signal and gaps, but the contact density points to a boundary different to the assigned one. That's all I see in the assembly.
Please let me know what do you think, and share the savestate so we can approve the EAR before the PDF is regenerated to save time and start the ENA uploading of the new fasta.

**Comment by csantos-alvess** [comment]
Hi @diegomics , we think that in SUPER_14 and SUPER_15 it is only highly repetitive centromeric regions and as we don't have telo or gap signal we should not make a break. The new curated map with the edit you suggested for SUPER_12 and SUPER_13 and the save state file are here: https://drive.google.com/drive/folders/17hsU_W42G9jGsasg3RlHbsNG0x38_QMh?usp=share_link
Let me know what you think so I can generate a new report. Thanks

**Comment by diegomics** [comment]
All good from my side. If you hare happy with the savestate, please approve @ldemirdj

**Comment by ldemirdj** [comment]
Hi @csantos-alvess, @diegomics, 

Thank you for sharing the updated map and the save state file. I agree with your assessment regarding SUPER_14 and SUPER_15 — it makes sense not to make a break there. 

Everything looks good to me with the changes in SUPER_12 and SUPER_13 as well. Feel free to go ahead and generate the new report.

Thanks again!

**Review by ldemirdj — APPROVED** [review]

**Comment by diegomics** [comment]
@csantos-alvess I merged this but the PDF was removed in the update (I thought it was just updated as we were waiting, sorry I was in a meeting!) Can you update the PDF?

**Comment by csantos-alvess** [comment]
@diegomics, sure, I will do this. Sorry, didn't know the first one should't be removed.

**Comment by csantos-alvess** [comment]
@diegomics, can you see the PDF now?

**Comment by diegomics** [comment]
Hi @csantos-alvess 
A few things. First, I can see in your repo that you have two files:
https://github.com/epaule/EARs/tree/daCheTaga1_EAR/Assembly_Reports/Cheirolophus_tagananensis/daCheTaga1

You should only have one, the last version of the PDF, named daCheTaga1_EAR.pdf

Second, please create a new pull request so I can merge it correctly this time and the PDF can be part of the stable repo

**Comment by csantos-alvess** [comment]
Hi @diegomics, I just added the PDF  last version. Please check if everything is fine. Thanks

**Pull request merged**
