### PR TITLE
Devel - CorAlb Assembly Review

### PR DESCRIPTION
**Pull request by jpnm**
Species name: Corema album
Taxa: Embryophyta
Project: ERGA-Pilot

### CODE REVIEW

**Comment by tbrown91** [comment]
Hi Joao,

I'm a little concerned about the HiC library here. Are you able to get hold of the following statistics?

Total number of read pairs/total coverage
Number of mapped reads
Number of cis/trans interactions
Number of cis interactions >1kb
Number of cis interactions >10kb
Number of cis interactions >50kb

This also looks like a pretty interesting case of sex chromosomes in flowering plants. I guess this is a male plant as it looks like there are some heterogametic chromosomes in the merqury plots. Does this sound right to you?

@nadegeguiglielmoni I feel a little uneasy about the purging here, what do you think?

**Comment by nadegeguiglielmoni** [comment]
@tbrown91 Because of the k-mer spectra? I would try changing --xmax and --ymax.

**Comment by jpnm** [comment]
Hi Tom and Nadege,

I wanted to drop you a quick message to say sorry for taking so long to get back to you. I've been swamped with BGE tasks that needed my urgent attention. Because of these commitments, I'll need a few more weeks to find the right time to tackle the issue you've mentioned properly.

Thanks a lot for your feedback. I want you to know that as soon as I have some free time, I'll put all my energy into sorting this out in the best way possible.

I'll be in touch as soon as I have any updates.
Cheers

**Comment by tbrown91** [comment]
Hi @jpnm, not a problem, take your time. It's better everything is done correctly, rather than quickly.

**Pull request closed without merging**
