### PR TITLE
rMalMon1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
Assembly review request
---

ToLID: rMalMon1

Species: Malpolon monspessulanus

Project: ERGA-BGE

Affiliation: CNAG

### CODE REVIEW

**Comment by fcamara7** [comment]
I apologize for mApoAgr2, not sure how it got in there...Hope this is fine now..If not will try again tomorrow.

**Comment by diegomics** [comment]
Hi @fcamara7 
Thanks for sending the EAR of _Malpolon monspessulanus_.
I added the corresponding tag to the PR and appointed @tbrown91 as assignee to supervise.
I will contact a reviewer ASAP.

- By-passing the assignee's initial check. PR is looking good. EAR contact map reachable. 
- By-passing the EAR Reviewer Selection Process because Tom Mathers already jumped-in (#37)

**Comment by diegomics** [comment]
Hi @tommathers, do you agree to review this assembly? Please reply to this message only with Yes or No by 06-MAY-2024 at 20:03 CET.

**Comment by tommathers** [comment]
Yes

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Review by tommathers — CHANGES_REQUESTED** [review]
SUPER_1 break on gaps at ~2.5 Mb and ~11.4 Mb and flip chunk. 

SUPER_Z 9.678 Mb to 10.319 Mb in the Z PAR region should be moved to W as an unloc.

SUEPR W. Currently all but 1 chunk is unloc. There are various joins that can be made to scaffold more of W. There are also several misjoins in the unloc scaffolds that should be broken - where these chunks don’t place on the main W scaffold they can left as unlocs.

I have made a savestate with a suggested assembly of W (note cuts in W unloc scaffolds eg. W_unloc_2 and W_unloc_4) but the system wont let me upload it. I will send via email. 

In general it looks like W is incomplete. General background suggest W + W unlocs all go together but there are big drop offs in HIC signal on the diagonal which are indicative of missing content. I am not familiar with the nanopore assembly method used. However, if there is an alt assembly of hoplotigs it is possible that pieces of W are in the alt / haplotigs assembly. For pacbio hifi assemblies done with hifiasm with this problem we normally scaffold up the alt assembly and generate a merged map which we then use to move bits of the alt  back into the main assembly. 

If sticking with the current assembly then the W + unlocs strategy is fine but I would add a note to the release saying W is likely incomplete.

**Comment by tommathers** [comment]
HI  @fcamara7<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_fcamara7&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=foQVfTSV3-INWVAJm9XFWn-jvPEtnJ2n7Gpzf8SWXM0L-8nFE-0QtUQR6_4UjTPG&s=C-DI-KsCRR0gEXfirsGz3E9S_BzAxTGNw4sgz-vsrz4&e=>  - can you send me your email address? I have made a savestate with a suggested assembly of W but the github system wont let me upload it.

Thanks,

Tom.

Dr. Thomas Mathers
Senior Computer Biologist
Genome Reference Informatics Team
Tree of Life
Wellcome Sanger Institute
Hinxton
Cambridge
CB10 1SA

Twitter: @Thomas_Mathers [twitter.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_Thomas-5FMathers-3Flang-3Den-2Dgb&d=DwMGaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tJRHixSYq-VP6FIxTiP35xdkMZl3FaXQVx1qay3XZ-7I4UkhUxDC7h1P98bVhcBb&s=hffLCC65eIfPsnmm3hnO-CV4DYCZYG2ebSippldU3zw&e=>
Publications: Google Scholar [scholar.google.co.uk]<https://urldefense.proofpoint.com/v2/url?u=https-3A__scholar.google.co.uk_citations-3Fhl-3Den-26user-3D5XjBm94AAAAJ-26view-5Fop-3Dlist-5Fworks-26sortby-3Dpubdate&d=DwMFAg&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=KIKynKbLKfS4YVQYVctJHL39ls39CbRogxK7G0OumbwWdwS4Qdlkrg9NnRJHPJGs&s=T2pa4qY1i623xxULQ3x4gTTj4JvNcKbwYHoNm5knTFc&e=>


From: Diego De Panis ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Monday, 29 April 2024 at 21:58
To: ERGA-consortium/EARs ***@***.***>
Cc: Thomas Mathers ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] rMalMon1 EAR (PR #38) [EXT]


Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to Busy until you finish this review.
Please check the Wiki [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_wiki_Reviewers-2Dsection&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=mnAgIV0cwe1RgisojWJKIJX29oOTMmmAnASJofG9ziYBPPzwp3vzKy_8j8RJkU_H&s=WQb5eY1vcpgk8qMxJzG85HegkaMLUrsEPQYFlkdFxAc&e=> if you need to refresh something.
Contact the PR assignee for any issues.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_38-23issuecomment-2D2083650430&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=mnAgIV0cwe1RgisojWJKIJX29oOTMmmAnASJofG9ziYBPPzwp3vzKy_8j8RJkU_H&s=slATGmJqkgDEKv7LSdL-h3hUh31xaY8Swr_izY1EO-w&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3G2QWMLQ2DGM3MYM5OTY72X7LAVCNFSM6AAAAABG6RFK7SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBTGY2TANBTGA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=mnAgIV0cwe1RgisojWJKIJX29oOTMmmAnASJofG9ziYBPPzwp3vzKy_8j8RJkU_H&s=8UD4ebz_VbcxbQLat30GIK-cHxQpWXkTCYr9H33xV4w&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by tommathers** [comment]
Also, apologies. I just spotted a mistake with the first suggested correction above. For SUPER_1 you need to cut off beginning chunk on gap at ~2.5 Mb and place in gap at ~11.4 Mb. 

Cheers,

Tom.

**Comment by tbrown91** [comment]
Hi @tommathers You can upload via this "file-drop" link:

https://ergapilot.bsc.es/index.php/s/FGWMazw5Hq6ArMT

**Comment by fcamara7** [comment]
hi @tommathers, we really appreciate your reviewing it. I was actually in the process of building a HiRes, unsorted pretext map to make things easier for you, but looks like you do not need that for now? Since W was broken into (many) scaffolds what we did was to pick one of the large ones as W and the others as unlocs...Looking forward to your W assembly though! You can try sending it to francisco.camara at cnag dot eu please. Cheers

**Comment by tommathers** [comment]
Great – thanks for this. Have just uploaded the file.

Tom.


From: Tom Brown ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Tuesday, 30 April 2024 at 09:33
To: ERGA-consortium/EARs ***@***.***>
Cc: Thomas Mathers ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] rMalMon1 EAR (PR #38) [EXT]


Hi @tommathers [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tommathers&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tRwm-RYvRocmx9vPTcWVp8K07gu-u-zDpag5IxSIzrDFjTqxJAnTysxQ9gzswDnZ&s=RjCJSLyLvYUajCyM-Oo3Q7g1pP-WuVbEatf2xMeAfaQ&e=> You can upload via this "file-drop" link:

https://ergapilot.bsc.es/index.php/s/FGWMazw5Hq6ArMT [ergapilot.bsc.es]<https://urldefense.proofpoint.com/v2/url?u=https-3A__ergapilot.bsc.es_index.php_s_FGWMazw5Hq6ArMT&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tRwm-RYvRocmx9vPTcWVp8K07gu-u-zDpag5IxSIzrDFjTqxJAnTysxQ9gzswDnZ&s=SkfGdYw8bfEAIT9fvDdH_7m1KI3VtwoZagVJkbhaNRw&e=>

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_38-23issuecomment-2D2084707691&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tRwm-RYvRocmx9vPTcWVp8K07gu-u-zDpag5IxSIzrDFjTqxJAnTysxQ9gzswDnZ&s=UAPkCriCRenYeClYaYtj6Kp5qbOcPxeKdiJeDmFoLDY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3G47PWCMQIB4XGG2Z2DY75JMRAVCNFSM6AAAAABG6RFK7SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBUG4YDONRZGE&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tRwm-RYvRocmx9vPTcWVp8K07gu-u-zDpag5IxSIzrDFjTqxJAnTysxQ9gzswDnZ&s=FTaKDNmtkeo3h24mstP9J0a_pNAZXI0-_RXOgva-NYY&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by tbrown91** [comment]
@fcamara7 Do you have access to the BSC Nextcloud? We will use this for easy file-transfer between centres

**Comment by tommathers** [comment]
Thanks – I think the lower res map is fine for this QC, there are just a few changes to make.

I tried uploading the savestate via the link Tom sent – did you get the file?

Cheers,

Tom.


From: Francisco Câmara Ferreira ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Tuesday, 30 April 2024 at 09:34
To: ERGA-consortium/EARs ***@***.***>
Cc: Thomas Mathers ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] rMalMon1 EAR (PR #38) [EXT]


hi @tommathers [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tommathers&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=1dhR5TH4j7RJJAXaBKks0qDohthbte30k2XNDIjhVZVi9Op9s1AlZHmbieCHI5Ae&s=zp_INOsbMoUao__VyGm2gJe3pHTb0kDcmDX_mmXd5dA&e=>, we really appreciate your reviewing it. I was actually in the process of building a HiRes, unsorted pretext map to make things easier for you, but looks like you do not need that for now? Since W was broken into (many) scaffolds what we did was to pick one of the large ones as W and the others as unlocs...Looking forward to your W assembly though! You can try sending it to francisco.camara at cnag dot eu please. Cheers

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_38-23issuecomment-2D2084710734&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=1dhR5TH4j7RJJAXaBKks0qDohthbte30k2XNDIjhVZVi9Op9s1AlZHmbieCHI5Ae&s=kSmF_ZV6qz5shlmiHu_kW039VD8TkKgIM_P1vQhWScU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3GY2WWMZSUSVWJ6FKC3Y75JRNAVCNFSM6AAAAABG6RFK7SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBUG4YTANZTGQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=1dhR5TH4j7RJJAXaBKks0qDohthbte30k2XNDIjhVZVi9Op9s1AlZHmbieCHI5Ae&s=2CfvsvJshm_qzKR5M_BDAUfS4vtYTNxj3KzVis6pksA&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by tbrown91** [comment]
Thank you for the review @tommathers 

In the future, anyone at Sanger can use this Nextcloud instance we have set up for ERGA to share files between sites. Shane is the admin of the "DTOL" space, so you can ask him about how best to structure things. Diego and I also have admin rights over everything.

**Comment by fcamara7** [comment]
@tommathers I have the save state and will take a look at it thanks. I actually did not have access to the BSC Nextcloud @tbrown91 but Tyler does and he downloaded the file and gave me access from now on. We will take a look at it and get back to you asap. Thank you!

**Comment by fcamara7** [comment]
@tommathers @tbrown91 I have tried to implement the suggested changes, after reviewing them with Tyler.  For the suggested change: "SUPER_Z 9.678 Mb to 10.319 Mb in the Z PAR region should be moved to W as an unloc." we moved the  region to Z rather than W as an unloc as it seems to only match Z.

**Comment by tbrown91** [comment]
Thanks for the resubmission @fcamara7 Is SUPER_9 designated as the W chromosome? I can't seem to find either the W or Z scaffolds.

**Comment by fcamara7** [comment]
@tbrown91 I see..., I apologize but something seems to have happened with the re-mapping. Ignore the resubmission for now, I will try to find out what happened and re-do the mapping asap. The "pretextview" painting seems to have failed but I will check it.

**Comment by tbrown91** [comment]
Not a problem @fcamara7! It's no extra time for us. Looking forward to seeing the final map

**Comment by tbrown91** [comment]
Thanks @fcamara7 looks good to me

@tommathers Can I ask you to give the map one last look-over to make sure everything is looking ok.

**Comment by tommathers** [comment]
Hi – sorry for the delay. Will have a look this afternoon.



From: Tom Brown ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Monday, 13 May 2024 at 14:14
To: ERGA-consortium/EARs ***@***.***>
Cc: Thomas Mathers ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] rMalMon1 EAR (PR #38) [EXT]


Thanks @fcamara7 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_fcamara7&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=dv86Xm9RkcobasmEP7WSox3qAr1K1XtPXB7S1J2PF9JGFY8LwHtQNmzivOqBQBMN&s=hYa9HNFI-RhgWscmL345_zEOkAZ94FALTlvVVsdHLeI&e=> looks good to me

@tommathers [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tommathers&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=dv86Xm9RkcobasmEP7WSox3qAr1K1XtPXB7S1J2PF9JGFY8LwHtQNmzivOqBQBMN&s=Ri0gYjxGtd_Dajj1CVd88o_2oFDOtyWAdRjDpz2Xr0M&e=> Can I ask you to give the map one last look-over to make sure everything is looking ok.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_38-23issuecomment-2D2107549129&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=dv86Xm9RkcobasmEP7WSox3qAr1K1XtPXB7S1J2PF9JGFY8LwHtQNmzivOqBQBMN&s=Y2loCNdmh_rEsGjYshCWppYDQ8NUplN5hNZghUrIAP8&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3G4SYVUI2EUCSOSP2F3ZCC4ERAVCNFSM6AAAAABG6RFK7SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBXGU2DSMJSHE&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=dv86Xm9RkcobasmEP7WSox3qAr1K1XtPXB7S1J2PF9JGFY8LwHtQNmzivOqBQBMN&s=TgNkHg96Fjz4WfbK2mMTXFHwaKWjjTb_zkWKIXy9ouk&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by tommathers** [comment]
Hi - I am trying to look at the revised map but not sure if I have the correct file? If I download the pdf in the "files changed" section the pdf has a link to this file: rMalMon1_yahs_scaffolds_final.curated_primary.no_mt.scrubbed.rev1_mq40.extensions.pretext. Is this the latest version? On doanloading the map I see W is still not scaffolded up. 

image

**Comment by tommathers** [comment]
Also, I cant find the Z unloc mentioned in the chat above in rMalMon1_yahs_scaffolds_final.curated_primary.no_mt.scrubbed.rev1_mq40.extensions.pretext.

**Comment by tbrown91** [comment]
@fcamara7 Do you have any idea on the location of the unlocalised Z scaffold and the status of the W chromosome? Did you decide not to scaffold in the end, but to leave it all unlocalised?

**Comment by fcamara7** [comment]
@tommathers @tbrown91 I will resubmit the EAR report, but basically the link is the same as before except for the last six characters ... https://ccnag-my.sharepoint.com/:u:/g/personal/tyler_alioto_cnag_eu/EeRzhhQnPwNJmlGJfwAuSIQB8bWp3P97ycj1a5QzmlFDqQ?e=Sgx5WT Could you please take a look and let me know if you are seeing the pretext above whenever possible?

**Comment by fcamara7** [comment]
@tbrown91 I have double checked and the link in the EAR report ( https://ccnag-my.sharepoint.com/:u:/g/personal/tyler_alioto_cnag_eu/EeRzhhQnPwNJmlGJfwAuSIQB8bWp3P97ycj1a5QzmlFDqQ?e=Gxx47M) should also take you the correct pretext file above.

**Comment by fcamara7** [comment]
Also clicked on the link in the pdf file (I presumably submitted) and that takes me to the right pdf as well. The file is dated May 13th which is the correct date.

**Comment by tommathers** [comment]
Hi. I just downloaded the file in the link you pasted above and W looks like this: 
image

**Comment by tommathers** [comment]
I tried renaming the file in case the pretext cache was messing things up but still looks the same.

**Comment by fcamara7** [comment]
@tommathers let me take a more careful look tomorrow and I will get back to you. Chr_W was not scaffold "painted" indeed so it looks like several scaffolds. However I also noticed some other minor issues so I will take a look and get back to you asap.

**Comment by tbrown91** [comment]
@fcamara7 Thank you for resubmitting and for the explanation for how you dealt with the W chromosome. @tommathers Could I ask you to give the map one last look-over to make sure there are no major errors? From what I can see, there is a lot of unlocalised sequence for the W, but they have done a pretty good job.

**Comment by fcamara7** [comment]
Hi @tbrown91 we tried to do the best we could with the W. It was pretty difficult to order & orient due to its repetitive nature and as @DomAbsolon mentioned on a previous message I am quite sure that we did not even recover all of it. Initially in fact all of the W was purged by purge_dups and only by going back to the polished assembly pre-purging were we able to recover part of it.

**Comment by tommathers** [comment]
Hi @tbrown91. I'm trying to download the new map but getting this error: 
image

**Comment by tommathers** [comment]
Any idea what might be wrong? Not sure if it is something at my end or not.

**Comment by tbrown91** [comment]
Good catch 

@fcamara7 could you please make the link publicly downloadable?

**Review by tommathers — APPROVED** [review]
Looks good.

**Comment by tbrown91** [comment]
Thanks @tommathers 

Good job @fcamara7 and team on another assembly

**Review by tbrown91 — APPROVED** [review]

**Comment by tbrown91** [comment]
Congrats on the assembly @fcamara7 
You are good to go to [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission).
Thanks all, merging now.

**Pull request merged**
