### PR TITLE
add Androsace saussurei

### PR DESCRIPTION
**Pull request by auryjm**
## Assembly review request

- ToLID: ddAndSaus20
- Species: Androsace saussurei
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @auryjm, thanks for sending the EAR of _Androsace saussurei_.
I added the corresponding tag to the PR and will contact a supervisor and a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @tbrown91, do you agree to [supervise](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) this assembly?
Please reply to this message only with **OK** to give acknowledge.

**Comment by tbrown91** [comment]
OK

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-07-25 12:05

All Eligible Candidates:

Github ID  | Full Name     | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
-----------------------------------------------------------------------------------------------------------------------
SarahPelan | Sarah Pelan   | Sanger      | 1             | 2024-03-22  | Y      | N    | 1001          | 1051          
DomAbsolon | Dom Absolon   | Sanger      | 1             | 2024-04-22  | Y      | N    | 1001          | 1051          
additive3  | Jo Wood       | Sanger      | 2             | 2024-06-15  | Y      | N    | 1000          | 1050          
tommathers | Tom Mathers   | Sanger      | 2             | 2024-07-08  | Y      | N    | 1000          | 1050          
gitcruz    | Fernando Cruz | CNAG        | 1             | 2024-07-15  | Y      | N    | 1000          | 1050          
tbrown91   | Tom Brown     | IZW         | 9             | 2024-07-05  | Y      | N    | 993           | 993           

Selected reviewer: Sarah Pelan (SarahPelan)
The decision was based on:
- different institution ('Sanger')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1051)
- chosen based on oldest review and fewest reviews among the finalists
```

**Comment by diegomics** [comment]
Hi @SarahPelan, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 01-AUG-2024 at 12:07 CET.

**Comment by tbrown91** [comment]
Hi @auryjm 

I will wait for the reviewers comments as well, but my first thoughts are it looks like there are a number of gaps in one of the chromosomal pairs along the the genome, and I wonder if it would be better to create a set of 20 "best" chromosomes

Here an example of what looks to be 3Mb which is missing in chromosome 30
image

Let me know what you think

**Comment by SarahPelan** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).
Contact the PR assignee for any issues.

**Comment by SarahPelan** [comment]
Hi @auryjm and @diegomics,

I have reviewed ddAndSaus20.

Just as an initial observation, it's good to have the sister chromatids in the same orientation as each other for submission.

There seem to be several haps remaining in the assembly.  As it is indicated as an octoploid assembly, these could belong with the other sets of chromosomes so it may be beneficial to have all the copies in one assembly for curation (although this might be a bit of a headache to look at)

For the regions where sequence is missing as has already been mentioned above, is it possible that these were removed during the purge dups stage? 

Things I found (most of these are small hap issues):

ddAndSaus20_20 missing approx 2.2Mb @ ~17.9Mb compared to ddAndSaus20_19

ddAndSaus20_18 missing approx 1.5Mb @ ~17.3Mb compared to ddAndSaus20_17

ddAndSaus20_8 missing approx 2.6Mb @ ~1Mb and approx 1.8Mb @ 3.3Mb compared to ddAndSaus20_7

regions of 0- 2.2Mb of ddAndSaus20_29 and 0-2.1Mb of ddAndSaus20_30 need to be swapped.

ddAndSaus20_30 missing approx 3Mb @ ~17.3Mb compared to ddAndSaus20_29

ddAndSaus20_11, ~6.6-7.0Mb I think this looks slightly mbetter in the other orientation, and scaffold_105 is a hap of part of this region

ddAndSaus20_32 looks like a small region of duplication at approx 20.1Mb

ddAndSaus20_21 is missing approx 181Kbp @ ~ 1.6Mb (the first ~181Kbp of ddAndSais20_22)

ddAndSaus20_22 is missing the first approx 1.6Mb compared to ddAndSaus20_21

ddAndSaus20_24 missing the first approx 1.3Mb and from approx 13.47Mb to the end compared to ddAndSaus20_23

scaffold_62 belongs to ddAndSaus20_28, maybe unloc

scaffold_72 looks like a hap of ddAndSaus20_17 @ ~8.8Mb

scaffold_140 hap of ddAndSaus20_17 @ ~5.8Mb

scaffold_161 hap of ddAndSaus20_17 @ ~9.4Mb

scaffold_125 hap of ddAndSaus20_17 @ ~6.4Mb

scaffold_186 hap of ddAndSaus20_17 @ ~21.7Mb

scaffold_142 hap of ddAndSaus20_20 @ ~4Mb

scaffold_56, scaffold_67 and scaffold_76 belong in ddAndSaus20_1 @ ~10.5

scaffold_167, hap of ddAndSaus20_1 @ ~10Mb

scaffold_88 possible hap of ddAndSaus20_2 @ ~19.6, but coverage is high so could be from one of the other haplotypes

scaffold_74 possibly belongs in ddAndSaus20_2 @ ~10Mb

scaffold_159 possible hap of ddAndSaus20_3 @ ~1Mb

scaffold_84 and scaffold_104 go in ddAndSaus20_3 @ ~ 10.7Mb

scaffold_151 hap of ddAndSaus20_3 @ ~ 20.6Mb

scaffold_117 hap of start of ddAndSaus20_5

scaffold_79 possibly goes in ddAndSaus20_5 @ ~217Kbp

scaffold_138 possibly goes. in ddAndSaus20_4 @ ~10.8Mb

scaffold_52 hap of first ~170Kb of ddAndSaus20_15

scaffold_89, scaffold_118 and scaffold_133 belong in ddAndSaus20_15 @ ~12.9Mb

scaffold_168 hap of both xddAndSaus20_15 @ ~15.9Mb and ddAndSaus20_16 @ ~1.1Mb

scaffold_157 hap of ddAndSaus20_16 @ ~8Mb

scaffold_48 hap of both ddAndSaus20_15 @ ~9.5Mb and ddAndSaus20_17 @ ~12.2Mb

scaffold_149 hap of ddAndSaus20_16 @ 17.3Mb

scaffold_85 belongs to ddAndSaus20_11 @ ~ 19.7Mb

scaffold_83 possibly join to end of ddAndSaus20_11, but has very small hap dup at it’s start

scaffold_73 hap of ddAndSaus20_11 @ ~ 11.0Mb

scaffold_95 hap of ddAndSaus20_12 @ ~9.0Mb

ddAndSaus20_14 region between 11.7Mb and 12.1Mb looks strange. I think 12.0-12.1Mb is a hap, and scaffold_102 joins in where this is removed from

scaffold_54, scaffold_119 and scaffold_143 belong in ddAndSaus20_10 @ ~ 11.1Mb

scaffold_173 hap of ddAndSaus20_9 @ ~7.3Mb

scaffold_64 and scaffold_129 haps of ddAndSaus20_29 @ ~ 1,9Mb

scaffold_113 hap of ddAndSaus20_30 @ ~4.3Mb

scaffold_114 hap of ddAndSaus20_30 @ ~9.2Mb

scaffold_65 hap of ddAndSaus20_30 @ ~11.2Mb

scaffold_155 belongs in ddAndSaus20_31 @ ~10Mb

scaffold_139 hap of above region (scaffold_155 and ddAndSaus20_31 @ ~10Mb)

scaffold_81 possibly belongs in ddAndSaus20_32 @ ~1Mb. might have a small amount of hap on the end

scaffold_170, I would add this as a 3rd unloc for ddAndSaus20_33

scaffold_78, hap of ddAndSaus20_33 @ ~10.7Mb

scaffold_109, belongs to ddAndSaus20_35 @ ~ 8Mb

scaffold_80 hap of ddAndSaus20_21 @ ~ 5.5Mb

scaffold_160, hap of ddAndSaus20_21 @ ~ 7.5Mb

scaffold_156, hap of ddAndSaus20_21 @ ~ 8.6Mb

ddAndSaus20_22 @ ~ 10.5Mb looks like potentially retained hap, also scaffold_68 maps to this region, possibly part of hap

scaffold_98 and scaffold_107 belong in ddAndSaus20_22 @ ~ 8.4Mb

scaffold_101 hap of ddAndSaus20_22 @ ~ 7.3Mb

scaffold_108 may join into ddAndSaus20_24 @ ~ 3Mb

scaffold_90, hap of ddAndSaus20_26 @ ~ 6.5Mb

scaffold_53, scaffold_96 and scaffold_126 belong in ddAndSaus20_25 @~ 9.2Mb

scaffold_62 and scaffold_103 belong in ddAndSaus20_28 @ ~ 9Mb

I’m not sure that the unlocs labelled for ddAndSaus20_38 convincingly belong to ddAndSaus20_38 as they seem to have the same signal to other chr’s

ddAndSaus20_38_unloc_3 and ddAndSaus20_38_unloc_4 seem to have affinity to both ddAndSaus20_38,ddAndSaus20_37, ddAndSaus20_39 and ddAndSaus20_40 so maybe don’t assign to a chromosome

scaffold_100 hap of ddAndSaus20_40 @ ~ 9.4Mb

Thanks,
Sarah

**Comment by auryjm** [comment]
Thank you, Sarah, this is an in-depth review! 

I will go through the things you found, but I can already provide some information. I made a mistake in the EAR report: the assembly was performed using Nextdenovo, and allelic duplications were not purged to avoid excessive removal of sequences. Note that the Hifiasm assembly had a cumulative size of 350Mb compared to 800Mb with Nextdenovo. I suggest this is an octoploid genome but it could also be a tetraploid. To proceed, I think we need to detect polymorphism.

Jean-Marc

**Comment by auryjm** [comment]
> Hi @auryjm
> 
> I will wait for the reviewers comments as well, but my first thoughts are it looks like there are a number of gaps in one of the chromosomal pairs along the the genome, and I wonder if it would be better to create a set of 20 "best" chromosomes
> 
> Here an example of what looks to be 3Mb which is missing in chromosome 30 image
> 
> Let me know what you think

Sorry I didn't see your remarks earlier. Indeed, as I mentioned in the curation notes, I suggest a gene conversion event between two regions of the homologous chromosomes that are 100% identical, causing the assembler to merge them into a single region. This is confirmed by the coverage of this region, which is double compared to other regions. For instance, we can see the same pattern in Brassica napus (rapeseed), which is a hybrid composed of two subgenomes, A and C. However, an assembly of this genome should contain both subgenomes and not a single set of chromosomes.
Jean-Marc

**Comment by tbrown91** [comment]
Hi Jean-Marc,

Based on what you've said it sounds likely to be tetraploid. I was suggesting making a primary and alternate assembly, with 20 chromosomes in each, which would be consistent with the output of hifiasm.

Do you have indications from genomescope or smudgeplot that the genome is indeed octoploid and not tetraploid?

**Comment by auryjm** [comment]
Hi @SarahPelan and @tbrown91,

I made the requested changes (see below) and generated a new pretext map and EAR report.

A few comments :
1. Smudgeplot predicted a tetraploid genome, consistent with only 20 chromosomes for the haploid genome. I was a bit confused because generally, the assembler did not successfully generate both maternal and paternal alleles. So, we probably should generate a version with the 20 most complete chromosomes. Before that, I will send a message to the sample ambassador to get his feedback on that.
2. The assembly is now named ddAndSaus6; the initial name (ddAndSaus20) was incorrect.
3. Hifiasm generated a haploid assembly of around 790M, but then purgedup eliminated half of the assembly.
4. Now the chromosomes are better organized and in the correct orientation; they were shuffled when I generated the final fasta file.

Jean-Marc
==========================
OK GC - ddAndSaus20_20 missing approx 2.2Mb @ ~17.9Mb compared to ddAndSaus20_19

OK GC - ddAndSaus20_18 missing approx 1.5Mb @ ~17.3Mb compared to ddAndSaus20_17

OK GC - ddAndSaus20_8 missing approx 2.6Mb @ ~1Mb and approx 1.8Mb @ 3.3Mb compared to ddAndSaus20_7

OK done - regions of 0- 2.2Mb of ddAndSaus20_29 and 0-2.1Mb of ddAndSaus20_30 need to be swapped.

OK GC - ddAndSaus20_30 missing approx 3Mb @ ~17.3Mb compared to ddAndSaus20_29

OK done and scaffold_105 tagged as Haplotig - ddAndSaus20_11, ~6.6-7.0Mb I think this looks slightly mbetter in the other orientation, and scaffold_105 is a hap of part of this region

OK moved to homologous chromosome (ddAndSaus20_31) : ddAndSaus20_32 looks like a small region of duplication at approx 20.1Mb

OK moved 181Kbp of ddAndSaus20_22 to ddAndSaus20_21, unique part is now on the same chromosome : ddAndSaus20_21 is missing approx 181Kbp @ ~ 1.6Mb (the first ~181Kbp of ddAndSais20_22)

OK GC : ddAndSaus20_22 is missing the first approx 1.6Mb compared to ddAndSaus20_21

OK GC : ddAndSaus20_24 missing the first approx 1.3Mb and from approx 13.47Mb to the end compared to ddAndSaus20_23

OK scaffold_62 moved to ddAndSaus20_28 @9Mb in an existing gap : scaffold_62 belongs to ddAndSaus20_28, maybe unloc

OK scaffold_72 tagged as Haplotig : scaffold_72 looks like a hap of ddAndSaus20_17 @ ~8.8Mb

OK scaffold_140 tagged as Haplotig : scaffold_140 hap of ddAndSaus20_17 @ ~5.8Mb

OK scaffold_161 tagged as Haplotig : scaffold_161 hap of ddAndSaus20_17 @ ~9.4Mb

OK scaffold_125 tagged as Haplotig : scaffold_125 hap of ddAndSaus20_17 @ ~6.4Mb

OK scaffold_186 tagged as Haplotig : scaffold_186 hap of ddAndSaus20_17 @ ~21.7Mb

OK scaffold_142 tagged as Haplotig : scaffold_142 hap of ddAndSaus20_20 @ ~4Mb

OK three scaffolds moved in ddAndSaus20_1 @ ~10.5 in an existing gap : scaffold_56, scaffold_67 and scaffold_76 belong in ddAndSaus20_1 @ ~10.5

OK scaffold_167 tagged as Haplotig : scaffold_167, hap of ddAndSaus20_1 @ ~10Mb

OK scaffold_88 moved to ddAndSaus20_1 @ ~20.5 in an existing gap : scaffold_88 possible hap of ddAndSaus20_2 @ ~19.6, but coverage is high so could be from one of the other haplotypes

OK moved scaffold_74 in ddAndSaus20_2 @ ~10Mb in an existing gap : scaffold_74 possibly belongs in ddAndSaus20_2 @ ~10Mb

OK scaffold_159 tagged as Haplotig : scaffold_159 possible hap of ddAndSaus20_3 @ ~1Mb

OK moved scaffold_84 and scaffold_104 in ddAndSaus20_3 @ ~10.7Mb in an existing gap : scaffold_84 and scaffold_104 go in ddAndSaus20_3 @ ~ 10.7Mb

OK scaffold_151 tagged as Haplotig : scaffold_151 hap of ddAndSaus20_3 @ ~ 20.6Mb

OK scaffold_117 tagged as Haplotig : scaffold_117 hap of start of ddAndSaus20_5

OK moved scaffold_79 possibly goes in ddAndSaus20_5 @ ~217Kbp in an existing gap : scaffold_79 possibly goes in ddAndSaus20_5 @ ~217Kbp

OK moved scaffold_138 in ddAndSaus20_4 @ ~10.8Mb in an existing gap : scaffold_138 possibly goes. in ddAndSaus20_4 @ ~10.8Mb

OK scaffold_52 tagged as Haplotig : scaffold_52 hap of first ~170Kb of ddAndSaus20_15

OK moved scaffold_89, scaffold_118 and scaffold_133 in ddAndSaus20_15 @ ~12.9Mb in an existing gap : scaffold_89, scaffold_118 and scaffold_133 belong in ddAndSaus20_15 @ ~12.9Mb

OK scaffold_168 tagged as Haplotig : scaffold_168 hap of both xddAndSaus20_15 @ ~15.9Mb and ddAndSaus20_16 @ ~1.1Mb

OK scaffold_157 tagged as Haplotig : scaffold_157 hap of ddAndSaus20_16 @ ~8Mb

OK scaffold_48 tagged as Haplotig : scaffold_48 hap of both ddAndSaus20_15 @ ~9.5Mb and ddAndSaus20_17 @ ~12.2Mb

OK scaffold_149 tagged as Haplotig : scaffold_149 hap of ddAndSaus20_16 @ 17.3Mb

OK moved scaffold_85 in ddAndSaus20_11 @ ~ 19.7Mb in an existing gap : scaffold_85 belongs to ddAndSaus20_11 @ ~ 19.7Mb

OK moved scaffold_83 in ddAndSaus20_11 but tagged as Haplotig the first 24Kb : scaffold_83 possibly join to end of ddAndSaus20_11, but has very small hap dup at it’s start

OK scaffold_73 tagged as Haplotig : scaffold_73 hap of ddAndSaus20_11 @ ~ 11.0Mb

OK scaffold_95 tagged as Haplotig : scaffold_95 hap of ddAndSaus20_12 @ ~9.0Mb

OK region 12.0-12.1Mb tagged as Haplotig and scaffold_102 moved in ddAndSaus20_14 in the newly created gap : ddAndSaus20_14 region between 11.7Mb and 12.1Mb looks strange. I think 12.0-12.1Mb is a hap, and scaffold_102 joins in where this is removed from

OK scaffold_54, scaffold_119 and scaffold_143  moved to ddAndSaus20_10 @ ~ 11.1Mb : scaffold_54, scaffold_119 and scaffold_143 belong in ddAndSaus20_10 @ ~ 11.1Mb

OK scaffold_173 tagged as Haplotig : scaffold_173 hap of ddAndSaus20_9 @ ~7.3Mb

OK scaffold_64 and scaffold_129 tagged as Haplotig : scaffold_64 and scaffold_129 haps of ddAndSaus20_29 @ ~ 1,9Mb

OK scaffold_113 tagged as Haplotig : scaffold_113 hap of ddAndSaus20_30 @ ~4.3Mb

OK scaffold_114 tagged as Haplotig : scaffold_114 hap of ddAndSaus20_30 @ ~9.2Mb

OK scaffold_65 tagged as Haplotig : scaffold_65 hap of ddAndSaus20_30 @ ~11.2Mb

OK scaffold_155 moved to ddAndSaus20_31 @ ~10Mb in an existing gap :  scaffold_155 belongs in ddAndSaus20_31 @ ~10Mb

OK scaffold_139 tagged as Haplotig : scaffold_139 hap of above region (scaffold_155 and ddAndSaus20_31 @ ~10Mb)

OK scaffold_81 moved to ddAndSaus20_32 @ ~1Mb in an existing gap and tagged as Haplotig the last 12Kb : scaffold_81 possibly belongs in ddAndSaus20_32 @ ~1Mb. might have a small amount of hap on the end

OK scaffold_170 tagged as Unloc in ddAndSaus20_33 : scaffold_170, I would add this as a 3rd unloc for ddAndSaus20_33

OK scaffold_78 tagged as Haplotig : scaffold_78, hap of ddAndSaus20_33 @ ~10.7Mb

OK but tagged as unloc in ddAndSaus20_35, no clear location and no existing gap : scaffold_109, belongs to ddAndSaus20_35 @ ~ 8Mb

OK scaffold_80 tagged as Haplotig : scaffold_80 hap of ddAndSaus20_21 @ ~ 5.5Mb

OK scaffold_160 tagged as Haplotig : scaffold_160, hap of ddAndSaus20_21 @ ~ 7.5Mb

OK scaffold_156 tagged as Haplotig : scaffold_156, hap of ddAndSaus20_21 @ ~ 8.6Mb

OK scaffold_68 moved to this region, retained hap is not evident even if the coverage is a bit lower. I would prefer keep this region as it was : ddAndSaus20_22 @ ~ 10.5Mb looks like potentially retained hap, also scaffold_68 maps to this region, possibly part of hap

OK scaffold_98 and scaffold_107 moved to ddAndSaus20_22 @ ~ 8.4Mb : scaffold_98 and scaffold_107 belong in ddAndSaus20_22 @ ~ 8.4Mb

OK scaffold_101 tagged as Haplotig : scaffold_101 hap of ddAndSaus20_22 @ ~ 7.3Mb

OK scaffold_108 moved to ddAndSaus20_24 @ ~ 3Mb : scaffold_108 may join into ddAndSaus20_24 @ ~ 3Mb

OK scaffold_90 tagged as Haplotig : scaffold_90, hap of ddAndSaus20_26 @ ~ 6.5Mb

OK scaffold_53, scaffold_96 and scaffold_126 moved to ddAndSaus20_25 @~ 9.2Mb : scaffold_53, scaffold_96 and scaffold_126 belong in ddAndSaus20_25 @~ 9.2Mb

OK scaffold_62 already moved, scaffold_103 moved to ddAndSaus20_28 @ ~ 9Mb : scaffold_62 and scaffold_103 belong in ddAndSaus20_28 @ ~ 9Mb

I’m not sure that the unlocs labelled for ddAndSaus20_38 convincingly belong to ddAndSaus20_38 as they seem to have the same signal to other chr’s

OK, I did not assign these contigs to chromosome 38 : ddAndSaus20_38_unloc_3 and ddAndSaus20_38_unloc_4 seem to have affinity to both ddAndSaus20_38,ddAndSaus20_37, ddAndSaus20_39 and ddAndSaus20_40 so maybe don’t assign to a chromosome

OK scaffold_100 tagged as Haplotig : scaffold_100 hap of ddAndSaus20_40 @ ~ 9.4Mb

**Comment by tbrown91** [comment]
Hi @auryjm,

This is looking pretty good. It's amazing to see how many inversions and rearrangements there are between the chromosomal copies. Overall, I think the scaffolding looks complete.

Regarding the ploidy, It is most important for the submission to ENA. Are you planning to submit one assembly with 40 chromosomes, 2 with 20 or 4 with 10 each? Based on the Hi-C map, I would suggest submitting primary and alt assemblies, with the best version of each of the 20 chromosomes in the primary. But as you say, if the sample provider has better input then that would be very helpful.

@SarahPelan can I ask you to give the map one last look through and let us know if you have any further thoughts on the assembly?

Thank you both for the time and hard work. This is a really nice output from the BGE project.

**Review by SarahPelan — APPROVED** [review]
Hi @auryjm and @diegomics,
Apologies for the delay in looking at this one again, I have been on annual leave.

Thanks for making all the changes, I think it looks great now.

Sarah

**Pull request merged**
