### PR TITLE
ibLobCana1 EAR

### PR DESCRIPTION
**Pull request by gitcruz**
## Assembly review request

- ToLID: ibLobCana1
- Species: Loboptera canariensis
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
OK

**Comment by gitcruz** [comment]
Thanks @diegomics  and @andar27

**Comment by andar27** [comment]
Hi @gitcruz 
This assembly looks very good. I don't see anything that would require to be changed.

Best
Adama

**Comment by gitcruz** [comment]
Thanks Adama,

Let's see if @diegomics have some comment otherwise, I then I'll ask you fro approval and  he can merge the PR.

Best,
Fernando

**Comment by diegomics** [comment]
Hi @gitcruz, sorry for the delay.
This assembly is actually not super friendly for a quick review (at least at the pretext resolution... should be clearer with higlass, do you have it?). If not, maybe @additive3 can take a quick look, he usually sees things using pretext that I can only see with higlass...
Out of curiosity, what's the heterozygosity level according to Genomescope2? Also, there are a lot of gaps, but still less than 1000 per Gbp, so all good.
I'm confused about the "Sex chromosome unknown" but Expected & Observed: XX.
Have you tried to place some scaffolds as unloc? I'm wondering if "sco_38" should not be unloc to SUPER_13?
I will take a look now at the other Blattodea EAR you guys sent

**Comment by gitcruz** [comment]
_**_Hi @ diegomics,

Thanks for your comments and review. See my responses below, inserted in your previous message._**_

> Hi @gitcruz, sorry for the delay. This assembly is actually not super friendly for a quick review (at least at the pretext resolution... should be clearer with higlass, do you have it?). 

**We haven't generated the higlass map. I guess the higher resolution allows localizing much better small scaffolds/contigs. I think it takes time to set this up...but could upload a high res map from pretext, although I don't usually see much difference. In my opinion this map has high hic density and confirms the supers as chromosomes.**

If not, maybe @additive3 can take a quick look, he usually sees things using pretext that I can only see with higlass...

**Sure, you can pass it to Jo. I think it might delay things a  bit though, but if you think it's going to improve the assemby go ahead.**

 Out of curiosity, what's the heterozygosity level according to Genomescope2? 

**As for the other cockroaches in the genus it was relatively high: Heterozygous (ab) 1.51476%-1.53835%**

Also, there are a lot of gaps, but still less than 1000 per Gbp, so all good. 

**Yes, it was realtively well contigged N50 8.65 thanks.**

I'm confused about the "Sex chromosome unknown" but Expected & Observed: XX. 

**Yes, let me explain the reason is that we have assembled a female XX and males are expected to be X0. So we know this assembly contains two X chromosomes but I don't know which SUPER corresponds to the X. We can't tell based in coverage.**

Have you tried to place some scaffolds as unloc? I'm wondering if "sco_38" should not be unloc to SUPER_13? 

**Good catch, this was left behind with the set of unplaced scaffolds. I agree that can be placed in SUPER_13 but not localize it. On top of this there is another scaffold, scaffold_40 that is a haplotig of scaffold_38 (see the coverage signal in the snapshot).**

ibLobCana1_SUPER_13_unloc

**Thus I suggest to do this and generate the final assembly. Added the savestate with this change to the shared folder:  ibLobCana1.curated_primary.no_mt.scrubbed_mq40.extensions.pretext.savestate_FC_1** 

I will take a look now at the other Blattodea EAR you guys sent

**Sure, go ahead.**

**Thanks again,
    Fernando**

**Comment by gitcruz** [comment]
Hi @diegomics 

Then I will ask @andar27  to appove the PR and you to merge it aftewards.

I will run the rapid scripts to generate the ibLobCana1.1 and start the ENA upload of this assembly together with its mitogenome.

By the way,  I'll chime in the converstation with Francisco about troglobia to clarify some comments.

Thanks both for the review
Fernando

**Review by andar27 — APPROVED** [review]

**Comment by diegomics** [comment]
Thank you all, merging now!

**Comment by gitcruz** [comment]
Hi @diegomics,

Please check the Blattodea's comparison in [PR#126](https://github.com/ERGA-consortium/EARs/pull/126)

Do you agree on me tagging SUPER_4 as X? Do you want me to regenerate the EAR with a small comment about this ...saying that despite being a female we identifeid the X via WGA to other species in the genus. More than anything it would be useful to remember when we'll write the Genome Note.

Thanks!

**Comment by gitcruz** [comment]
Great Thanks!

**Pull request merged**
