### PR TITLE
add Deroceras lasithionense/xgDerLasi

### PR DESCRIPTION
**Pull request by CaroB-M**
## Assembly review request

- ToLID: xgDerLasi 
- Species:Deroceras lasithionense
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @CaroB-M, thanks for sending the EAR of _Deroceras lasithionense_.
I added the corresponding tag to the PR and will contact a supervisor and a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @tbrown91, do you agree to [supervise](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) this assembly?
Please reply to this message only with **OK** to give acknowledge.

**Comment by tbrown91** [comment]
ok

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-07-25 15:11

All Eligible Candidates:

Github ID  | Full Name     | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
-----------------------------------------------------------------------------------------------------------------------
gitcruz    | Fernando Cruz | CNAG        | 1             | 2024-07-15  | Y      | N    | 1007          | 1057          
DomAbsolon | Dom Absolon   | Sanger      | 1             | 2024-04-22  | Y      | N    | 1001          | 1051          
tommathers | Tom Mathers   | Sanger      | 2             | 2024-07-08  | Y      | N    | 1000          | 1050          
additive3  | Jo Wood       | Sanger      | 2             | 2024-06-15  | Y      | N    | 999           | 1049          
tbrown91   | Tom Brown     | IZW         | 9             | 2024-07-05  | Y      | N    | 999           | 999           

Selected reviewer: Fernando Cruz (gitcruz)
The decision was based on:
- different institution ('CNAG')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1057)
- Highest adjusted calling score.
```

**Comment by diegomics** [comment]
Hi @gitcruz, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 01-AUG-2024 at 15:12 CET.

**Comment by diegomics** [comment]
Time is out! I will look for another reviewer :)

**Comment by gitcruz** [comment]
Hi Diego,

I am on holidays right now. I will be back in business on August 19th.

Cheers,
Fernando

**Comment by tommathers** [comment]
Yes

From: Diego De Panis ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Thursday 1 August 2024 at 14:16
To: ERGA-consortium/EARs ***@***.***>
Cc: Thomas Mathers ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] add Deroceras lasithionense/xgDerLasi (PR #50) [EXT]


Hi @tommathers [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tommathers&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=mW2bfmbVmC2icLgejm6U7wkjSl6VN5TR35P5HLQSaSYn1zWaVUc2nmh-3ivmAmA4&s=fYMDiQy2TCWUu7nS6zQiZGgOCAZPGGRdapEQhMgjZCs&e=>, do you agree to review this assembly?
Please reply to this message only with Yes or No by 08-AUG-2024 at 15:15 CET.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_50-23issuecomment-2D2263016321&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=mW2bfmbVmC2icLgejm6U7wkjSl6VN5TR35P5HLQSaSYn1zWaVUc2nmh-3ivmAmA4&s=A9SLEkNtJXqFAKyuGqDccUIHvfegkJK1gt0AkevmLoU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3G5J52SML7L566M65GDZPIYJ5AVCNFSM6AAAAABLOQOY3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRTGAYTMMZSGE&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=mW2bfmbVmC2icLgejm6U7wkjSl6VN5TR35P5HLQSaSYn1zWaVUc2nmh-3ivmAmA4&s=UxbcAFOmIny0shQy2gn6eTgEjV6kzt6JUPMjvvAhzdU&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).
Contact the PR assignee for any issues.

**Review by tommathers — CHANGES_REQUESTED** [review]
Chrom 1: retained hap at 48.7 Mb. 

Chrom 24 chunk from gap at 18.9 Mb to gap at 19.1 Mb moves to 18.4 Mb.

Chrom 29: retained hap at 10.8 Mb.

Chrom 31 and chrom 32 join. 

A lot of the shrapnel can either be localaised to specific chroms eg. scaffold_34 to chrom 29 or is hap dup and should be removed eg. scaffold_35 and scaffold_38 etc..

**Comment by tbrown91** [comment]
Hi @CaroB-M 

Have you had a chance to look at the suggested changes from @tommathers and recreate the EAR? It would be great to have another assembly finished

**Comment by CaroB-M** [comment]
Hello, I'm back from vacation. I'm now generating the files, having taken into account the changes suggested by @tommathers.  I'll upload the files as soon as possible.

**Comment by CaroB-M** [comment]
Hello, I added the new EAR report.  I made the changes suggested by @tommathers. For the little contigs, I placed just some of them in larger scaffolds.

**Comment by tbrown91** [comment]
Hi @CaroB-M 

Welcome back and thank you for re-uploading the EAR. @tommathers can I ask you to give the map one last look-through? Hopefully we can finish this assembly off soon and publish it to ENA

**Comment by tbrown91** [comment]
@tommathers ping

**Comment by tbrown91** [comment]
Hi @CaroB-M 

I looked through the map and can see two potential mis-scaffolds:

xgDerLasi_30:14.37Mb-14.54Mb this should be placed at 21.21Mb - same orientation
xgDerLasi_18:21.81Mb-21.91Mb this should be placed at the end ~36Mb - reverse orientation

In your TAPAS plot there are two bacterial sequences. Have you already removed these, or do you have evidence that they are false positives?

If you make these changes and remove the contaminants I think it is ready to upload.

Any further thoughts, @tommathers ?

**Comment by tommathers** [comment]
Hi. Sorry for the delay. Just had a look through. I agree with Tom's suggestions re chrom 18 and 30. Also, the haplotig in chrom 1 at 48.7 i flagged before needs removing and I just noticed there is another small one i missed before at 48.1 Mb.

**Comment by tbrown91** [comment]
Thanks @CaroB-M 

Hopefully just one more quick look-through please @tommathers

**Comment by CaroB-M** [comment]
Hello, I added the new EAR report. I made the changes suggested. The bacterial contigs were already removed. Thanks!

**Comment by tommathers** [comment]
Hi just wanted to check if the corrext ear has been uploaded? I can still see the haplotigs on chr. 1 that were flagged above when I downloaded the map from the latest report. See attached pic of region of chr. 1 at ~48 Mb.
image

**Comment by CaroB-M** [comment]
Hello @tommathers. You're rigth. There was a mistake. I have changed the pretext map link so can you try to download the pdf file and the pretext map? Sorry for the inconvenience

**Review by tommathers — APPROVED** [review]
Looks good.

**Comment by tbrown91** [comment]
Thanks @tommathers 

Congrats @CaroB-M please go forward with the upload to ENA

**Pull request merged**
