### PR TITLE
Add icTarCana1

### PR DESCRIPTION
**Pull request by tommathers**
## Assembly review request

- ToLID: icTarCana1
- Species: Tarphius canariensis
- Project: ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by tbrown91** [comment]
ok

**Comment by diegomics** [comment]
Hi @auryjm and @CaroB-M sorry for the excess of pings, we detected a bot anomaly that we are fixing.

@auryjm do you agree to review this EAR? Please reply to this message only with Yes or No by 30-Sep-2024 at 16:49 CET

@CaroB-M you should not have been called at this point. So please pretend you have not been contacted (yet!)

**Comment by auryjm** [comment]
Thank you, @tommathers and @JoannaCollins for this genome assembly of the coleoptera. The long-read assembly looks good, with a low number of contigs per chromosome and the X chromosome assembled in a single contig!

Here are a few things I noticed, although some may be explained by the fact that the Hi-C was performed on a different individual.

SUPER_1 @ 43.29-43.34: allelic duplication
SUPER_1 @ 45.19-45.23: very few contacts with SUPER_1; move to the end of SUPER_7? Also, very low coverage, which could indicate a falsely duplicated region.
SUPER_2 @ 20.59-20.63: allelic duplication
SUPER_2 @ 37.30-37.37: unlocalized (possibly because Hi-C was performed on another individual?)
SUPER_3 @ 3.40-3.47: allelic duplication
SUPER_3 @ 15.44-15.49: allelic duplication
SUPER_4 @ 2.70-2.84: allelic duplication
SUPER_4 @ 19.11-19.15: allelic duplication
SUPER_4 @ 33.15-33.21: very few contacts with SUPER_4; move to the end of SUPER_7? Also, very low coverage, which could indicate a falsely duplicated region.
SUPER_5: small region at the start has more contact with the end of SUPER_4 (possibly because Hi-C was performed on another individual?)
SUPER_5 @ 15.82-15.85: allelic duplication
SUPER_7 @ 17.50-17.58: allelic duplication
SUPER_8: small region at the start has more contact with the end of SUPER_7 (possibly because Hi-C was performed on another individual?)
SUPER_8 @ 4.06-4.17: allelic duplication
SUPER_8: small region at the end has more contact with the end of SUPER_7 (possibly because Hi-C was performed on another individual?)
SUPER_9 @ 10.94-10.97: allelic duplication
SUPER_9 @ 20.94-20.99: allelic duplication
SUPER_X: small region at the start has more contact with the end of SUPER_9 (possibly because Hi-C was performed on another individual?)

**Comment by tbrown91** [comment]
Thank you for the review @auryjm 

@tommathers @JoannaCollins could I ask you to please look through the list of suggestions and make any changes you see fit?

**Comment by JoannaCollins** [comment]
Hi @auryjm 

Thank you very much for reviewing the assembly of icTarCana1 :slightly_smiling_face: .

I have investigated all of the issues that you raised and have added my comments on each point below:  

SUPER_1 @ 43.29-43.34: allelic duplication - **contigous - data supports current assembly.**
SUPER_1 @ 45.19-45.23: very few contacts with SUPER_1; move to the end of SUPER_7? Also, very low coverage, which could indicate a falsely duplicated region. - **contigous region/not gapped, coupled with Hi-C from a different individual which makes moving the sequence a potentially ambiguous placement so I think its not appropriate to make the change. Low cov likely due to sequence being repetitive.** 
SUPER_2 @ 20.59-20.63: allelic duplication - **contigous - data supports current assembly.**
SUPER_2 @ 37.30-37.37: unlocalized (possibly because Hi-C was performed on another individual?) - **contigous, and has ambiguous hits elsewhere - not appropriate to make change.**
SUPER_3 @ 3.40-3.47: allelic duplication - **There is a gap here but the data supports current assembly.**
SUPER_3 @ 15.44-15.49: allelic duplication - **contigous - data supports current assembly.**
SUPER_4 @ 2.70-2.84: allelic duplication - **contigous - data supports current assembly.**
SUPER_4 @ 19.11-19.15: allelic duplication - **contigous - data supports current assembly.**
SUPER_4 @ 33.15-33.21: very few contacts with SUPER_4; move to the end of SUPER_7? Also, very low coverage, which could indicate a falsely duplicated region.-**contigous, and has ambiguous hits elsewhere - not appropriate to make change. Low cov likely due to sequence being repetitive.** 
SUPER_5: small region at the start has more contact with the end of SUPER_4 (possibly because Hi-C was performed on another individual?) - **contigous, and has ambiguous hits elsewhere - not appropriate to make change.**
SUPER_5 @ 15.82-15.85: allelic duplication - **contigous - data supports current assembly.**
SUPER_7 @ 17.50-17.58: allelic duplication- **There is a gap here, but data supports current assembly.**
SUPER_8: small region at the start has more contact with the end of SUPER_7 (possibly because Hi-C was performed on another individual?) - **contigous, and has ambiguous hits elsewhere - not appropriate to make change.**
SUPER_8 @ 4.06-4.17: allelic duplication - **There is a gap in this region, but data supports current assembly.**
SUPER_8: small region at the end has more contact with the end of SUPER_7 (possibly because Hi-C was performed on another individual?) - **contigous, and has ambiguous hits elsewhere - not appropriate to make change.**
SUPER_9 @ 10.94-10.97: allelic duplication - **contigous - data supports current assembly.**
SUPER_9 @ 20.94-20.99: allelic duplication- **contigous - data supports current assembly.**
SUPER_X: small region at the start has more contact with the end of SUPER_9 (possibly because Hi-C was performed on another individual?) - **contigous, and has ambiguous hits elsewhere - not appropriate to make change.**


As you noted the assembly was of very high quality prior to curation, and I was able to utilise the merged hap1/hap2 map for curation which showed very nicely that the automated assembly process had produced an essentially complete assembly for each haplotype.

With regard to the regions where Hi-C suggests a different placement, these regions are all contiguous, thus I agree with your comments that this is most likely as a result of the underlying data and Hi-C being derived from different individuals. The sequence in question also seems to have ambiguous hits across the map, so taking all of the above into account I think it is appropriate to leave these regions as they were originally assembled. 


Thanks again, Best wishes, Jo

**Comment by JoannaCollins** [comment]
Hi @auryjm,

Thanks for taking another look at this. 

In terms of verfiying the current assembly I looked at each of the regions that you noted in the HiGlass map of the data set. As HiGlass provides a much more detailed view of the underlying data than pretext it allows for easier identification of genuine haplotypic duplications. Typically the hap dups we see are at contig gaps (although not always) are accompanied by a drop in coverage of the PacBio data to approximately half and have a typical motif as seen in the following image (not from this assembly).

image


So for instance in the case of the issue you noted @ SUPER_3 @ 15.44-15.49: allelic duplication, you can see from the picture below that with the high resolution map there is no obvious error.  So my point "contiguous - data supports current assembly" is really just saying at this point in the assembly, there are no gaps in the underlying data and there is no evidence from HIC mapping in the high resolution map that there is an assembly error at this location. 

image

 
Best Wishes

Jo

**Comment by tbrown91** [comment]
Thank you @JoannaCollins and @auryjm 

In case it's helpful, this is the pipeline I use to generate the .mcool files for visualising the maps in HiGlass. I really struggle with the pretext maps, so also tend to end up using these to make most of my decisions: https://workflowhub.eu/workflows/795

If you are happy with the genome as it is, could you please "Approve" the pull-request Jean-Marc and then we can send another happy genome off to ENA.

Thank you both again for the work and input

**Comment by tbrown91** [comment]
Morning both,

Sorry to pester again. @auryjm Have I interpreted correctly that you are happy with the assembly? We would like to merge this (and open you up as a reviewer again ;))

@JoannaCollins I think this can be submitted, in case you are waiting for the go-ahead

**Review by auryjm — APPROVED** [review]

**Pull request merged**
