### PR TITLE
rMalMon1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
Assembly review request
---

ToLID: rMalMon1

Species: Malpolon monspessulanus

Project: ERGA-BGE

Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @fcamara7 
Thanks for sending the EAR of Malpolon monspessulanus
I added the corresponding tag to the PR and appointed @tbrown91 as assignee to supervise.
I will contact a reviewer ASAP.

```
*****
EAR Reviewer Selection Process
Date: 2024-04-29 15:59

All Eligible Candidates:

Github ID     | Full Name   | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
------------------------------------------------------------------------------------------------------------------------
additive3     | Jo Wood     | Sanger      | 1             | 2024-02-26  | Y      | N    | 999           | 1049          
SarahPelan    | Sarah Pelan | Sanger      | 1             | 2024-03-22  | Y      | N    | 999           | 1049          
joannacollins | Jo Collins  | Sanger      | 1             | 2024-03-27  | Y      | N    | 999           | 1049          
DomAbsolon    | Dom Absolon | Sanger      | 1             | 2024-04-22  | Y      | N    | 999           | 1049          
tommathers    | Tom Mathers | Sanger      | 1             | 2024-04-26  | Y      | N    | 999           | 1049          
tbrown91      | Tom Brown   | IZW         | 8             | 2024-02-21  | Y      | N    | 993           | 993           

Selected reviewer to call first: Jo Wood (additive3)
The decision was based on:
- different institution ('Sanger')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1049)
- chosen based on oldest review and fewest reviews among the finalists
```

**Comment by tommathers** [comment]
HI – I can review this one if needed. Already took a quick look at it…

Dr. Thomas Mathers
Senior Computer Biologist
Genome Reference Informatics Team
Tree of Life
Wellcome Sanger Institute
Hinxton
Cambridge
CB10 1SA

Twitter: @Thomas_Mathers [twitter.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_Thomas-5FMathers-3Flang-3Den-2Dgb&d=DwMGaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tJRHixSYq-VP6FIxTiP35xdkMZl3FaXQVx1qay3XZ-7I4UkhUxDC7h1P98bVhcBb&s=hffLCC65eIfPsnmm3hnO-CV4DYCZYG2ebSippldU3zw&e=>
Publications: Google Scholar [scholar.google.co.uk]<https://urldefense.proofpoint.com/v2/url?u=https-3A__scholar.google.co.uk_citations-3Fhl-3Den-26user-3D5XjBm94AAAAJ-26view-5Fop-3Dlist-5Fworks-26sortby-3Dpubdate&d=DwMFAg&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=KIKynKbLKfS4YVQYVctJHL39ls39CbRogxK7G0OumbwWdwS4Qdlkrg9NnRJHPJGs&s=T2pa4qY1i623xxULQ3x4gTTj4JvNcKbwYHoNm5knTFc&e=>


From: Diego De Panis ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Monday, 29 April 2024 at 15:00
To: ERGA-consortium/EARs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ERGA-consortium/EARs] rMalMon1 EAR (PR #37) [EXT]


Hi @fcamara7 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_fcamara7&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=kCRyd1jTmXuh7AYOukssECAGxS41h4Z-_vt0hBODfduSYAi-5i1pCTLkUKvt4XII&s=BlsrCwGzBIDasvJdR1yFk3dRZfR4KLBVra3X2muzyk4&e=>
Thanks for sending the EAR of Malpolon monspessulanus
I added the corresponding tag to the PR and appointed @tbrown91 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tbrown91&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=kCRyd1jTmXuh7AYOukssECAGxS41h4Z-_vt0hBODfduSYAi-5i1pCTLkUKvt4XII&s=8Duo6oyFrtEatuvXujqubxoXHoD-YqxKLQerJ3KuiVQ&e=> as assignee to supervise.
I will contact a reviewer ASAP.

*****

EAR Reviewer Selection Process

Date: 2024-04-29 15:59



All Eligible Candidates:



Github ID     | Full Name   | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score

------------------------------------------------------------------------------------------------------------------------

additive3     | Jo Wood     | Sanger      | 1             | 2024-02-26  | Y      | N    | 999           | 1049

SarahPelan    | Sarah Pelan | Sanger      | 1             | 2024-03-22  | Y      | N    | 999           | 1049

joannacollins | Jo Collins  | Sanger      | 1             | 2024-03-27  | Y      | N    | 999           | 1049

DomAbsolon    | Dom Absolon | Sanger      | 1             | 2024-04-22  | Y      | N    | 999           | 1049

tommathers    | Tom Mathers | Sanger      | 1             | 2024-04-26  | Y      | N    | 999           | 1049

tbrown91      | Tom Brown   | IZW         | 8             | 2024-02-21  | Y      | N    | 993           | 993



Selected reviewer to call first: Jo Wood (additive3)

The decision was based on:

- different institution ('Sanger')

- active ('Y')

- not busy ('N')

- highest adjusted calling score in this particular selection (1049)

- chosen based on oldest review and fewest reviews among the finalists

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_37-23issuecomment-2D2082836534&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=kCRyd1jTmXuh7AYOukssECAGxS41h4Z-_vt0hBODfduSYAi-5i1pCTLkUKvt4XII&s=9yw1nbKJmtJRDNcu2oiL0TJCIEfUyiWlXe_DOwICGqo&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3G5CPKEVG4V7QKSBNCDY7ZG7FAVCNFSM6AAAAABG6KTGHKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBSHAZTMNJTGQ&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=kCRyd1jTmXuh7AYOukssECAGxS41h4Z-_vt0hBODfduSYAi-5i1pCTLkUKvt4XII&s=1LR6Ttm62PkDvJ_PT4IgJ7z7HWLTSZanteHpcSkANcQ&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by tbrown91** [comment]
Hi @fcamara7 can you please edit the pull request so that it only contains one file. It looks like you need to merge with the ERGA-consortium branch first before submitting your pull request. Please close the request and make a new one with just the rMalMon EAR

**Comment by tbrown91** [comment]
Sorry, looking again, you need to delete the mApoAgr2 folder from your EAR directory

**Pull request closed without merging**
