### PR TITLE
Initial submission of xAbcDef1

### PR DESCRIPTION
**Pull request by luisamarins**
Full species name: _Abc def_
Taxon: something
Sequencing technology: HiC, HiFi 
Contact: email@email.com

### CODE REVIEW

**Review by tbrown91 — COMMENTED** [review]
Need to purge again

**Review by diegomics — CHANGES_REQUESTED** [review]
Please provide a KAT plot

**Review by tbrown91 — APPROVED** [review]
this look good to me now

**Comment by luisamarins** [comment]
Please check the changes you requested

**Pull request merged**
