### PR TITLE
ilGraIsab1 EAR

### PR DESCRIPTION
**Pull request by gitcruz**
Assembly review request
---

- ToLID: ilGraIsab1 
- Species: Graellsia isabellae
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by gitcruz** [comment]
Hi @diegomics,

Thanks for developing this tool. 

Regarding the automatic flags associated to the ilGraIsab1.1_EAR: 

- Haploid number: there is a direct estimate of the haploid number in GoaT under "chromosome_number" that says 31. GoaT is not consistent, it should say 61 twice the autosomes plus the sex chromosome (Z0 system) and instead of the ancestor estimate indicate haploid_number (direct): 31. 
- Ploidy: In GoaT is 2 as this is a diploid organism

Could you double check the procedure to avoid unnecessary warnings or contact GoaT to clarify this particular case?

Best regards,
Fernando

**Comment by diegomics** [comment]
Hi @gitcruz, thanks for sending the EAR of _Graellsia isabellae_.
I added the corresponding tag to the PR and appointed @tbrown91 as the [assignee](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section).
I will contact a reviewer ASAP.
:ear:

**Comment by tbrown91** [comment]
Hi @gitcruz,

I am unable to download your pretext map without logging into a windows account. Is it possible to either make the link publicly sharable or update to an open link?

Thanks,

Tom

**Comment by tbrown91** [comment]
For example, we could make a public download link in the new CNAG-BGE Nextcloud folder from BSC

**Comment by gitcruz** [comment]
Hi Tom.

I sent you an email to gmail with a new link. If it works I will  regenerate the PDF and upload it...Can I replace the file or should  I do a new commit?

Best regards,
Fernando

**Comment by tbrown91** [comment]
for me the new link is perfect

**Comment by gitcruz** [comment]
Great! should I create a new commit or can I replace the PDF?

**Comment by diegomics** [comment]
Please replace the PDF in your branch, it will automatically update the PR

**Comment by gitcruz** [comment]
Hi guys,

It's done. It should work for everyone now.

Thanks

**Comment by diegomics** [comment]
Hi @SarahPelan, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 29-MAR-2024 at 13:44 CET.

**Comment by SarahPelan** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Review by SarahPelan — APPROVED** [review]
I've checked this and all looks good to me
Thanks,
Sarah

**Comment by tbrown91** [comment]
Thank you @SarahPelan that's great!

@gitcruz good luck with the submission and great to see another high-quality genome on its way!

**Review by tbrown91 — APPROVED** [review]

**Comment by gitcruz** [comment]
Thanks for reviewing this @SarahPelan!  Tom we will submit this assembly and its mitogenome to ENA asap...

**Pull request merged**
