### PR TITLE
fAlbAlb1 ear

### PR DESCRIPTION
**Pull request by tbrown91**
## Assembly review request

- ToLID: fAlbAlb1
- Species: Alburnus alburnus
- Project: ERGA-Pilot
- Affiliation: MPI-CBG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @tbrown91, thanks for sending the EAR of _Alburnus alburnus_.
I added the corresponding tag to the PR and appointed myself as the assignee to supervise.
I will contact a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @bistace, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 10-JUN-2024 at 15:15 CET.

**Comment by bistace** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Review by bistace — APPROVED** [review]
Hi @tbrown91, everything looks good to me!

**Comment by diegomics** [comment]
Thanks @bistace 
@tbrown91 I took a quick look at the pretext files and found some spots that raised doubts in me. Maybe you can comment on those. @bistace, do you agree? I didn't double-check the mcool, so maybe I'm being overly cautious

```
hap1_s4 2,041 Kbp
hap1_s4 4,150 Kbp
hap1_s4 8,770 Kbp
hap1_s6 35,700 Kbp
hap1_s6 41,500 Kbp --to flip?
hap1_s8 2,285 Kbp
hap1_s10 36,500 Kbp
hap1_s20 30,950 Kbp
```

```
hap2_s5 38,500 Kbp
hap2_s13 2,270 Kbp --telomeric signal out of the terminal region
hap2_s15 1,100 Kbp
hap2_s21 13,500 Kbp --telomeric signal out of the terminal region
hap2_s25 19,200 Kbp
```

Is it only one hap to be curated?

**Review by bistace — COMMENTED** [review]
Hi @diegomics, I saw the regions you pointed out but as I did not find any good places to put these pieces and doing the changes often made the map look worse I did not include it in my review. You probably have a lot more experience on this than I do so if you feel like it is problematic I will follow your call. @tbrown91 could you please comment on these?

**Comment by additive3** [comment]
Hi @tbrown91 @bistace 

I haven't managed to get time to review the haplotype assmeblies for fAlbAbl1 yet.
Initial thing to fix in both haps are scaffold_21.
hap1 start-13.4Mb flip
hap2 start-13.49Mb flip

There are a couple of other things to correct, I'll get a list asap.

Best,
Jo

**Comment by tbrown91** [comment]
Hi @additive3 

Thank you for agreeing to look at this. I also have a been a bit pre-occupied with the fAnaHis assembly and helping others, so haven't looked at this one much. I will hopefully have some time this afternoon to have a proper look and make some changes

**Comment by tbrown91** [comment]
Hello,

Here are my changes for hap1:

```
hap1_manual_scaffold_1  1       59056062        1       W       hap1_manual_scaffold_1  1       59056062        +
hap1_manual_scaffold_2  1       40222322        1       W       hap1_manual_scaffold_2  1       40222322        +
hap1_manual_scaffold_2  40222323        40222422        2       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_2  40222423        40373016        3       W       hap1_manual_scaffold_6  35648732        35799325        -
hap1_manual_scaffold_2  40373017        40373116        4       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_2  40373117        57895807        5       W       hap1_manual_scaffold_2  40222563        57745253        +
hap1_manual_scaffold_3  1       52482068        1       W       hap1_manual_scaffold_3  1       52482068        +
hap1_manual_scaffold_4  1       52130229        1       W       hap1_manual_scaffold_4  1       52130229        +
hap1_manual_scaffold_5  1       47861043        1       W       hap1_manual_scaffold_5  1       47861043        +
hap1_manual_scaffold_6  1       35648732        1       W       hap1_manual_scaffold_6  1       35648732        +
hap1_manual_scaffold_6  35648733        35648832        2       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_6  35648833        41400295        3       W       hap1_manual_scaffold_6  35799566        41551028        +
hap1_manual_scaffold_6  41400296        41400395        4       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_6  41400396        42307200        5       W       hap1_manual_scaffold_6  41551269        42458073        -
hap1_manual_scaffold_6  42307201        42307300        6       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_6  42307301        43987635        7       W       hap1_manual_scaffold_6  42458574        44138908        +
hap1_manual_scaffold_7  1       17770803        1       W       hap1_manual_scaffold_7  1       17770803        +
hap1_manual_scaffold_7  17770804        17770903        2       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_7  17770904        42968010        3       W       hap1_manual_scaffold_7  18108701        43305807        +
hap1_manual_scaffold_8  1       40710992        1       W       hap1_manual_scaffold_8  1       40710992        +
hap1_manual_scaffold_9  1       39127023        1       W       hap1_manual_scaffold_9  1       39127023        +
hap1_manual_scaffold_10 1       38828630        1       W       hap1_manual_scaffold_10 1       38828630        +
hap1_manual_scaffold_11 1       38752591        1       W       hap1_manual_scaffold_11 1       38752591        +
hap1_manual_scaffold_12 1       38593639        1       W       hap1_manual_scaffold_12 1       38593639        +
hap1_manual_scaffold_13 1       37913015        1       W       hap1_manual_scaffold_13 1       37913015        +
hap1_manual_scaffold_14 1       37831164        1       W       hap1_manual_scaffold_14 1       37831164        +
hap1_manual_scaffold_15 1       37225888        1       W       hap1_manual_scaffold_15 1       37225888        +
hap1_manual_scaffold_16 1       36776458        1       W       hap1_manual_scaffold_16 1       36776458        +
hap1_manual_scaffold_17 1       36442654        1       W       hap1_manual_scaffold_17 1       36442654        +
hap1_manual_scaffold_18 1       36260489        1       W       hap1_manual_scaffold_18 1       36260489        +
hap1_manual_scaffold_19 1       35515853        1       W       hap1_manual_scaffold_19 1       35515853        +
hap1_manual_scaffold_20 1       33184425        1       W       hap1_manual_scaffold_20 1       33184425        +
hap1_manual_scaffold_21 1       13445619        1       W       hap1_manual_scaffold_21 1       13445619        -
hap1_manual_scaffold_21 13445620        13445719        2       U       100     scaffold        yes     proximity_ligation
hap1_manual_scaffold_21 13445720        32927044        3       W       hap1_manual_scaffold_21 13446120        32927444        +
hap1_manual_scaffold_22 1       30812925        1       W       hap1_manual_scaffold_22 1       30812925        +
hap1_manual_scaffold_23 1       30067891        1       W       hap1_manual_scaffold_23 1       30067891        +
hap1_manual_scaffold_24 1       29074022        1       W       hap1_manual_scaffold_24 1       29074022        +
hap1_manual_scaffold_25 1       28830976        1       W       hap1_manual_scaffold_25 1       28830976        +
hapdup_1        1       337657  1       W       hap1_manual_scaffold_7  17771044        18108700        +
```

I will hopefully have a look at hap2 tomorrow. @bistace let me know if you are happy and have had a chance to have a closer look through the assemblies. I have added a new pretext file and save state for hap1 to the same download folder

**Comment by tbrown91** [comment]
Here is my agp for hap2:

```hap2_manual_scaffold_1  1       53505432        1       W       hap2_manual_scaffold_1  1       53505432        +
hap2_manual_scaffold_2  1       53853169        1       W       hap2_manual_scaffold_2  1       53853169        +
hap2_manual_scaffold_3  1       53172001        1       W       hap2_manual_scaffold_3  1       53172001        +
hap2_manual_scaffold_4  1       58854854        1       W       hap2_manual_scaffold_4  1       58854854        +
hap2_manual_scaffold_5  1       46411488        1       W       hap2_manual_scaffold_5  1       46411488        +
hap2_manual_scaffold_6  1       40880504        1       W       hap2_manual_scaffold_6  1       40880504        +
hap2_manual_scaffold_7  1       44312380        1       W       hap2_manual_scaffold_7  1       44312380        +
hap2_manual_scaffold_8  1       40190326        1       W       hap2_manual_scaffold_8  1       40190326        +
hap2_manual_scaffold_9  1       32076929        1       W       hap2_manual_scaffold_9  1       32076929        +
hap2_manual_scaffold_10 1       38024220        1       W       hap2_manual_scaffold_10 1       38024220        +
hap2_manual_scaffold_11 1       40844461        1       W       hap2_manual_scaffold_11 1       40844461        +
hap2_manual_scaffold_12 1       37360060        1       W       hap2_manual_scaffold_12 1       37360060        +
hap2_manual_scaffold_13 1       2286014 1       W       hap2_manual_scaffold_13 1       2286014 -
hap2_manual_scaffold_13 2286015 2286114 2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_13 2286115 33958356        3       W       hap2_manual_scaffold_13 2286115 33958356        +
hap2_manual_scaffold_14 1       39455939        1       W       hap2_manual_scaffold_14 1       39455939        +
hap2_manual_scaffold_15 1       33773007        1       W       hap2_manual_scaffold_15 1       33773007        +
hap2_manual_scaffold_16 1       36976204        1       W       hap2_manual_scaffold_16 1       36976204        +
hap2_manual_scaffold_17 1       36312288        1       W       hap2_manual_scaffold_17 1       36312288        +
hap2_manual_scaffold_18 1       35076004        1       W       hap2_manual_scaffold_18 1       35076004        +
hap2_manual_scaffold_19 1       34323713        1       W       hap2_manual_scaffold_19 1       34323713        +
hap2_manual_scaffold_20 1       33206301        1       W       hap2_manual_scaffold_20 1       33206301        +
hap2_manual_scaffold_21 1       13469405        1       W       hap2_manual_scaffold_21 1       13469405        -
hap2_manual_scaffold_21 13469406        13469505        2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_21 13469506        28789149        3       W       hap2_manual_scaffold_21 13469506        28789149        +
hap2_manual_scaffold_22 1       30633991        1       W       hap2_manual_scaffold_22 1       30633991        +
hap2_manual_scaffold_23 1       32475719        1       W       hap2_manual_scaffold_23 1       32475719        +
hap2_manual_scaffold_24 1       36045655        1       W       hap2_manual_scaffold_24 1       36045655        +
hap2_manual_scaffold_25 1       30754614        1       W       hap2_manual_scaffold_25 1       30754614        +```

I have also uploaded a new pretext and savestate to the download folder. @bistace @diegomics please let me know if you're happy with the assembly now. It would be nice to get everything to ENA

**Comment by bistace** [comment]
Hi @tbrown91, thank you for doing the changes to the assembly. It seems that the pretext map for the second haplotype with gaps and reads coverage is not present in the download folder, could you please add it?

**Comment by bistace** [comment]
Thank you for adding the pretext map! I have taken a look at both of them and think it looks good, I just have two interrogations:
 - Hap 1: this one looks like a duplication with less contacts and halved coverage. The pattern is not completely blank so I will let you decide if something needs to be done
```
       hap1_manual_scaffold_8[34.82 Mbp] to hap1_manual_scaffold_8[34.38 Mbp]
```
  - Hap 2: I think that this part could be moved because it is pretty clear where it should go
```
       hap2_manual_scaffold_2[42.51 Mbp] to hap2_manual_scaffold_2[42.65 Mbp]
       moved to
       hap2_manual_scaffold_2[39.06 Mbp]
```

**Comment by diegomics** [comment]
Hap1 is good to go for me. I'm looking closely at hap2 in Higlass, give me some minutes

**Comment by diegomics** [comment]
It's a small one, but it does looks like can be placed on hap2_scaf2 ~38.41. Do you have small gaps that support the missassembly? If you don't, I'm ok with it, I'm not a fan of open new gaps.
Other than that, I can see telo signal at ~2.2 in scaf13. Is it not fixable?
Laborious task the one you carried out Tom... unearth this old salsa-scaffolded genome to push it to completion 🙌🙌

**Comment by tbrown91** [comment]
@diegomics I forgot to save the switch in hap13, but it is in the agp I used to generate the new assembly s.o.

That region in scaff_2 is a single contig. I think these repeats are just biology

**Comment by tbrown91** [comment]
I updated the save state

**Review by bistace — APPROVED** [review]
Good to go!

**Review by diegomics — APPROVED** [review]

**Comment by diegomics** [comment]
Thanks @bistace for the review.
I will add a new reviewed species for you to the table ;)
Also, thanks @additive3 for all your input, it was really helpful 🙌

Congrats on the assembly @tbrown91!
After the merging, you can [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission)

**Pull request merged**
