### PR TITLE
ibLobSubt1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
## Assembly review request

- ToLID: ibLobSubt1
- Species: Loboptera subterranea
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by diegomics** [comment]
@fcamara7 please use the correct default body for the PR, I will edit it now. Write me if this is not clear.

**Comment by fcamara7** [comment]
> @fcamara7 please use the correct default body for the PR, I will edit it now. Write me if this is not clear.

Not sure what you mean @diegomics Can you clarify? F

**Comment by epaule** [comment]
Yes

But I am currently doing a workshop until the end of the week, so it might not happen in the next few days.

**Comment by diegomics** [comment]
> > @fcamara7 please use the correct default body for the PR, I will edit it now. Write me if this is not clear.
> 
> Not sure what you mean @diegomics Can you clarify? F

This is the default body of the EAR pull-request (you only need to complete those empty fields):
Screenshot 2024-10-07 at 14 11 46

...it is markdown, so, empty, it will show like this:
Screenshot 2024-10-07 at 14 12 48

Now, this is the body of the PR that you sent:
Screenshot 2024-10-07 at 14 09 27

The part indicated in red is what I removed ;)

**Comment by fcamara7** [comment]
> > > @fcamara7 please use the correct default body for the PR, I will edit it now. Write me if this is not clear.
> > 
> > 
> > Not sure what you mean @diegomics Can you clarify? F
> 
> This is the default body of the EAR pull-request (you only need to complete those empty fields): Screenshot 2024-10-07 at 14 11 46
> 
> ...it is markdown, so, empty, it will show like this: Screenshot 2024-10-07 at 14 12 48
> 
> Now, this is the body of the PR that you sent: Screenshot 2024-10-07 at 14 09 27
> 
> The part indicated in red is what I removed ;)

I see! I will make sure this does not happen. Somehow it is being added automatically to the final pull request.

**Comment by epaule** [comment]
it looks very nice. The only thing i could find was the end of SUPER_8, which potentially might need flipping from 175.4 kbp to the end.

If you assume that the gaps are very likely the insertion points, I think it would be possible to also place some of the unlocs, but as the HiC is from a different sample, it is a bit vague and maybe leaving them as unloc to the chromsome is more conservative and safer, so I will leave that up to you.

And I would usually only remove contamination internal to a chromosome, if there are no reads spanning the host-contaminant join. Ideally I would want a gap there, especially as I believe there were a few HGTs described in other Blattodea.

**Comment by fcamara7** [comment]
> Based on the data, I will go for the conservative approach. @fcamara7 let us know what's the consensus the curators reach at CNAG so @epaule can approve and we can merge this one asap ;)

Thanks for the review @diegomics & @epaule I will be taking a look with @talioto and we will get back to you asap.

**Comment by fcamara7** [comment]
@epaule @diegomics After reviewing it with @talioto we have made the change at the end of SUPER_8 as suggested. With regard to the unlocs and given the limitations pointed out we will take the conservative approach and leave things as are. The shared directory with the pretext file (ibLobSubt1_mq40_nosort.extensions.pretext)  and a save state is linked below. Given that the changes are minimal and are not going change the blobtools or hic mapping to any extent we also suggest simply resubmitting the EAR report with the new pretext, some extra comments and no further changes regarding blobtools or remapping of HiC. Let us know if you agree. 

(https://ccnag-my.sharepoint.com/:f:/g/personal/francisco_camara_cnag_eu/EmNsyQCOTpFHuEx6MCPOmmEBF_6IU0eW_19oETdxur5-cw?e=XNVjzb)

**Comment by fcamara7** [comment]
> I agree. Do you think gfastats and/or busco can be updated too in addition to the new comments? It would be nice to merge this one for good :) Please, take a look at the savestate and approve the PR if all is good from your side @epaule

Of course, I will regenerate with new gfastas. Busco and merqury as well even though that would take an extra day (busco). In any case if you both agree we can go ahead with the ENA upload in the mean time.

**Comment by epaule** [comment]
just had a look at the savestate, and it looks good. So I think it should be good for ENA uploading.

**Review by epaule — APPROVED** [review]
just had a look at the savestate, and it looks good. So I think it should be good for ENA uploading.

**Comment by diegomics** [comment]
Thanks @epaule! @fcamara7 you are good to go to upload this one to ENA, please regenerate the pdf so I can merged the PR and release the reviewer. Run only a new gfastats and busco. The assembly was in a really good shape, you will not find any differences in the QV from the SUPER_8 terminal flipping. That way we can merge this tomorrow ;)

**Comment by fcamara7** [comment]
@diegomics let me know if it is fine now and sorry for the mistake.

**Comment by diegomics** [comment]
All good. Nothing else to do here, congrats again!

**Pull request merged**
