### PR TITLE
fAnaHis1 ear

### PR DESCRIPTION
**Pull request by tbrown91**
## Assembly review request

- ToLID: fAnaHis1
- Species: Anaecypris hispanica
- Project: ERGA-Pilot
- Affiliation: MPI-CBG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @tbrown91, thanks for sending the EAR of _Anaecypris hispanica_.
I added the corresponding tag to the PR and appointed myself as the assignee to supervise.
I will contact a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @CaroB-M, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 10-JUN-2024 at 15:17 CET.

**Comment by CaroB-M** [comment]
yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Comment by CaroB-M** [comment]
Hi @diegomics I think scaffolds 20 and 21 need several changes but  I'm having trouble making the right decisions. Is it possible to add the coverage track to the maps? Thanks

**Comment by diegomics** [comment]
Thanks @CaroB-M I agree.
@tbrown91 I took a quick look at the pretext files and found some spots that raised doubts in me. Maybe you can comment on those. What do you think @CaroB-M ? I didn't double-check the mcool, so maybe I'm being overly cautious...

```
hap1_s2 465 kbp --telomeric signal slightly out of the terminal region
hap1_s2 39,250 kbp
hap1_s3 1,750 kbp --flip?
hap1_s6 12,100 kbp
hap1_s6 20,500 kbp
hap1_s8 25,000 kbp
hap1_s9 3,100 kbp
hap1_s10 4,900 kbp
hap1_s20 1,350 kbp --flip?
hap1_s22 11,800 kbp --flip?

```
```
hap2_s2 500 kbp --telomeric signal slightly out of the terminal region
hap2_s2 39,200 kbp
hap2_s7 29,250 kbp
hap2_s8 23,150 kbp --maybe this is just ok
hap2_s8 36,200 kbp
hap2_s13 30,000 kbp
hap2_s14 12,150 kbp
hap2_s20 1,200 kbp --flip?
```

Is it only one hap to be curated?

**Comment by tbrown91** [comment]
Hi @CaroB-M, thank you for looking at the assembly. I have uploaded pretext files including the coverage tracks to the same download folder

**Comment by CaroB-M** [comment]
I think we can try to place the last little scaffolds in the scaffold 21

**Comment by tbrown91** [comment]
thanks @CaroB-M I'll get back to you once I've made some edits - hopefully this afternoon, but to recreate the whole EAR will take a long time due to the blobplot

**Comment by tbrown91** [comment]
HI @CaroB-M I'm not sure what to make of some of these, could you please have a look at what I have commented on?

Edit 1: **- done**
hap1_manual_scaffold_2[495.35 kbp] to hap1_manual_scaffold_2[300.21 kbp]
inverted and moved to
hap1_manual_scaffold_1[57.87 Mbp]
Edit 2: **- this was actually an inversion, easier to see in higlass**
hap1_manual_scaffold_2[39.25 Mbp] to hap1_manual_scaffold_2[39.37 Mbp]
moved to
hap1_manual_scaffold_2[39.24 Mbp]
**Are these all typos? They don't seem to be actually changing anything, unless you really want to shift them all 20kb upstream.**
Edit 3:**-as above**
hap1_manual_scaffold_3[31.84 Mbp] to hap1_manual_scaffold_3[31.84 Mbp]
moved to
hap1_manual_scaffold_3[31.82 Mbp]
Edit 4:**-as above**
hap1_manual_scaffold_4[28.21 Mbp] to hap1_manual_scaffold_4[28.30 Mbp]
moved to
hap1_manual_scaffold_4[28.19 Mbp]
Edit 5:**-as above**
hap1_manual_scaffold_4[27.81 Mbp] to hap1_manual_scaffold_4[27.92 Mbp]
moved to
hap1_manual_scaffold_4[27.80 Mbp]
Edit 6:**-as above**
hap1_manual_scaffold_4[27.63 Mbp] to hap1_manual_scaffold_4[27.78 Mbp]
moved to
hap1_manual_scaffold_4[27.62 Mbp]
Edit 7:**-as above**
hap1_manual_scaffold_4[27.68 Mbp] to hap1_manual_scaffold_4[27.83 Mbp]
moved to
hap1_manual_scaffold_4[27.66 Mbp]
Edit 8:**- I'm not sure what is happening here**
hap1_manual_scaffold_8[25.19 Mbp] to hap1_manual_scaffold_4[27.27 Mbp]
moved to
hap1_manual_scaffold_8[25.17 Mbp]
Edit 9:**- more 20kb shifts**
hap1_manual_scaffold_4[28.45 Mbp] to hap1_manual_scaffold_4[28.52 Mbp]
moved to
hap1_manual_scaffold_4[28.43 Mbp]
Edit 10:**-as above**
hap1_manual_scaffold_4[27.24 Mbp] to hap1_manual_scaffold_4[27.29 Mbp]
moved to
hap1_manual_scaffold_4[28.63 Mbp]
Edit 11:**-as above**
hap1_manual_scaffold_4[27.66 Mbp] to hap1_manual_scaffold_4[27.74 Mbp]
moved to
hap1_manual_scaffold_4[27.65 Mbp]
Edit 12:**-as above**
hap1_manual_scaffold_4[27.72 Mbp] to hap1_manual_scaffold_4[27.75 Mbp]
moved to
hap1_manual_scaffold_4[27.71 Mbp]
Edit 13:**-as above**
hap1_manual_scaffold_4[27.62 Mbp] to hap1_manual_scaffold_4[28.90 Mbp]
moved to
hap1_manual_scaffold_4[26.88 Mbp]
Edit 14:**- this is a centromeric repeat in the middle of a contig, are you sure it should be moved to another chromosome?**
hap1_manual_scaffold_8[24.93 Mbp] to hap1_manual_scaffold_8[25.19 Mbp]
moved to
hap1_manual_scaffold_4[28.61 Mbp]
Edit 15:**- more small shifts**
hap1_manual_scaffold_14[21.71 Mbp] to hap1_manual_scaffold_14[21.26 Mbp]
moved to
hap1_manual_scaffold_14[21.72 Mbp]
Edit 16:**-as above**
hap1_manual_scaffold_14[21.81 Mbp] to hap1_manual_scaffold_14[21.89 Mbp]
moved to
hap1_manual_scaffold_14[21.83 Mbp]
Edit 17:**- another centromeric repeat block, should it really be moved?**
hap1_manual_scaffold_15[10.10 Mbp] to hap1_manual_scaffold_15[10.33 Mbp]
moved to
hap1_manual_scaffold_14[20.41 Mbp]
Edit 18:**- another centromeric repeat region. This would involve cutting the contig, which I am not so keen on in this instance. I think looking at the higlass this is just a biological repeat**
hap1_manual_scaffold_14[21.83 Mbp] to hap1_manual_scaffold_14[20.44 Mbp]
inverted and moved to
hap1_manual_scaffold_14[20.31 Mbp]
Edit 19:**- potential false duplication in the middle of a contig - can we be sure this is not biological?**
hap1_manual_scaffold_17[1.11 Mbp] to hap1_manual_scaffold_17[1.31 Mbp]
moved to
hap1_manual_scaffold_18[15.01 kbp]
Edit 20:**- this is a mapping artifact due to the repetitive end of scaffold_21.**
hap1_manual_scaffold_24[0.00 bp] to hap1_manual_scaffold_24[1.05 Mbp]
moved to
hap1_manual_scaffold_21[31.73 Mbp]
Edit 21:**as above**
hap1_manual_scaffold_21[31.75 Mbp] to hap1_manual_scaffold_21[31.88 Mbp]
moved to
hap1_manual_scaffold_24[480.34 kbp]
Edit 22:**as above**
hap1_manual_scaffold_21[30.44 Mbp] to hap1_manual_scaffold_21[30.58 Mbp]
moved to
hap1_manual_scaffold_21[29.93 Mbp]
Edit 23:**as above**
hap1_manual_scaffold_21[30.98 Mbp] to hap1_manual_scaffold_21[31.09 Mbp]
moved to
hap1_manual_scaffold_21[30.11 Mbp]
Edit 24:**I think this is just rearranging the small stuff**
hap1_manual_scaffold_38[0.00 bp] to hap1_manual_scaffold_28[105.07 kbp]
moved to
hap1_manual_scaffold_37[30.02 kbp]
Edit 25:**I think this is just rearranging the small stuff**
hap1_manual_scaffold_35[0.00 bp] to hap1_manual_scaffold_42[15.01 kbp]
moved to
hap1_manual_scaffold_28[0.00 bp]
**Other:
Inverted first 1Mb of scaffold_20**
I think we can try to place the last little scaffolds in the scaffold 21**These pieces also have a strong signal with scaffolds 20, 23, 24...

**Comment by tbrown91** [comment]
@additive3 some thoughts...


Hap1_scaffold2 270-480kb flip and move to start of scaffold **done**
Hap1_scaffold2 39.16-39.54Mb flip **done**
Hap1_scaffold3 1.76-2.16Mb suggest this does want to flip (is it gapped?) **done**
Hap1_scaffold4 28.9-29.2Mb localises to Hap1_scaffold15 9.5Mb **centromeric repeat in the middle of a contig - fits best in 4**
Hap1_scaffold6 12-12.15Mb places @24.8Mb **looks far worse in pretext than it actually is**
Hap1_scaffold26 and Hap1_scaffold27 localised to start of Hap1_scaffold10 (+26, +27, +10) ** done**
Hap1_scaffold13 37.46Mb break/flip, some hapdup also needs to be removed from the contig end 38.1-end. **flip done - how can you be sure the repeat is not biological?**
Hap1_scaffold17 780kb-1Mb hapdup remove **in the middle of a contig - same question**
Hap1_scaffold20 break 1.36Mb flip **done**
Hap1_scaffold21 20.23-20.45Mb flip **done**
Hap1_scaffold22 11.68-12Mb flip **done**
Hap1_scaffold29 looks to be hapdup remove **how can you be sure this is not just centromeric signal that can't be placed? It seems to have a lot of interactions throughout the genome**

**Comment by CaroB-M** [comment]
hap1_manual_scaffold_2[39.25 Mbp] to hap1_manual_scaffold_2[39.37 Mbp]
moved to
hap1_manual_scaffold_2[39.24 Mbp]
Are these all typos? They don't seem to be actually changing anything, unless you really want to shift them all 20kb upstream.   **Yes you re right**

Are these all typos? They don't seem to be actually changing anything, unless you really want to shift them all 20kb upstream.

**Maybe it is false edits in pretext. Sorry I didn't pay attention to that... I tried some moves and it had let this kind of edits in pretext**

hap1_manual_scaffold_4[27.62 Mbp] to hap1_manual_scaffold_4[28.90 Mbp]
moved to
hap1_manual_scaffold_4[26.88 Mbp]
Edit 14:- this is a centromeric repeat in the middle of a contig, are you sure it should be moved to another chromosome?

**Yes I moved different several contigs to a centromere because they have contacts just with this one.**

image

**This part of the scaffold 21 looks better after the changes**

**Comment by CaroB-M** [comment]
Hap1_scaffold4 28.9-29.2Mb localises to Hap1_scaffold15 9.5Mb centromeric repeat in the middle of a contig - fits best in 4    **it has contact with scaff 4 and 6, better contacts with 4**

Hap1_scaffold13 37.46Mb break/flip, some hapdup also needs to be removed from the contig end 38.1-end. flip done - how can you be sure the repeat is not biological?   **yes you have a drop in the coverage**

Hap1_scaffold29 looks to be hapdup remove how can you be sure this is not just centromeric signal that can't be placed? It seems to have a lot of interactions throughout the genome
**I think it can be moved in scaffold 23 18,7Mb**

**Comment by additive3** [comment]
Hi @tbrown91 

**Hap1_scaffold4 28.9-29.2Mb localises to Hap1_scaffold15 9.5Mb centromeric repeat in the middle of a contig - fits best in 4**
Yes I agree it is centromeric but only has very limited interaction with scaffold4. much stronger interaction across a wider region on scaffold15

**Hap1_scaffold6 12-12.15Mb places @24.8Mb looks far worse in pretext than it actually is**
Do you mean interms of the the sequence and hic interaction? Yes I agree it is probably more/over saturated in pretext and the amount of sequence that requires moving is tiny.

**Hap1_scaffold13 37.46Mb break/flip, some hapdup also needs to be removed from the contig end 38.1-end. flip done - how can you be sure the repeat is not biological?**
**Hap1_scaffold17 780kb-1Mb hapdup remove in the middle of a contig - same question**
There is a drop in the coverage to ~50%, you do see coverage drops through repeats but it tends to be satellites, if real i would expect to see diploid level of coverage over both copies, or if indel in one hap, one copy at dip, one copy at hap cov.

**Hap1_scaffold29 looks to be hapdup remove how can you be sure this is not just centromeric signal that can't be placed? It seems to have a lot of interactions throughout the genome**
Again combination of the above responses, Hi-C interaction strongest to Hap1_scaffold_23 (sorry I should have explicitly mentioned this) every other scaffold interaction is very limited. The contig is also half coverage, and there looks to be a direct repeat line.. to the region in 23 as with the other hapdup calls.

Best,
Jo

**Comment by additive3** [comment]
I see @CaroB-M has identified the same things I have just mentioned in identifing the problems/resolutions :)

**Comment by tbrown91** [comment]
@CaroB-M @additive3 
I have added a new pretext file with the changes in the save-state for hap1 in the same download folder.

Thank you both for the thorough review. As I said in the report, it's been a number of years since I've looked at this genome and I appreciate the review before it gets uploaded to ENA.

@CaroB-M if you have any comments for the hap2 assembly, I would really appreciate it.

All the best and many thanks again

**Comment by CaroB-M** [comment]
here are the edits for hap2 : 

Edit 1:
       hap2_manual_scaffold_2[480.90 kbp] to hap2_manual_scaffold_2[495.93 kbp]
       moved to
       hap2_manual_scaffold_2[0.00 bp]
Edit 2:
       hap2_manual_scaffold_4[27.49 Mbp] to hap2_manual_scaffold_6[23.41 Mbp]
       moved to
       hap2_manual_scaffold_4[27.47 Mbp]
Edit 3:
       hap2_manual_scaffold_4[27.52 Mbp] to hap2_manual_scaffold_6[23.43 Mbp]
       moved to
       hap2_manual_scaffold_4[27.50 Mbp]
Edit 4:
       hap2_manual_scaffold_4[27.52 Mbp] to hap2_manual_scaffold_2[39.06 Mbp]
       moved to
       hap2_manual_scaffold_4[27.50 Mbp]
Edit 5:
       hap2_manual_scaffold_4[27.64 Mbp] to hap2_manual_scaffold_6[23.41 Mbp]
       moved to
       hap2_manual_scaffold_4[27.62 Mbp]
Edit 6:
       hap2_manual_scaffold_7[29.24 Mbp] to hap2_manual_scaffold_8[22.96 Mbp]
       moved to
       hap2_manual_scaffold_7[29.23 Mbp]
Edit 7:
       hap2_manual_scaffold_4[27.59 Mbp] to hap2_manual_scaffold_2[39.07 Mbp]
       moved to
       hap2_manual_scaffold_4[27.58 Mbp]
Edit 8:
       hap2_manual_scaffold_4[27.35 Mbp] to hap2_manual_scaffold_4[27.65 Mbp]
       moved to
       hap2_manual_scaffold_4[27.08 Mbp]
Edit 9:
       hap2_manual_scaffold_7[29.21 Mbp] to hap2_manual_scaffold_7[29.30 Mbp]
       moved to
       hap2_manual_scaffold_4[27.77 Mbp]
Edit 10:
       hap2_manual_scaffold_8[22.96 Mbp] to hap2_manual_scaffold_8[23.29 Mbp]
       moved to
       hap2_manual_scaffold_5[32.76 Mbp]
Edit 12:
       hap2_manual_scaffold_9[16.95 Mbp] to hap2_manual_scaffold_9[17.04 Mbp]
       moved to
       hap2_manual_scaffold_8[23.28 Mbp]
Edit 19:
       hap2_manual_scaffold_26[0.00 bp] to hap2_manual_scaffold_26[1.52 Mbp]
       moved to
       hap2_manual_scaffold_8[9.86 Mbp]
Edit 20:
       hap2_manual_scaffold_35[0.00 bp] to hap2_manual_scaffold_35[255.48 kbp]
       moved to
       hap2_manual_scaffold_13[37.00 Mbp]
Edit 21:
       hap2_manual_scaffold_19[22.51 Mbp] to hap2_manual_scaffold_19[23.83 Mbp]
       moved to
       hap2_manual_scaffold_14[22.38 Mbp]
Edit 22:
       hap2_manual_scaffold_27[0.00 bp] to hap2_manual_scaffold_29[15.03 kbp]
       moved to
       hap2_manual_scaffold_16[37.19 Mbp]


image

this part of the scaffold 4 looks better when you move all these small contigs

**Comment by additive3** [comment]
Hi @tbrown91 @CaroB-M 
I agree, I would not be moving all these satellite sequences to one region.
Suggestions for (re)localisation should only be made when there is evidence.
With regards these sequences, the Hi-C interations are because they are highly similar across the genome and the multi-align read information are being retained in the contact map generation.

Looking at the map I don't belive these satellites are the actual centromeres... but are proximal to them.

**Comment by tbrown91** [comment]
Thank you both! I've gone through and made the changes I feel comfortable making

Hap2 changes:
hap2_manual_scaffold_1  1       57224652        1       W       hap2_manual_scaffold_1  1       57224652        +
hap2_manual_scaffold_2  1       184334  1       W       hap2_manual_scaffold_2  307140  491473  +
hap2_manual_scaffold_2  184335  184434  2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_2  184435  491473  3       W       hap2_manual_scaffold_2  1       307039  +
hap2_manual_scaffold_2  491474  491573  4       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_2  491574  53349730        5       W       hap2_manual_scaffold_2  491574  53349730        +
hap2_manual_scaffold_3  1       6322660 1       W       hap2_manual_scaffold_3  1       6322660 +
hap2_manual_scaffold_3  6322661 6322760 2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_3  6322761 53530201        3       W       hap2_manual_scaffold_3  6468340 53675780        +
hap2_manual_scaffold_4  1       47703140        1       W       hap2_manual_scaffold_4  1       47703140        +
hap2_manual_scaffold_5  1       29006231        1       W       hap2_manual_scaffold_5  1       29006231        +
hap2_manual_scaffold_5  29006232        29006331        2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_5  29006332        29379483        3       W       hap2_manual_scaffold_5  29006332        29379483        -
hap2_manual_scaffold_5  29379484        29379583        4       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_5  29379584        43236044        5       W       hap2_manual_scaffold_5  29379584        43236044        +
hap2_manual_scaffold_6  1       42008159        1       W       hap2_manual_scaffold_6  1       42008159        +
hap2_manual_scaffold_7  1       40814457        1       W       hap2_manual_scaffold_7  1       40814457        +
hap2_manual_scaffold_8  1       9883701 1       W       hap2_manual_scaffold_8  1       9883701 +
hap2_manual_scaffold_8  9883702 9883801 2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_8  9883802 11499692        3       W       hap2_manual_scaffold_26 1       1615891 +
hap2_manual_scaffold_8  11499693        11499792        4       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_8  11499793        37853204        5       W       hap2_manual_scaffold_8  9883942 36237353        +
hap2_manual_scaffold_8  37853205        37853304        6       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_8  37853305        41379139        7       W       hap2_manual_scaffold_8  36422900        39948734        +
hap2_manual_scaffold_9  1       40357516        1       W       hap2_manual_scaffold_9  1       40357516        +
hap2_manual_scaffold_10 1       39962871        1       W       hap2_manual_scaffold_10 1       39962871        +
hap2_manual_scaffold_11 1       38344506        1       W       hap2_manual_scaffold_11 1       38344506        +
hap2_manual_scaffold_12 1       38161978        1       W       hap2_manual_scaffold_12 1       38161978        +
hap2_manual_scaffold_13 1       38563620        1       W       hap2_manual_scaffold_13 1       38563620        +
hap2_manual_scaffold_14 1       37458866        1       W       hap2_manual_scaffold_14 1       37458866        +
hap2_manual_scaffold_15 1       37440632        1       W       hap2_manual_scaffold_15 1       37440632        +
hap2_manual_scaffold_16 1       37265869        1       W       hap2_manual_scaffold_16 1       37265869        +
hap2_manual_scaffold_17 1       34566735        1       W       hap2_manual_scaffold_17 1       34566735        +
hap2_manual_scaffold_18 1       23936730        1       W       hap2_manual_scaffold_18 1       23936730        +
hap2_manual_scaffold_18 23936731        23936830        2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_18 23936831        24122376        3       W       hap2_manual_scaffold_8  36237354        36422899        +
hap2_manual_scaffold_18 24122377        24122476        4       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_18 24122477        36873664        5       W       hap2_manual_scaffold_18 23936831        36688018        +
hap2_manual_scaffold_19 1       37937741        1       W       hap2_manual_scaffold_19 1       37937741        +
hap2_manual_scaffold_20 1       1231958 1       W       hap2_manual_scaffold_20 1       1231958 -
hap2_manual_scaffold_20 1231959 1232058 2       U       100     scaffold        yes     proximity_ligation
hap2_manual_scaffold_20 1232059 34782916        3       W       hap2_manual_scaffold_20 1232059 34782916        +
hap2_manual_scaffold_21 1       31539787        1       W       hap2_manual_scaffold_21 1       31539787        +
hap2_manual_scaffold_22 1       33457341        1       W       hap2_manual_scaffold_22 1       33457341        +
hap2_manual_scaffold_23 1       30684359        1       W       hap2_manual_scaffold_23 1       30684359        +
hap2_manual_scaffold_24 1       29183921        1       W       hap2_manual_scaffold_24 1       29183921        +
hap2_manual_scaffold_25 1       27951010        1       W       hap2_manual_scaffold_25 1       27951010        +
hapdup_1        1       145679  1       W       hap2_manual_scaffold_3  6322661 6468339 +

I will make a screenshot from pretext for a new EAR, but you can't see much at the genome-scale.

**Comment by diegomics** [comment]
Hi @CaroB-M would you please review the latest changes from Tom and add your review, thanks!

**Comment by CaroB-M** [comment]
Hello @tbrown91 you didn't add the pretext map to the last EAR report? 
On the screenshots, I don't see more to change but it is harder to decide.

**Comment by CaroB-M** [comment]
Hi @tbrown91 
maybe a last move in hap1
Edit 11:
       hap1_manual_scaffold_14[20.35 Mbp] to hap1_manual_scaffold_14[20.47 Mbp]
       moved to
       hap1_manual_scaffold_14[21.92 Mbp]

Nothing to change in hap2.

**Comment by tbrown91** [comment]
Hi @CaroB-M I had a look and this is another instance of repeat arrays around the centromere:

image


I don't think this should be grouped together, as this is due to very similar sequence causing secondary mappings with the HiC data

**Comment by diegomics** [comment]
I think this is good to go. @CaroB-M if you agree please click the `Add your review` and `Review changes` green buttons to approve or request further changes

**Review by CaroB-M — APPROVED** [review]

**Comment by diegomics** [comment]
Thanks @CaroB-M for the review.
I will add a new reviewed species for you to the table ;)
Also, thanks @additive3 for all your input, it was really helpful 🙌

Congrats on the assembly @tbrown91!
After the merging, you can [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission)

**Review by diegomics — APPROVED** [review]

**Pull request merged**
