### PR TITLE
Added Macrothele cretica / qqMacCret1

### PR DESCRIPTION
**Pull request by EmilieTeo**
## Assembly review request

- ToLID: qqMacCret1
- Species: Macrothele cretica
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by tbrown91** [comment]
ok

**Comment by EmilieTeo** [comment]
Hi @tbrown91
Maybe I should close this pull request to redo it properly without my previous commits ?

**Comment by tbrown91** [comment]
It's ok now, not a problem.

**Comment by JoannaCollins** [comment]
Yes

**Review by JoannaCollins — CHANGES_REQUESTED** [review]
Hi Emilie,

Apologies for the delay in giving feedback on this assembly. I think you have done a really great job here with a difficult assembly that unfortunately has very poor HIC data. With regard to the HIC I was wondering how much coverage you achieved? and if you mapped your duplicate/repetitive reads? If not it might be worth considering doing this to try and improve the signal.  If this is something you have already done then i really think it would be beneficial to get additional HIC data if at all possible? The reason being that due to the lack of signal it is quite difficult to determine with certainty the correct  the assembly path in a number of regions. 

I don't know if it is possible for you to do, but we have a telomere track that we upload to our pretext maps which is also helpful for correct chromosome assembly, particularly if HIC data is poor. There are a few chromosomes in this assembly where it looks as though the end may flip but the data is ambiguous due to poor HIC. Having the telo track (provided telo's are present) can help provide confirmation of assembly over these types of region.

Regarding the half coverage chromosomes, typically we would assign these using the coverage as evidence for the assignment. This genus has representatives with between 9 and 13 X's so i think it would be appropriate to assign all the half coverage chromosomes X1-X11 in this case.

I have gone through the assembly as best as i can given the quality of the HIC. I am concerned that there are regions that are not resolvable with certainty as its just too difficult to place things due to lack of signal. I think potentially there are also likely to be contiging errors that are also being masked. As such below is a list of observations I have made where the HIC signal as it is suggests misplacement. Please do let me know though where something is not clear or if you feel the data is not of good enough quality to make a change. Ultimately i think some additional HIC would help to resolve the regions of ambiguity. 

SUPER_16: 45.59 looks to belong 69.17 or is hap.
SUPER_17: block on left end belongs @ ~26.67.
SUPER_18: looks like a break is needed at ~84.69 and the end needs to be inverted.
SUPER_19: needs breaks @ gaps 70.14-73.48 and region needs inverting.
SUPER_21: the unlocs need reassigning as i don't think that any of them assign to this chromosome:
SUPER_21_unloc_2 - localises to SUPER_39 (SUPER_39 looks to need rearranging - see note below)
SUPERs_21_unloc_3, 4  5 - all seem to localise to SUPER_42  in the gap @ 19.58. It is difficult to order and orientate them though with the HiC data as it is.
SUPER_22: HIC data suggests a break @ ~88.70 and that the end should be inverted.
SUPER_24: region ~42.07-43.77 does not appear to belong on this chromosome. The region around  64.87 looks a bit odd, maybe hap dup but coverage is high over whole region so difficult to be sure. More HIC would likely help what is going on here.
SUPER_28: HIC suggests a break is needed @ ~12.91Mb and the left end should be inverted.
SUPER_29: HIC suggests a break is needed @ ~12.67Mb and the left end should be inverted.
SUPER_31: this is as bit less certain but HIC seems to suggest a break is needed @ ~49.47 and the right end should be inverted.
SUPER_33: again, difficult to be sure because of the poor HIC but I think there may need to be a break @~43.10 and the end inverted.
SUPER_35: possible break @ ~12.12 and left end inverts
SUPER_39: needs to break @ 13.58 and 26.73 and then this piece inverts, then i think you need SUPER_21_unloc_2 in the +ve orientation, then what is left of S_39 invets to the -ve orientation.
SUPER_40: needs to break @ ~4.97 as this piece seems to localise closer to around 39.28 although i can't place it with any accuracy. I also think 5.45- 10.97 belongs on the right hand end of the chromosome, again its difficult to place with any accuracy and might be best to unloc.  I think maybe the unloc joins onto the right end end of this piece. SUPER_40 ~11.09-13.33 belongs on SUPER_37 but i can't place it so it would have to be unloc.
SUPER_44: Looks like it needs to break @ ~12.27 and 12.27-end goes at the beginning of the chromosome. I think there maybe other misassembly within this chromosome as well e.g possible inversions but its very difficult to be certain.
SUPER_47: needs to break @ ~3.75 and this piece looks to locate closer to the right hand end.

Laslty there is the possibility that scaffolds SUPER_21_unloc_1, scaffold_59, and 66 could be another X but this cannot be confirmed easily with the HIC data but should you be able to get more this might give you further evidence.


Best Wishes, Jo

**Comment by additive3** [comment]
Paper karyotyping M. gigas:
https://academic.oup.com/biolinnean/article/109/2/377/2415906

**Comment by tbrown91** [comment]
Hi @EmilieTeo Can you please have a look through the suggestions from @JoannaCollins ?

Thank you for the review Jo and the link to the paper Jo

**Comment by EmilieTeo** [comment]
Hi Joanna, 
Thank you very much for your thorough review !
I only have 15X of HiC coverage which is indeed lacking. 
We would still like to achieve a first version of this assembly with what we have, but still try to get additional HiC data to try to complete a second version of this assembly. 

I assigned the half coverage chromosomes X_1 to X_11 according to length. 

I did the changes that you suggested on the following scaffolds: 
SUPER_16
SUPER_17
SUPER_18
SUPER_19
SUPER_22
SUPER_28
SUPER_29
SUPER_31
SUPER_33
SUPER_35
SUPER_39
SUPER_44
SUPER_47


For SUPER_21, SUPERs_21_unloc_3, 4 5 - all seem to localise to SUPER_42 in the gap @ 19.58, as it was difficult to place them, I moved them but placed them as unloc.

For SUPER_24, the region ~42.07-43.77 looks like it might belong to SUPER_21 (now X_1) but I was unable to precisely place it so I placed itas unloc ?
Region around 64.87 is indeed odd but without a drop in coverage and without more HiC maybe leave it as is. 

For SUPER_40, I did all the modifications that you suggested. The only uncertainty is about the beginning of the scaffold until ~4.97. I moved this region into a gap but I'm not sure it looks better placed here. For SUPER_40 I also placed region 5.45- 10.97 as unloc. 

Emilie

**Comment by JoannaCollins** [comment]
Hi Emilie,

Thanks for sending the updated map and for listing all the changes :-).

Its great that you are going to try and get additional HiC for this sample, as hopefully it will help to get a much clearer picture of the assembly. 

The updated assembly looks good, there are just a couple of things remaining.

I apologise, I think maybe I wasn't explicit about the changes needed for the SUPER_21_unlocs in my prior message.  The ones that you have assigned to other chromosomes all look to be correct :-). However I should have been clear that the unlocs that don't appear to assign elsewhere also don't have a particular affinity to X1 or elsewhere so these scaffolds (X1_unloc_1, 2 and 3) should just be left as unassigned in the assembly.

The only other observation I made was that the HIC signal suggests that perhaps the region 0-5.60Mb on X_9 potentially moves to the other end of the chromosome? Maybe you can see this more clearly if you are working in the lower resolution map? 

Best Wishes

Jo

**Comment by tbrown91** [comment]
Thank you @JoannaCollins Are you able to share a savestate with some of the edits you are suggesting? Perhaps things are getting a little lost in trying to describe everything.

@EmilieTeo If you are able to look through the final changes and make a decision either way, it would be fantastic to wrap this genome up this week.

**Comment by JoannaCollins** [comment]
Hi @tbrown91 and @EmilieTeo,

I thought it might be easier to use some screen shots rather than a save state, hopefully this makes things clearer. Any further questions please ask.

qqMacCret1_X_1_unloc

qqMacCret1_X_9

qqMacCret1X_9_a

Best Wishes

Jo

**Comment by ldemirdj** [comment]
Hi @tbrown91,
I hope you're doing well. I wanted to let you know that Emilie has been traveling for work for the past two weeks and will continue to be out of office  this week as well. She’ll do her best to finalize the genome, but it’s possible it may only be completed next week. Apologies for the inconvenience, and thank you for your understanding.
Best regards,
Lola

**Comment by tbrown91** [comment]
Hi @ldemirdj thanks for letting me know. I will check in again at the end of next week.

All the best,
Tom

**Comment by EmilieTeo** [comment]
Hi, @JoannaCollins and @tbrown91 
Sorry for the delay, I had a problem when trying to make the new EAR report so it took longer than expected. 
I made the last changes that you suggested 

Best, 
Emilie

**Comment by tbrown91** [comment]
Thank you both! Great to see another assembly through

**Pull request merged**
