### PR TITLE
Add Holothuria sanctori

### PR DESCRIPTION
**Pull request by ldemirdj**
## Assembly review request

- ToLID: ehHolSanc2
- Species: Holothuria sanctori
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by diegomics** [comment]
ping @gitcruz we are waiting for your answer

**Comment by ldemirdj** [comment]
Hello, I have already noticed a few things to change on the Hi-C map, so I made the modifications, and the new EAR report is currently being generated. I will make it available as soon as I have it. In the meantime, I’m waiting for feedback from the reviewer. Thanks!

**Comment by gitcruz** [comment]
Yes

**Comment by gitcruz** [comment]
Dear Lola,

@ldemirdj Please let me know when the new report is ready to start the review.

Thanks,
Fernando

**Comment by ldemirdj** [comment]
Hello @gitcruz, yess it will be done tomorow. Thanks!

**Comment by ldemirdj** [comment]
Hello @gitcruz, 

I’ve updated the EAR report, and it’s now ready for review. Apologies for the confusion; I realize that I should have given this second EAR report the same name, but I’m not sure how to change it. Please let me know if any adjustments are needed so we can quickly finalize it and submit it to ENA before October 31.

Thank you in advance for your help.

Best regards,  

Lola

**Comment by diegomics** [comment]
Hi @ldemirdj ,
Your PR contains two pdf files:
`Assembly_Reports/Holothuria_sanctori/ehHolSanc2/ehHolSanc2_EAR.pdf`
`Assembly_Reports/Holothuria_sanctori/ehHolSanc2/ehHolSanc2_EAR2.pdf`

I would guess the one for review is ehHolSanc2_EAR2.pdf, right?
Please delete the old one and rename the correct one so it ends with EAR.pdf
Thx!

**Comment by ldemirdj** [comment]
Hi @diegomics, it's done :)

**Comment by gitcruz** [comment]
Hi @ldemirdj 

Excelent work given the low density of the compact map. Most of the SUPER look good and most of them are flanked by telomeres. My only suggestion is regarding to a contig in SUPER_6 that does not seem to fit well, I tried to flip it but still shows an ugly pattren of contacts. I think SUPER_6[47.09 Mbp] to SUPER_6[47.84 Mbp] should be excised and tagged as unloc. What do you think Lola?

I don't know if @diegomics have anything else to say.

To me is almost ready to go to ENA.

Cheers.
Fernando

**Comment by diegomics** [comment]
Hi @ldemirdj the metrics look very good
I'm not super sure about the boundaries of that weir spot that @gitcruz mentioned on SUPER_6. Similar to another weird spot in SUPER_13 @ 9,547. What others think about this at Genoscope?
Additionally:
I'm not sure why SUPER_18_unloc_1 should not be placed in SUPER_18 @ 15,590 Would you like to comment about it?
I'm seeing off-terminal Telo signal in the SUPER_1. Can you comment on it?

Screenshot 2024-10-28 at 14 25 53

I think we can approve this one pretty fast :)

**Comment by diegomics** [comment]
True, let's follow the conservative approach on those two spots, and wait for @ldemirdj feedback

**Comment by ldemirdj** [comment]
Hi @gitcruz, @diegomics, 

Thank you all for the detailed feedback!

For SUPER_6, I agree with the suggestion to remove the contig from 47.09 Mbp to 47.84 Mbp and mark it as unloc due to its inconsistent contact pattern. I’ll proceed with this adjustment unless anyone has further feedback. I’ll also check the boundary issues in SUPER_13 that @gitcruz pointed out to ensure no additional changes are necessary.

Regarding the placement of SUPER_18_unloc_1, I agree with Fernando’s approach of proceeding cautiously given the low Hi-C coverage, especially since there are no visible gaps in SUPER_13 and SUPER_18.

I am currently regenerating the EAR report for a final review. After confirming these final details, we should be ready to submit the project to ENA. 

Thanks again for the excellent collaboration!

Cheers,  

Lola

**Comment by ldemirdj** [comment]
Hi evereyone, 

Here is the latest update. Please let me know if you see any further changes needed so we can proceed with the ENA submission. 

Thank you!

Lola

**Comment by diegomics** [comment]
Looks good. @gitcruz please approve if you think all is ok.

**Review by gitcruz — APPROVED** [review]
Approved, excellent work Lola! 

One more for the ENA!

**Comment by diegomics** [comment]
Thanks all! Merging...

**Pull request merged**
