### PR TITLE
Adding idCulThei1 EAR

### PR DESCRIPTION
**Pull request by DomAbsolon**
## Assembly review request

- ToLID: idCulThei1
- Species: Culex theileri
- Project: ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by tbrown91** [comment]
yes

**Comment by tbrown91** [comment]
Hi Dom @DomAbsolon,

Thanks for submitting yet another tricky assembly. I'm sure you guys will be really happy not to see any more Culex genomes. Generally the scaffolding itself looks perfect, I have just found a number of regions that look to have retained haplotypes and from the stats it looks like you already had to remove quite a number. I have put with a star those that I am less sure about. Hopefully a quick look-through for you as well.

Many thanks again

Potential retained duplication SUPER_1 around 45.5Mb, 108Mb, 154.9Mb, 198.7Mb, 305.3Mb, 333.8Mb
image
image
image
image
image
image

SUPER_2 around 32.9Mb*, 42.3Mb, 148.3Mb (hapdup with 53.2Mb), 167.7Mb, 187.1Mb*, 206.9Mb & 208.8Mb, 248.7Mb*
image
image
image
image
image
image
image

SUPER_3 looks good to me

**Comment by tbrown91** [comment]
Hi @DomAbsolon have you had a chance to look through the suggested edits? I don't think it should take long to turn this around and get it submitted

**Comment by DomAbsolon** [comment]
@tbrown91 I have uploaded new map for you to check. If you're happy with it I will remake the EAR. https://tolqc.cog.sanger.ac.uk/erga-bge/insects/Culex_theileri/assembly/curated/idCulThei1.1/ear_v2/idCulThei1.1_normal.pretext

**Comment by tbrown91** [comment]
Hi @DomAbsolon Thanks for the new map. The map overall is looking good. I wonder if something happened with your super_2_unloc sequence - it looks like the first 2Mb have ended up at the end of SUPER_2:

image

Here's my edit:

https://box.fu-berlin.de/s/psS7A6q8wiA4Poc

Otherwise I'm happy with the rest of the assembly

**Comment by DomAbsolon** [comment]
Oh sorry yeah you're right. I'll re-unloc (must have miss painted) and make a new ear to upload

**Comment by diegomics** [comment]
Hi @DomAbsolon
Can you share the savestate with the latest proposed changes so @tbrown91 can have a look and move forward to approve this one? Thx!

**Comment by DomAbsolon** [comment]
Hi, there's no save state to be shared I don't think. I am waiting for the EAR to be regenerated. Should be up in the next day or so.

**Comment by tbrown91** [comment]
Thanks @DomAbsolon I'm really happy with this one. 

Please no more Culex's

**Review by tbrown91 — APPROVED** [review]

**Pull request merged**
