### PR TITLE
qqGluDors1 EAR

### PR DESCRIPTION
**Pull request by gitcruz**
Assembly review request
---

- ToLID: qqGluDors1
- Species: Gluvia dorsalis
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @gitcruz, thanks for sending the EAR of _Gluvia dorsalis_. I added the corresponding tag to the PR and appointed @tbrown91  as assignee to supervise. I will contact a reviewer ASAP.
:ear:

**Comment by diegomics** [comment]
Hi @tommathers, do you agree to review this assembly? Please reply to this message only with **Yes** or **No** by 12-APR-2024 at 15:15 CET.

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Review by tommathers — CHANGES_REQUESTED** [review]
Based on HiC background signal SUPER_7 joins to SUPER_1 and SUPER_6 joins to SUPER_2 (note this is more visible in the low res map than the high res map).

The HIC signal looks better for both chunks if they are joined in their current orientation eg. SUPER_7 end joins start of SUPER_1. However, if you would prefer to be more cautious then they could be tagged as unlocalised (unloc in pretext). It is somewhat ambiguous as there may be some missing assembly content in this region.

**Comment by gitcruz** [comment]
Thanks for your quick response @tommathers!!!

I already saw these contacts, but to me they are weak and terminal...I interpreted them as t2t contacts (between telomeric regions) in fact super_6 carries an array of telomeric sequence at one end. As you suggested I did move them in their current orientation (using a multimappings pretext, now in the folder). But, SUPER_7 has to be placed right before a telomere peak in SUPER_1 and that's something I don't like very much.

After moving them, there is a sharp contrast between these SUPER (6 and 7) and their target (1 and 2) and I don't like how they fit there, it seems that they don't belong to that "chromosome" or something is missing:

move_SUPER7_to_SUPER1

move_SUPER6_to_SUPE2

They are both slightly over 7Mb, and as I don't know much of spider karyotypes I thought they could be considered micro-chromosomes....but perhaps does not make sense to do so. 

In my opinion, we could also consider them as "unplaced" (if we think that they don't earn SUPER status based on their length). To recap the options as I see them: 
a) Consider them Unlocs of SUPER_1 and 2 as @tommathers  suggested 
b) Unplaced them 
c) Leave them as SUPER_6 & 7 (original map)

What do @tbrown91 thinks?

Best,
Fernando

**Comment by tommathers** [comment]
Hi Fernando - is the QC map using multi mapping reads? In your message you say you have added a new map with multi mappers - can you point me to this file?

**Comment by gitcruz** [comment]
Hi,

I just added this one to the same shared folder that containing the other
Maps. IS the one that has  mq0 and sorted_by_len in its filename. Its done
with default resolution.
Please let me know If you find It.

Cheers

**Comment by tbrown91** [comment]
Morning both,

I tend to take a more cautious approach, so wouldn't go as far as placing Super6&7 as suggested in chromosomes, but I think it makes sense to include them as unlocalised sequences. From the 3 maps you've shared I think you can be fairly confident that Super 7 belongs with Super 1 and Super 6 belongs with Super 2, unless there are large chunks of sequence missing from the assembly, but we can't say anything certain about that.

@gitcruz I would leave the final decision to you: either place them as unlocalised sequences, or include as scaffolds that are not chromosomes in the hope that someone does a karyotype or further sequencing in this genus.

**Comment by gitcruz** [comment]
Hi,

I was thinking about this and I agree that this two scaffolds can be placed in SUPER_1 and SUPER_2. Although these chromosomes could be acrocentric, it's hard to localize the 7Mb in them. I prefer to be conservative an Unloc them. I will produce a new fasta and a new pretext in order to get the approval for ENA upload.

Thanks @tommathers and @tbrown91 for your time and comments.

Best, 
Fernando

**Comment by tommathers** [comment]
Sounds good to me.

Tom.

Dr. Thomas Mathers
Senior Computer Biologist
Genome Reference Informatics Team
Tree of Life
Wellcome Sanger Institute
Hinxton
Cambridge
CB10 1SA

Twitter: @Thomas_Mathers [twitter.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_Thomas-5FMathers-3Flang-3Den-2Dgb&d=DwMGaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=tJRHixSYq-VP6FIxTiP35xdkMZl3FaXQVx1qay3XZ-7I4UkhUxDC7h1P98bVhcBb&s=hffLCC65eIfPsnmm3hnO-CV4DYCZYG2ebSippldU3zw&e=>
Publications: Google Scholar [scholar.google.co.uk]<https://urldefense.proofpoint.com/v2/url?u=https-3A__scholar.google.co.uk_citations-3Fhl-3Den-26user-3D5XjBm94AAAAJ-26view-5Fop-3Dlist-5Fworks-26sortby-3Dpubdate&d=DwMFAg&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=KIKynKbLKfS4YVQYVctJHL39ls39CbRogxK7G0OumbwWdwS4Qdlkrg9NnRJHPJGs&s=T2pa4qY1i623xxULQ3x4gTTj4JvNcKbwYHoNm5knTFc&e=>


From: Fernando Cruz ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Monday, 8 April 2024 at 16:31
To: ERGA-consortium/EARs ***@***.***>
Cc: Thomas Mathers ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] qqGluDors1 EAR (PR #36) [EXT]


Hi @tbrown91 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tbrown91&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=PWimSdk318h3yUNxsGc69NPjRHJdTXjljPpodm_JEL_oLKhTBGqALskth-rhNHc_&s=hUpLtzwpBDyEjCX8WYsCKy0X6tjDgtLq1UE9ERtZb9o&e=>

I created a new version qqGluDors1.3, but as I told you I am planning to simply remap the hic again (with default resolution) and share the contact map with you and @tommathers [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tommathers&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=PWimSdk318h3yUNxsGc69NPjRHJdTXjljPpodm_JEL_oLKhTBGqALskth-rhNHc_&s=r_8p3w6CMUHmSAZlin15hekT_pZ_uOTNM2Qd3hn-9n4&e=>.

Personally, I don't think is necessary to rerun Blobtoolkit and create a new EAR report.

Please let me knoe if that's ok.

Thanks!
F.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_36-23issuecomment-2D2043067295&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=PWimSdk318h3yUNxsGc69NPjRHJdTXjljPpodm_JEL_oLKhTBGqALskth-rhNHc_&s=GHrcDZ8LswWhnz5my23fK46M4WZ9ixpyakAJxiWEr3M&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABVP3G3RHNFILPL2WUUOWP3Y4KZ6ZAVCNFSM6AAAAABFY5Z7UCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBTGA3DOMRZGU&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=MigC00eCez0AYiD8Bi3uR5vUblihAN7OJ3KK8sbnotw&m=PWimSdk318h3yUNxsGc69NPjRHJdTXjljPpodm_JEL_oLKhTBGqALskth-rhNHc_&s=w_PLrx0_r_Em_d6McGJwLolfVVNk7gZEBEOy4EFQgvE&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by tbrown91** [comment]
Could you please create a new EAR just with an updated snapshot of the pretext? As the scaffolds are unlocalised the blobplot will be identical.

**Comment by gitcruz** [comment]
Thanks @tbrown91 

Should the new EAR be uploaded overwriting the previous one?

WRT the blobplot I can insert a png without these two unlocs, so total number of scaffolds matches the main assembly stats

cheers

**Comment by diegomics** [comment]
Hi @gitcruz
Yes, replace the PDF in the branch `gitcruz-qqGluDors` of your repo, the pull request will be updated automatically.
Thanks!

**Comment by gitcruz** [comment]
Hi @diegomics, 

It's done. However, the PDF of both versions have different names (ToLID.version_EAR.pdf). Not sure if that's the best way to do it.

Please let me know if it worked well.

Thanks.

**Comment by diegomics** [comment]
Hi @gitcruz
Please, keep only the final version. Use the ToldID without versioning. The pull request should contain only one file.

**Comment by gitcruz** [comment]
How can I remove this file then? Then will change the name of latest to
overwrite 1.2

Thanks,
Fernando

**Comment by diegomics** [comment]
Here is a way of doing it from the browser:
Upload to _EARs/Assembly_Reports/Gluvia_dorsalis_ in your branch `gitcruz-qqGluDors1` a PDF report named qqGluDors1_EAR.pdf
Remove the files **qqGluDors1.2_EAR.pdf** and **qqGluDors1.3_EAR.pdf**
Please notice that inside your PDF report it also says qqGluDors1.3
That tolid does not exist when searched on https://id.tol.sanger.ac.uk/search
So you should change it to qqGluDors1.
;)

**Comment by gitcruz** [comment]
Thanks Diego.


Ah, I see the EAR field is just the ToLID so I did it wrong. I'll try to
fix this by uploading a report named just *qqGluDors1_EAR.pdf*

However, I think I will specify the assembly version in the notes field
qqGluDors1.3*.* For internal purposes we need to distinguish which version
will be uploaded to ENA. I am basically following the Tree of life naming
scheme: https://gitlab.com/wtsi-grit/darwin-tree-of-life-sample-naming

Best,
Fernando

**Comment by gitcruz** [comment]
Hi all,

I'm done with the changes and updated the PDF in github after a struggling with VS code. Now I would be able to do this faster. 

Please let me know if we can start uploading this spider genome to ENA.

Thanks!

**Comment by tbrown91** [comment]
Hi @gitcruz ,

Thans for re-uploading. @tommathers can I ask you to have one last look through and then "approve" the pull request if you are happy?

It's looking pretty good to me

**Comment by tbrown91** [comment]
@tommathers a ping to please give this one last look-over.

Many thanks

**Review by tommathers — APPROVED** [review]
SOrry for the delay. Looks good to me.

**Comment by tbrown91** [comment]
Thanks T9m

Good job @gitcruz with another assembly

**Review by tbrown91 — APPROVED** [review]

**Pull request merged**
