### PR TITLE
Add carabus banonii files

### PR DESCRIPTION
**Pull request by Arno75**
## Assembly review request

- ToLID: icCarBano7
- Species: Carabus banonii
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by additive3** [comment]
yes

From: "erga-ear-bot[bot]" ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Wednesday 9 October 2024 at 07:21
To: ERGA-consortium/EARs ***@***.***>
Cc: Jo Wood ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] Add carabus banonii files (PR #87) [EXT]


Hi @additive3 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_additive3&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=mziWyaWP7jU5nOZyYNxmiS1wrR94zjjHLp4de_dN0G3BvgKh8HpwSGEs_Z_NM1Nm&s=k0DA6oXV9SGOhcjBVBESV6cTbolI5o5ZISjUX8KEq50&e=>, do you agree to review this assembly?
Please reply to this message only with Yes or No by 16-Oct-2024 at 08:20 CET

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_87-23issuecomment-2D2401412353&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=mziWyaWP7jU5nOZyYNxmiS1wrR94zjjHLp4de_dN0G3BvgKh8HpwSGEs_Z_NM1Nm&s=8J__xbICCXXbewClFYyMcVBfF-KRHS4nDj_kw59bzAE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEFJV4KMGAMSMMFNAXOLW5LZ2TDOJAVCNFSM6AAAAABPSFIEXWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBRGQYTEMZVGM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=mziWyaWP7jU5nOZyYNxmiS1wrR94zjjHLp4de_dN0G3BvgKh8HpwSGEs_Z_NM1Nm&s=CH9vmX8lzui7x0nQjMSDvD2UxJQHEloHsXYFW43y81E&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by additive3** [comment]
Hi Arnaud @Arno75,

Thanks for uploading your assembly for review. 
These data are challenging and I have the following recommendations for updating the assembly prior to release.

Carabus sp. coleoptera have been widely karyotyped (sadly not this one) with the most common chromsome number 2n=28(XY) (Serrano J, Yadav JS (1984) Chromosome numbers and sex-determining mechanisms in adephagan
Coleoptera. Coleopt Bull 38: 335-357) https://www.jstor.org/stable/4008212?origin=JSTOR-pdf . From the provided assembly and analysis I observe the sample is male and I see in your genome, 13 autosomes and an XY pair.

I note the pretext map provided is high resolution. Given the genome size and how the Hi-C signal presents, it would be beneficial to have the normal resolution map, would you be able to provide? Either the assembly as is now or with suggested changes listed below, it might help me confirm the rearrangements.
I have included an AGP of the changes just in case the below is not clear.

Best,
Jo

Scaffold_16 this is Y chromosome

Scaffold_9 (+), Scaffold_14 (+) join, this is X chromosome

Scaffold_1 18.111-18121Mb should be moved to the start of the scaffold - this end issue is common across other scaffolds..
[icCarBano1.pretext.map.agp_1.gz](https://github.com/user-attachments/files/17313970/icCarBano1.pretext.map.agp_1.gz)

Scaffold_2 17.027-17.046Mb should be moved to the start of the scaffold, Scaffold_15 start-842kb (+) and Scaffold_4 8.718-9.253Mb (-) inserts @Scaffold_2 9.186Mb.

Scaffold_3 start-15kb should be moved to the end of the scaffold.

Scaffold_4 15.396-15.437Mb should be moved to the start of the scaffold.

Scaffold_5 15.374-15.386Mb should be moved to the start of the scaffold, scaffold_44_unloc_1 (-) and scaffold_28_unloc_1 (-) inserts @Scaffold_5 6.861Mb.

Scaffold_6 13.943-13.962Mb should move to the start of the scaffold.

Scaffold_7 scaffold_7 (-) inserts @Scaffold_7 7.497Mb

Scaffold_8 12.327-12.375Mb should move to the start of the scaffold.

Scaffold_10 scaffold_22_unloc_1 (+) joins to end Scaffold_10.

Scaffold_11 12.019-12.054Mb should move to the start of the scaffold.

Scaffold_12 break 5.51Mb. rejoin with Scaffold_17 as follows - Scaffold_12 5.51-11.679Mb (+), Scaffold_17 (+), Scaffold_12 start-5.51Mb (+).

Scaffold_13 start-28kb should move to the end of the scaffold.

Scaffold_15 break 7.125Mb. Rejoin with Scaffold_18, scaffold_47_unloc_1, scaffold_51_unloc_1 as follows - Scaffold_15 7.125-9.828Mb (+), Scaffold_18 (+), scaffold_51_unloc_1 (+), scaffold_47_unloc_1 (+), Scaffold_15 0.842-7.125Mb (+).

The following sequences also look to be contamination and should be removed:
scaffold_53
scaffold_59
scaffold_60
scaffold_61
scaffold_62
scaffold_63
scaffold_65
scaffold_66
scaffold_67
scaffold_68
scaffold_69
scaffold_70
scaffold_71
scaffold_72
scaffold_73
scaffold_74
scaffold_75
scaffold_76
scaffold_77

**Comment by Arno75** [comment]
Map file was genered with --mapq 0 for NormalRes.map and --mapq 10 for HighRes.map.

**Comment by Arno75** [comment]
Hello Jo,
I am in the process of making the modifications that you indicated. Everything seems logical to me, but I don't understand the modification concerning scaffold 7 : "Scaffold_7 scaffold_7 (-) inserts @Scaffold_7 7.497Mb".

**Comment by additive3** [comment]
Hi Arnaud, 

In your map you have chromosome scaffolds "Scaffold_" and unplaced scaffolds "scaffold_"

In this case rather confusingly, "s_7" is inserted into "S_7" which is why we usually change the chromsome scaffolds to SUPER_ :)

> Map file was genered with --mapq 0 for NormalRes.map and --mapq 10 for HighRes.map.

It looks very much like it is the other way round...

Best,
Jo

**Comment by Arno75** [comment]
_Map file was genered with --mapq 0 for NormalRes.map and --mapq 10 for HighRes.map.

It looks very much like it is the other way round..._

you are right, sorry I actually reversed the values

**Comment by additive3** [comment]
Could you please regen a normal res map with --mapq 0.
Thanks and best,
Jo

**Comment by additive3** [comment]
Many thanks, will check and comeback to you.

**Comment by additive3** [comment]
Hi Arnaud, 

Normal resoultion map confirms to me the changes I have proposed.
Let me know if you want to discuss anything.

Best,
Jo

**Comment by Arno75** [comment]
hello jo, 
I would like to understand one thing regarding the small parts of scaffolds that you would like to see put back at the beginning.
Exemple : "Scaffold_1 18.111-18121Mb should be moved to the start of the scaffold "
I would have been more convinced to tag them as haplotig because we see the cross diagram on the map and the drop in coverage. What do you think about ?

**Comment by additive3** [comment]
Hi Arnaud, 

Without looking I would suggest that these are telomere sequences, in each case there are distinct Hi-C contacts to the opposite end which when moved supprots that these are telomeric.

I note that these were all connected to the ends via a sequence gap, (Big assumption on my part, but only b/c we see this so frequently) I would guess this was caused by slight mis-breaking from overjoining by YaHS, b/c of the large "masked" centromere regions (all also gapped) which it is unable to join.

I'll add some images when I get the opportunity :)

Best,
Jo

**Comment by Arno75** [comment]
Hi jo ,
Here is the final map. 
https://www.genoscope.cns.fr/lbgb/bge/icCarBano7.pretext.map
(Please note, I added the scaffold corresponding to the genome of the mitochondria.)
Tell me if this is ok for you.

**Review by additive3 — APPROVED** [review]

**Comment by diegomics** [comment]
Thanks both! @Arno75 please start the ENA submission with the new fasta to save time while you regenerate the new PDF so we can merge this PR ;)

**Comment by diegomics** [comment]
Hi @Arno75 please remember to update the PR with the final PDF so I can merge it and release the reviewer 🙏

**Comment by ldemirdj** [comment]
Hi @diegomics, 

Arnaud is currently on vacation, but I’ll let him know to update the PR with the final PDF as soon as he’s back. 

Thanks for your patience!

Best, 

Lola

**Comment by Arno75** [comment]
sorry I forgot to give the final pdf
https://www.genoscope.cns.fr/lbgb/bge/icCarBano7_EAR.pdf

**Comment by diegomics** [comment]
Hi @Arno75 it looks great, bu please replace the PDF in the pull request :)

**Comment by diegomics** [comment]
Thanks, I will merge this ASAP (we are fixing a little thing with the bot)

**Pull request merged**
