### PR TITLE
Added xbArcNoae1

### PR DESCRIPTION
**Pull request by EmilieTeo**
## Assembly review request

- ToLID: xbArcNoae1
- Species: Arca noae
- Project: BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @EmilieTeo, thanks for sending the EAR of _Arca noae_.
I added the corresponding tag to the PR and will contact a reviewer ASAP.

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-07-16 09:23

All Eligible Candidates:

Github ID     | Full Name     | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
--------------------------------------------------------------------------------------------------------------------------
SarahPelan    | Sarah Pelan   | Sanger      | 1             | 2024-03-22  | Y      | N    | 1001          | 1051          
joannacollins | Jo Collins    | Sanger      | 1             | 2024-03-27  | Y      | N    | 1001          | 1051          
DomAbsolon    | Dom Absolon   | Sanger      | 1             | 2024-04-22  | Y      | N    | 1001          | 1051          
additive3     | Jo Wood       | Sanger      | 2             | 2024-06-15  | Y      | N    | 1000          | 1050          
tommathers    | Tom Mathers   | Sanger      | 2             | 2024-07-08  | Y      | N    | 1000          | 1050          
gitcruz       | Fernando Cruz | CNAG        | 1             | 2024-07-15  | Y      | N    | 1000          | 1050          
tbrown91      | Tom Brown     | IZW         | 9             | 2024-07-05  | Y      | N    | 993           | 993           

Selected reviewer: Sarah Pelan (SarahPelan)
The decision was based on:
- different institution ('Sanger')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1051)
- chosen based on oldest review and fewest reviews among the finalists
```

**Comment by diegomics** [comment]
Hi @SarahPelan, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 23-JUL-2024 at 09:25 CET.

**Comment by diegomics** [comment]
Time is out! I will look for the next reviewer on the list :)
Hi @JoannaCollins, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 30-JUL-2024 at 13:39 CET.

**Comment by JoannaCollins** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).
Let me know if you have any issues.

**Comment by EmilieTeo** [comment]
Hi @JoannaCollins and thanks a lot for your review

I applied most of the changes that you pointed out. Unfortunately I don't have the ALT assembly and I agree that the potential haplotypic duplications in SUPER_16 seem ambiguous, so I would leave them in. For the same reason I would also leave the unlocs of SUPER_19 as they are. We never used the primary option with hifiasm and always produce the partially phased assemblies, so I'm a bit curious, do you systematically generate the primary and alternate assemblies ? 

I also have some doubts regarding three of the haplotypic duplications :
- SUPER_5 @ 14.30Mb
- SUPER_5 @ 16.49
- SUPER_8 @ 7.37Mb
For those, even though I see the drop in coverage that you mentioned, I don't see any particular pattern indicating a haplotypic duplications so I'm not very confident about removing them. You have more experience than I do, so I'm wondering if you came to your conclusions solely based on the coverage or if I didn't manage to make out the specific pattern

Here are the regions in SUPER_5
image

And SUPER_8
image

Emilie

**Comment by JoannaCollins** [comment]
Hi @EmilieTeo,

Thanks for responding so quickly to the review comments. 

In the absence of having an ALT assembly to view I think it is absolutely sensible to leave issues raised for SUPER_16 and 19 as they are. In answer to your question, at the moment most of the assemblies that are coming through our pipeline are HIC phased assemblies that result in the production of a HAP1 and HAP2 assembly. Both haplotypes are then scaffolded and typically we merge the assemblies and curate in the merged pretext map in order to try and create the most complete haplotype for submission. If we have to use HIC from a different individual then a primary and alt assembly are produced.  More recently we have been scaffolding the alt in addition to the pri and producing both a map just for the primary and also for a merged pri/alt assembly in order that should we have issues resulting from significant haplotype variation we already have the merged pretext map available which significantly helps determine one haplotype versus the other.

Re the haplotype issues you highlight on SUPER_5 and SUPER_8. I was looking at both coverage and in the case of SUPER_5 @ 14.30Mb and SUPER_8 @ 7.37Mb (i think its not so clear with SUPER_5 @ 16.49) the typical parallel line motif shown due to the duplicated sequence. If they occur at a gap they are generally much easier both to spot and excise. I wondered if they were clearer to see on the map you were editing hence highlighting them as potential hap dups however It sounds like that is not the case. Looking again I agree that in this case it is better to leave the possible haps @ SUPER_5 @ 16.49 and SUPER_8 @ 7.37Mb as with the data we have it is not overwhelmingly clear what should be removed. With the hap @ SUPER_5 @ 14.30Mb I would use the coverage as a guide and remove from ~14.10-14.36Mb. 

Hope that helps,

I am away from the office now until Tuesday 6th August but I am happy to answer any further questions on my return. 

Best Wishes

Jo

**Comment by diegomics** [comment]
Hi @EmilieTeo, just following up on the status of this review. If you have finished implementing Jo's insightful comments, please regenerate the EAR so we can have a final check.
Thanks :)

**Comment by EmilieTeo** [comment]
Hi,

Sorry for the late reply, I was out of the office for a couple of weeks. 
Thank you very much for your reply and those information on the ALT assemblies, we'll have to try it out for next genomes.
I made the changes mentionned before and generated a new map and EAR report

Emilie

**Comment by JoannaCollins** [comment]
Hi Emilie,

I have rechecked the pretext map and i think this all looks good now :-). 

One thing I thought I it might be useful to mention (apologies for not metioning this before) is that generally we make a note of the regions where we see haplotypic inversions. We record these in the Genome notes that accompany our submissions. An example of which would be something like:

"Inversions between haplotypes are seen in the following locations: Chromosome 3 from 27.8 to 37.8 Mbp, Chromosome 9 from 26.9 Mbp to end, Chromosome 11 from 1.5 to 11.1 Mbp and Chromosome 13 from 19.5 to 27.6 Mbp."

I wondered if this information would be something that would be useful to add to the curators notes section of the EAR?

Best Wishes

Jo

**Comment by EmilieTeo** [comment]
Hi Joanna, 
Thank you for your review on this genome :-)
I added the information on the inversions between haplotypes in the curators notes of the EAR report

Emilie

**Comment by diegomics** [comment]
Hi Emilie, thanks for updating the EAR, all looks good on my end. @JoannaCollins, if you think this one is done, please approve it and I will merge it :)

**Review by JoannaCollins — APPROVED** [review]
Hi Emilie

Thanks for updating the curators note section with the inversion info, i think this is really useful for the end user :-).

I am now happy to go ahead and approve the assembly.

**Comment by diegomics** [comment]
Thanks @JoannaCollins for the review.
I will add a new reviewed species for you to the table after merging the PR ;)

Congrats on the assembly @EmilieTeo!
After the merging, you can [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission)

**Pull request merged**
