### PR TITLE
pre-curation EAR for fValHis1

### PR DESCRIPTION
**Pull request by talioto**
Species: Valencia hispanica
Taxa: Metazoa: Chordata: Actinopteri: Cyprinodontiformes: Valenciidae: Valencia
Project: ERGA-BGE
URL: https://genomes.cnag.cat/erga-stream/species/32/

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @talioto Thanks for the EAR! Review will start asap :)

**Comment by tbrown91** [comment]
Hi @talioto 
In general, looking very good. You listed the sex as ZW, so I was trying to look for these in the EAR. Do you think maybe the syntenic regions are merged in scaffold 20? 
image

My only slight concern is maybe some of the sex chromosome is getting squashed out during the assembly collapse of nextdenovo. There appears to be some remaining kmers in the reads not included in the assembly at about 30/35X coverage. 
image

I suspect you know best about the limitations of these pseudo-haplotype assemblers and suspect this is still one of the best ONT-based fish assemblies out there.
I will approve my review, let me know if anything I've said is unclear.

Tom

**Review by tbrown91 — APPROVED** [review]
Looking good

**Comment by diegomics** [comment]
All EBP metrics are met and it looks very good. Agree with Tom that Nextdenovo's collapsed assembly may be the cause of the two things he is pointing out. What can you tell us about that? This is the first ONT-based assembly we have seen here, and your feedback is super welcomed in this testing phase.
@talioto I'll wait for your answer to approve this assembly and merge the PR

**Comment by diegomics** [comment]
One important thing unrelated to the assembly: Please modify the pull request to merge it with the devel branch. Since this is a testing phase, we always work in the devel branch. The branch fValHis1 in your repo should be based on the devel branch, and you should create a PR to merge with the ERGA-consortium/EARs devel branch. This is only for the testing phase and soon will be all in the main.

**Comment by talioto** [comment]
In response to all the comments above:

1. Regarding pseudohalploid assemblies, this is typical that roughly half of the kmers in the heterozygous peak will be missing in the assembly. This has little to do with sex chromosomes, although the height of the het(or hemi) peak will be higher with dimorphic sex chroms. In this case (and for MANY fish) the sex chromosomes are homomorphic. Unless we do phased assemblies (and I would like to, but this is still not standard across the field, and I don't have time to develop a new assembler;-), this is bound to happen. BTW, I listed it as ZW because it is a female sample and we requested the heterogametic sex. It is actually unknown to me whether it is XX or ZW.
2. Regarding the main vs devel branch, I was going to do it on the devel branch, but saw in the pull.gif that it was done on the main, so I switched to pulling vs. the main branch. I will try to fix this. In the meantime, please fix your documentation!

**Comment by diegomics** [comment]
Thanks for the replies.

Warning added in the readme until we move out of testing.

I see that you are asking to merge to the devel branch now, nice. Still, I think that your branch fValHis1 should be based on devel, not main.

**Comment by talioto** [comment]
OK. If you want I will submit a new pull request.

**Comment by diegomics** [comment]
Ok. Submit a new PR. I will close this PR and link the new one to this discussion to keep track of this discussion. Thanks Tyler, and sorry for the inconvenience of the testing phase :)

**Pull request closed without merging**
