### PR TITLE
xgPhyFlav1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
Assembly review request
---

ToLID: xgPhyFlav1

Species: Phyllidia flava

Project: ERGA-BGE

Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @fcamara7, thanks for sending the EAR of _Phyllidia flava_.
I added the corresponding tag to the PR and appointed @tbrown91 as the [assignee](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) to supervise.
I will contact a reviewer ASAP.
:ear:

**Comment by diegomics** [comment]
Hi @DomAbsolon, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 25-MAR-2024 at 14:50 CET.

**Comment by DomAbsolon** [comment]
Yes

From: Diego De Panis ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Monday, 18 March 2024 at 13:51
To: ERGA-consortium/EARs ***@***.***>
Cc: Dominic Absolon ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] xgPhyFlav1 EAR (PR #29) [EXT]


Hi @DomAbsolon [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DomAbsolon&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=TtcyhxFtjf_191NADQOHlJucJ3CVQXASKOiUQ_Kim9QKX5-YIBWKdrafh7T7ADaT&s=ToUglMLJArrVpDjPYYr-uvdknomvaJ3pQkEONPWeKzQ&e=>, do you agree to review this assembly?
Please reply to this message only with Yes or No by 25-MAR-2024 at 14:50 CET.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_29-23issuecomment-2D2003971619&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=TtcyhxFtjf_191NADQOHlJucJ3CVQXASKOiUQ_Kim9QKX5-YIBWKdrafh7T7ADaT&s=U3yl9NXB-37FoV8HySolUcJSMSCblDdyx_NmWAdk3I0&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BCJBKIEWTO2MRLQ427MUP7TYY3WNNAVCNFSM6AAAAABEM6P6V6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBTHE3TCNRRHE&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=TtcyhxFtjf_191NADQOHlJucJ3CVQXASKOiUQ_Kim9QKX5-YIBWKdrafh7T7ADaT&s=674gCeFftgb6ztZZrN4UuacsZZ9tCMsS73N54Hc8MzY&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Review by DomAbsolon — CHANGES_REQUESTED** [review]
The following changes should be made to this assembly: 

SUPER_1 - region from 131,773 - 134,789 Kbp should flip
SUPER_3 - region from 244,465 - end should be broken off and inserted at 238,607 Kbp
SUPER_7 - SUPER_7_unloc should place at gap 32,015 Kbp
SUPER_8 - region from 1,913 - 4,001 should flip
SUPER_10 - region from 20,125 - 22,999 Kbp should flip, region from 71,976 - 73,716 should flip and place at 75,746 Kbp
SUPER_11 - region from 92,160 - end should flip and place at 89,260 Kbp. 

Note that there are a number of heterozygous inversions evident in this assembly. You may wish to indicate these in the genome note upon submission. An example of such a region is SUPER_11 ~3,247 - 31,347 Kbp. Also note there appears to be missing data from the assembly evidenced by blunt joins in the HiC data. These are presumably centromeric regions not captured by the sequencing technology. 

Finally, when creating these Pretext maps, run with --nosort so the map is not sorted by length. This ensures the any unlocalised scaffold remain next to their associated chromosome.

**Comment by tbrown91** [comment]
Thank you @DomAbsolon for your thorough review of the genome. A couple of the inversions you have mentioned look to involve cutting contigs - is this something you would always do without hesitation? Perhaps I am too much on the conservative end and don't like doing this unless I'm sure.

@fcamara7 was this pretext run in the highRes mode? I don't really know how Dom was able to see everything at this resolution. Can you please have a look at the changes Dom has suggested, regenerate the pretext map and add a new EAR to your pull request?

Many thanks both

**Comment by fcamara7** [comment]
Thanks for reviewing our assembly and suggestions @DomAbsolon !, I will try to address them in the course of next week after conferring with the other members of our group.

No we don’t currently use the HiRes mode version of Pretext @tbrown91 . I suppose that would involve installing TreeVal as the version is not available elsewhere correct? Will look into that to...

Thanks!

Francisco

**Comment by diegomics** [comment]
Hi @fcamara7 
Please use [this flag](https://github.com/sanger-tol/PretextMap?tab=readme-ov-file#new-option-version-019) for HiRes in pretext

**Comment by fcamara7** [comment]
> Hi @fcamara7 Please use [this flag](https://github.com/sanger-tol/PretextMap?tab=readme-ov-file#new-option-version-019) for HiRes in pretext

Perfect @diegomics thanks for the information, we will try that.

**Comment by DomAbsolon** [comment]
Hi @tbrown91, generally yes, especially when both hic and the ont is from the same sample. Contiging errors do happen so if we feel the HiC data suggests the change, we will make it.  Let me know if there's anything you'd like me to explain in more detail!

**Comment by gitcruz** [comment]
@tbrown91 In order to run the hires pretext version I am trying to install a docker image sanger-tol/treeval or sanger-tol/curatiopretext. However I did not find it in their [github repo](https://github.com/sanger-tol/treeval/tree/main?tab=readme-ov-file):

Perhaps I am looking at the wrong place ...Could you point us to it?

Thanks,
Fernando

**Comment by gitcruz** [comment]
Hi again, 

I created a hires version for another genome and I can open the pretext file with v0.2.5. It seems that teh hires map gets rid of the background signal and shows more Kbp/Texel (helps with the shortest scaffolds). Maybe I'm wrong and there is no need of using an specific "hires" version to visualize the hires maps. 

Please let me know if I'm right or  wrong.

Thanks

**Comment by tbrown91** [comment]
I have PretextMap v0.1.9 installed via conda and PretextView v0.2.5 installed from source. I don't think there is anything special, just using the --highRes argument to generate the .pretext. This is more to help the reviewers in the future than anything profound

**Comment by DomAbsolon** [comment]
Hi @gitcruz. You are right in that the high res maps contain a smaller amount of bases per texel (the number of texels is doubled). Depending on the size of the genome and the amount of HiC signal, long range contacts can be diluted to the point that they can no longer be seen compared to the default resolution. However, they provide much better detail in most cases. At Sanger by default we make one of each for every genome and the curator will select the resolution which allows for the best curation. That said, files sizes for high res maps are much larger and so you can quickly clog up your storage. Just something to be aware of. Hope that makes sense

**Comment by gitcruz** [comment]
Thanks guys,

In that case, I think we can also upload one of each (default and hires) for our curated genomes in our shared one drive folders. This way the reviewer can choose.

And  we will also upload a "default" or "hires" pretext with multimmapings upon request in case the reviewer asks.

Best,
Fernando
P.S. @DomAbsolon true highres means less Kb per texel, but you understood what I meant. I just edited above comment to avoid confusions

**Comment by gitcruz** [comment]
Hi @tbrown91, 
@fcamara7 will probably pass you the highres map of _Phyllidia flava_ tomorrow. 
Best,
F

**Comment by diegomics** [comment]
Hi @fcamara7
An important issue to fix on this PR:
The folder structure is incorrect: it is placed in the root directory and should be inside the Assembly_Reports folder. Please fix it, the EAR cannot be merged otherwise (the same issue in mApoAgr2 EAR #28)
Thanks :)

**Comment by fcamara7** [comment]
@diegomics think both issues are fixed now?

**Comment by fcamara7** [comment]
We have made the modifications as suggested by @DomAbsolon . This time around I am sharing the HiRes (unsorted) Pretext map. Hope this suffices and that there are no other mistakes in the uploading of the new pdf...

**Comment by tbrown91** [comment]
Thanks @fcamara7 The pdf and pretext map look to be correct.

@DomAbsolon Can I ask you to please have another look through and to make sure there are no major errors? It looks like this is has been a real challenge to get together with a lot of heterozygous inversions clouding the signal, so we are not expecting a beautifully perfect picture

**Comment by DomAbsolon** [comment]
I'm not sure if it's me doing something wrong but I don't seem to be able to download the new map

**Comment by tbrown91** [comment]
Can you access this link?
https://ccnag-my.sharepoint.com/:u:/g/personal/tyler_alioto_cnag_eu/EZ-FnWksBhlAico3XdOe3P8BbGLoVtx7CtLKA5CxAhd8eg?e=lwPg9T

Unfortunately you have to download the pdf in order for the link to render properly - github pdf is not fully funcitonal

**Review by tbrown91 — APPROVED** [review]

**Comment by tbrown91** [comment]
Thanks @DomAbsolon and @fcamara7 It's great to see another genome on its way to ENA. Good job

**Pull request merged**
