### PR TITLE
mCriCri2 EAR

### PR DESCRIPTION
**Pull request by gitcruz**
## Assembly review request

- ToLID: mCriCri2
- Species: Cricetus cricetus
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
ok

**Comment by CaroB-M** [comment]
yes

**Comment by CaroB-M** [comment]
Hello @gitcruz and @diegomics 
I have very few remarks : 
SUPER_2[58.60 Mbp] to SUPER_2[67.83 Mbp] to be inverted (looks better if inverted)
scaffold_28 can be tagged as unloc of SUPER_4
scaffold_35 can be tagged as unloc of SUPER_6
The map looks good!
Best
Caroline

**Comment by gitcruz** [comment]
Hi @diegomics and @CaroB-M 

This is the link to the latest save_state: [](https://ccnag-my.sharepoint.com/:u:/g/personal/tyler_alioto_cnag_eu/EWXrzgxM49ZEjRQrEYTJrX8BOesgTCuzA5lSPgqLtt5C3w?e=fkRaqD)

**Comment by gitcruz** [comment]
Wait! 

I missed @diegomics comment and I agree, scaffold_34 can be tagged as unloc of SUPER_6.

I'll fix this and post the link again asap.

Thanks

**Comment by diegomics** [comment]
Looking great! Please @CaroB-M approve the review if you don't have any other comments :)
@gitcruz After the approval, generate the fasta and proceed with the ENA submission. You can generate the new PDF in the meantime to save time. I will merge the PR once the new PDF is updated ;)

**Comment by CaroB-M** [comment]
it seems that a very little contig as been painted as scaffold_10

**Comment by CaroB-M** [comment]
and the end of the chr Y tagged as unloc

**Comment by gitcruz** [comment]
Yes, this was present in the original pretext map...It has strong contacts
with the Y.

What do you think?

**Comment by talioto** [comment]
I've made the two fixes. piece of SUPER_1 ended up as Scaffold_10 moved back to SUPER_1. the unloc piece of Y is now localized.

Here's the [savestate](https://ccnag-my.sharepoint.com/:u:/g/personal/tyler_alioto_cnag_eu/EWQama2oy0RFjdKD6m7uDfEBJXqLgWzjEIBdWhdw2huMkQ?e=RbGxyh).

**Comment by talioto** [comment]
@CaroB-M , please approve and @diegomics , merge when you can. I will go ahead and prepare the submission to ENA. first have to submit the reads. oops!

**Comment by diegomics** [comment]
I don't think the PDF will change a lot between the original and the final version (gfastats and merqury should throw the same numbers), maybe a new BUSCO run can get something else based on the inverted region?

**Review by CaroB-M — APPROVED** [review]

**Comment by diegomics** [comment]
Hi @gitcruz please don't forget to update the PDF so we can merge this and release the reviewer (only gfastats, merqury and busco for the curated assembly should be updated)

**Comment by gitcruz** [comment]
Hi @diegomics,

Just updated the EAR with the stats for the approved assembly.

Please go ahead with merging the PR.

Thanks,
Fernando

**Comment by gitcruz** [comment]
Hi @diegomics, should I delete the branch for all the merged PRs I've done so far? I seems convenient.
Thnx.

**Comment by diegomics** [comment]
Yep, you can delete the branch :)

**Pull request merged**
