### PR TITLE
rHemHip1 EAR

### PR DESCRIPTION
**Pull request by gitcruz**
## Assembly review request

- ToLID: rHemHip1
- Species: Hemorrhois hippocrepis
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by additive3** [comment]
Ok


From: "erga-ear-bot[bot]" ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Monday 4 November 2024 at 14:51
To: ERGA-consortium/EARs ***@***.***>
Cc: Jo Wood ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] rHemHip1 EAR (PR #112) [EXT]


Hi @additive3 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_additive3&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=McukdzNsXVTFsBZoOYrKU_ifC8Tw0zzTrPA35PzTM0iVXXw6pewnBGwQ9BZGbvUI&s=rmoK8vZeEDIsgsQCLwWDt1YTPfjEwU7mMfmp9WhY4mY&e=>, do you agree to supervise [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_wiki_Assignees-2Dsection&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=McukdzNsXVTFsBZoOYrKU_ifC8Tw0zzTrPA35PzTM0iVXXw6pewnBGwQ9BZGbvUI&s=oqNxGfxRkTCxxLkRGNnJpJBDvmrKURoZ8n1CkZSQIUQ&e=> this assembly?
Please reply to this message only with OK to give acknowledge.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_112-23issuecomment-2D2454919733&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=McukdzNsXVTFsBZoOYrKU_ifC8Tw0zzTrPA35PzTM0iVXXw6pewnBGwQ9BZGbvUI&s=rGYGfQ2oNmvyKBta8kXYa4wjoxFGYDntcq01F4MbFuQ&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEFJV4OWTMHWWMLZMTIX32DZ66CXZAVCNFSM6AAAAABRENY7OKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJUHEYTSNZTGM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=TUaG6OqjPfI1I0rzJIbKqE8Tjv85ynPYIkNbCjRS2SI&m=McukdzNsXVTFsBZoOYrKU_ifC8Tw0zzTrPA35PzTM0iVXXw6pewnBGwQ9BZGbvUI&s=PfhBuAyJpQ47zUtLJA0PxlnFKOvV-qlrqAEho5yh6Pg&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by auryjm** [comment]
Yes

**Comment by auryjm** [comment]
Hi @gitcruz, 

Congratulations on this high-quality assembly! 

The ONT assembly looks highly contiguous, which may have facilitated the manual curation. 

The W chromosome looks challenging to organize, and I’m curious if the assembly would have been improved using PacBio. Maybe @additive3 has some insights about W chromosomes in snakes. Anyway, I just found a few issues and proposed an organization for the W chromosome, but if the convention is mainly to keep a single contig and designate others as unlocalized, I’m also comfortable with that.

- Move SCAFFOLD_52 to SUPER_1 @ 40.00 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_51 to SUPER_1 @ 138.30 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_56 to SUPER_1 @ 275.70 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_53 to SUPER_1 @ 334.78 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_46 to SUPER_1 @ 341.91 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_70 to SUPER_1 @ 353.18 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_54 to the end of SUPER_1.
- Move SCAFFOLD_67 to SUPER_2 @ 36.63 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_48 to SUPER_2 @ 159.18 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_59 to SUPER_3 @ 8.62 Mb: coverage is low, could be a haplotig?
- Move SCAFFOLD_69 to SUPER_Z @ 141.28 Mb: coverage is low, could be a haplotig?
- W_unloc_33 and W_unloc_32 are not positioned at the end of SUPER_W.
- Move SCAFFOLD_38, SCAFFOLD_55, SCAFFOLD_58, and SCAFFOLD_42 as W_unloc.

In the meantime, I've also uploaded the savestate to your repository.

Jean-Marc

**Comment by gitcruz** [comment]
Hi @auryjm,

Thanks for your thorough review and the savestate upload!!!!

I agree that all these scaffolds  previously unplaced are actually haplotigs (intersetingly they often seem to be placed in centromeric regions). 

Thanks for catching the W_unloc_33 and W_unloc_32, they might have scaped to  the painting.

I'll start from your savetate and produce a new fasta. Once it's done I will recompute the stats and upload a new EAR.

Merci beaucoup!
Fernando

**Comment by gitcruz** [comment]
Dear @auryjm, 

I uploaded the final EAR with all proposed changes. Could you have a final look and approved this EAR?

Once it's done, @additive3 could you please merge the PR so we are got to go with the ENA upload?

Thanks,
Fernando

**Comment by auryjm** [comment]
Sounds good to me ! Congratulations !

**Review by auryjm — APPROVED** [review]

**Comment by gitcruz** [comment]
No worries.
Thanks

**Comment by additive3** [comment]
All looks fine. Its a shame that you don't produce 2 haplotype assemblies as ~20Mb of W is collapsed into Z.

**Pull request merged**
