### PR TITLE
ibLobSubt1 EAR (final report after curation)

### PR DESCRIPTION
**Pull request by fcamara7**
## Assembly review request

- ToLID: ibLobSubt1
- Species: Loboptera subterranea
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by fcamara7** [comment]
@diegomics we have modified the EAR report as suggested and re-uploading it. We will also in the process of uploading the assembly to the ENA.  xcStiArct is already submitted and I will update the report today as well.

**Comment by diegomics** [comment]
Hi @fcamara7 I'm closing this as you should not open a new PR, just update the one that is already opened!

**Comment by fcamara7** [comment]
> Hi @fcamara7 I'm closing this as you should not open a new PR, just update the one that is already opened!

Oops, sorry. I will do that.

**Comment by diegomics** [comment]
All good, we are not braking anything :)
It's really great that we can merge ibLobSubt1 and xcStiArct soon so we can release the reviewers to be called again for another EAR. Thanks a lot!!

**Pull request closed without merging**
