### PR TITLE
ibLobTrog EAR

### PR DESCRIPTION
**Pull request by fcamara7**
## Assembly review request

- ToLID: ibLobTrog1
- Species: Loboptera troglobia
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
OK

**Comment by diegomics** [comment]
Unexpected behaviour from the bot here. @andar27 should not have been called since was already called in another PR. @arash77 can we take a look at this?
Please @andar27, ignore this PR, you were called first on the PR of ibLobCana1. I will manually fix this (apologies for the inconvenience, @fcamara7)

**Comment by diegomics** [comment]
OK

**Comment by CaroB-M** [comment]
Yes

**Comment by CaroB-M** [comment]
Hi @fcamara7 
This assembly looks very good. I don't see any changes to be made. Some regions are difficult to appraise, probably heterozygous regions. 
Best 
Caroline

**Comment by fcamara7** [comment]
> Hi @fcamara7 This assembly looks very good. I don't see any changes to be made. Some regions are difficult to appraise, probably heterozygous regions. Best Caroline

Thanks for the review and comments @CaroB-M , what's your call @diegomics ?

**Comment by diegomics** [comment]
I'm taking a look at both Blattodea EARs you guys sent. I'll try to finish today.
Just very quickly, scaffold_32 may be a SUPER_4 unloc. Can you check this and others?
Will come back asap!

**Comment by diegomics** [comment]
Related to Tom's comment, my concert with this EAR is related to haploid number (btw, nice catch that flipped segment, I agree). I noticed that ibLobCana has 17 chroms, while this sp has 14. I thought maybe they were a couple fused and weak contacts between arms are indeed two different chromosomes with higher interaction, but ibLobSubt also shows this n. Have you tried a dotplot with d-genies or something like that between these three species?

**Comment by gitcruz** [comment]
Hi @tbrown91, 

Just let me chime in. The kmer plot you are showing actually corresponds to the ibLobCana1  approved assembly.  WRT the kmer plot IMO both the separation of lines between the absent kmers and the small bump of them beneath the homozygous peak correspond with the presence of artificial kmers at the boundaries of two different haplotypes.  This is inherent to the nextdenovo assemblies for this highly heterozygous species and not in the flye ones. The reason is that nextdenovo is more aggressive collapsing haplotypes, and therefore producing a more contiguous assemblies. In order to do so builds a consensus of pileup of overalpping reads, thus some of the consensus kmers are "artifactual" thus considered as errors by merqury because they do not exist in the reads (is mixed of kmers that occur at haplotype switch). It seems that the polishing with Hypo fixed some but not all of the errors, specially these ones.

Although kmer completeness and QV were slightly lower than in our flye assemblies, we decided to curate the nextdenovo derived assemblies because they showed much lower levels of artificial dups, higher contiguity and BUSCOs. So this resulted in a better reference under the EBP standards.

WRT @diegomics  comment about the chromosome number, is hard to say as the telomere peaks detected by tidk are few and they always fall at the terminal position of 5-6 superscaffolds for these 3 species. Out of curiosity, we will run a WGA of ibLobTrog1 (n=14) using ibLobCana1.1 (n=17) as reference. We'll see if we find anything special there. Both species were scaffolded using a similar number of HiC million pairs (ibLobTrog 68.2 million vs. ibLobCana 79.2 million). We will also align troglobia against ibLobSubt1.1 (n=14). Based on the maps I'd speculate that maybe _L. canariensis_ experienced some fissions respect to the ancestral  species of this group. Hard to tell if it's a biological fact without a proper karyotype for each of them. 

Thanks,
Fernando

**Comment by fcamara7** [comment]
> I'm taking a look at both Blattodea EARs you guys sent. I'll try to finish today. Just very quickly, scaffold_32 may be a SUPER_4 unloc. Can you check this and others? Will come back asap!

@diegomics @tbrown91 I have made the suggested changes. Flipping the beginning of Super_9 does improve the map, especially along the diagonal, thanks! As for scaffold_32 we must have missed it and I put it as an unloc of 4 as suggested. I moved a few other scaffolds as well but in general we do not tend to move scaffolds smaller than 100 Kbases unless the signal is quite strong. I have a save state that reflects these changes (before painting)

**Comment by gitcruz** [comment]
Hi @diegomics, 

We'll post the alignments and our thoughts here. 

Cheers

**Comment by gitcruz** [comment]
Hi @diegomics,

We have run minimap2 alignments between these 3 Blattodea species using 1% divergence in minimap2 (asm10). The Dgenies results can be visualize here for few days or weeks (note that last tolid refers to the target assembly): 

1. [ibLobTrog1_curated_vs_ibLobSubt1.1](https://dgenies.toulouse.inra.fr/result/ibLobTrog_curated_vs_ibLobSubt11): the two n=14 species being mostly collinear, except for some inversions and rearrangements in the long arm of SUPER_1 (mostly translocations).
2. [ibLobCana1.1_curated_to_ibLobSubt1.1](https://dgenies.toulouse.inra.fr/result/ibLobCana11_curated_to_ibLobSubt11?)
3.[ibLobTrog1_curated_vs_ibLobCana1.1] (https://dgenies.toulouse.inra.fr/result/ibLobTrog_curated_vs_ibLobCana1)

These alignments and results  will be stored for longer time inside the shared folder for [ibLobCana1.1 EAR review](https://ccnag-my.sharepoint.com/personal/tyler_alioto_cnag_eu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Ftyler%5Falioto%5Fcnag%5Feu%2FDocuments%2FAAT%2FCuration%2FERGA%5FGenomes%2FibLobCana1&ga=1).

Observations:

A- The two n=14 species (ibLobTrog and ibLobSubt) are evolutionarily closer. Despite of the inversions of some segments they are mostly collinear for all "chromosomes" except for Troglobia's SUPER_1 were I think that several rearrangements occurred involving a fussion (SUPER_7 and  SUPER_10  consecutively align at 3-127Mb and 127-287Mb). But we do not see in the contact map any issues to break this SUPER. Because the second alignment spans from the long arm right after a "putative centromere".

B- The ibLobSubt X aligns to ibLobTrog's SUPER_6  and ibLobCana's SUPER_4. Consistently, the mentioned SUPER_6 and SUPER_4 also align "well".


SUPER_X_ibLobTrog_curated_to_ibLobSubt1 1


map_ibLobCana1 1_to_ibLobSubt1 1_SUPER_X

C- Consistently, SUPER_6 of Troglobia shows a coverage drop and @fcamara7 told me that we probably forgot to tag it as X.

D- Sequence Identity suggest that ibLobCana, with n=17, diverged long ago from the other two species (n=14). Thus the long divergence time explains their different chromosome number.

**Conlusions:**
- ibLobTrog: @fcamara7 will do the previously suggested edits and paint SUPER_6 as X.

- ibLobCana1: despite being already approved, I will tag SUPER_4 as X before ENA upload. Please let me know if you want me to mention this in a new version of the EAR and I can forward it to you to change it in the main branch.

Thanks
Fernando

**Comment by diegomics** [comment]
Thanks guys for the work. Please @CaroB-M, approve if you are happy with the review. There is no need to regenerate the contact map or the EAR (I don't think we'll see a change on gfastats or BUSCO metrics based on the SUPER 9 flip since you have a gap there already)

**Comment by gitcruz** [comment]
Great News! Merry Christmas to Every One in this conversation! Feliz
Navidad! Feliz Natal!

**Comment by CaroB-M** [comment]
Hello! Thanks @gitcruz and @fcamara7 for the additional analysis. 
Merry christmas! Feliz navidad! Joyeux noel!

**Comment by diegomics** [comment]
Nice, we can have this one as an early Christmas present. Please approve PR @CaroB-M if there is nothing else you would like to add :)

**Review by CaroB-M — APPROVED** [review]

**Comment by diegomics** [comment]
Thanks all, merging now. Frohe Weihnachten! 🎅

**Pull request merged**
