### PR TITLE
Assembly review request for ddcitcolo1

### PR DESCRIPTION
**Pull request by gkanogiannis**
## Assembly review request

- ToLID: ddCitColo1
- Species: Citrullus colocynthis
- Project: ERGA-Satellite
- Affiliation: International Center for Biosaline Agriculture (ICBA)

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @gkanogiannis, thanks for sending the EAR of _Citrullus colocynthis_.
I added the corresponding tag to the PR and will contact a supervisor and a reviewer ASAP.

**Comment by tbrown91** [comment]
Hi @gkanogiannis 

I don't know if you curated the hap2 (I don't think everyone does). But there is a small inversion at the end of scaffold_10 where the telomere has been placed inside the chromosome:

image

It should be a pretty quick fix to move the section 15.3Mb-19.5Mb to the end of the scaffold and invert the section 19.5Mb-25Mb. The hap2 is also missing quite a bit of sequence from scaffold 11, which is also visible in the kmer spectrum.

The hap1 on the other hand looks like a very good assembly. Assuming this is the reference you annotated and submitted, I'm happy to approve this, as long as we consider the hap2 and "alt" assembly.

**Review by tbrown91 — APPROVED** [review]

**Comment by gkanogiannis** [comment]
> Hi @gkanogiannis
> 
> I don't know if you curated the hap2 (I don't think everyone does). But there is a small inversion at the end of scaffold_10 where the telomere has been placed inside the chromosome:
> 
> image
> It should be a pretty quick fix to move the section 15.3Mb-19.5Mb to the end of the scaffold and invert the section 19.5Mb-25Mb. The hap2 is also missing quite a bit of sequence from scaffold 11, which is also visible in the kmer spectrum.
> 
> The hap1 on the other hand looks like a very good assembly. Assuming this is the reference you annotated and submitted, I'm happy to approve this, as long as we consider the hap2 and "alt" assembly.

Hi @tbrown91, great catch. I am glad that you indeed downloaded my pretext maps and thoroughly investigated them.

Correct, I did not spend too much time in curating the hap2, other than the rapid-curation pipeline.

I concentrated on the hap1, that was the one I annotated and eventually submitted.

**Comment by diegomics** [comment]
Hi @gkanogiannis
Hap1 looks good. In addition to what @tbrown91 pointed out, I also in the hap2:
. Scaffold 1 is quite large compared with the one from hap1. Also, I see a discontinuity in the contact signal @ 29,345Kbp that colocalises with telomere and gap signals. Are the scaffolds 1 and 2 fused?
. There is also an off-terminal region telomere signal @ 18,100 in scaffold 9, together with a gap. It may be a telomere-telomere misassembly.
The interaction signal is not too strong in the pretext files, this may be because of the mapping parameters (?). Check [Tom's nice snakemake pipeline](https://workflowhub.eu/workflows/795) to produce the plots if you are not aware of them ;)
I agree, if Hap2 is an alt assembly, all good. Congrats!

**Review by diegomics — APPROVED** [review]

**Comment by gkanogiannis** [comment]
> Hi @gkanogiannis Hap1 looks good. In addition to what @tbrown91 pointed out, I also see in the hap2: . Scaffold 1 is quite large compared with the one from hap1. Also, I see a discontinuity in the contact signal @ 29,345Kbp that colocalises with telomere and gap signals. Are the scaffolds 1 and 2 fused? . There is also an off-terminal region telomere signal @ 18,100 in scaffold 9, together with a gap. It may be a telomere-telomere misassembly. The interaction signal is not too strong in the pretext files, this may be because of the mapping parameters (?). Check [Tom's nice snakemake pipeline](https://workflowhub.eu/workflows/795) to produce the plots if you are not aware of them ;) I agree, if Hap2 is an alt assembly, all good. Congrats!

Dear @diegomics muchísimas gracias! This is correct, I did not spend too much time with hap2, as I was already satisfied with hap1 and had heavily invested time on annotating it.

Regarding HiC. I did a thorough investigation on the issue (weak interaction signal). Mapping wasn't the issue and had followed the best practices. The issue was that my predecessors had selected to send the sample for sequencing in one of their home country center, that used Proximo kit from Phase Genomics, but managed to screw it. Data came back with 80% duplication. After countless emails with their "specialists", they admitted that they did 12 PCR cycles (because DNA concentration wasn't enough), when protocol suggested 8 as maximum. Plus the remaining 20% data was mainly from intra-contig interactions, and hence signal is mainly around diagonal.

Again thank you and @tbrown91 for your time and valuable insights.

**Pull request merged**
