### PR TITLE
xcStiArct1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
## Assembly review request

- ToLID: xcStiArct1
- Species:  Stigmatoteuthis arcturi
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Ok

**Comment by diegomics** [comment]
@fcamara7 I edited the PR body. Please, only use the provided template

**Comment by andar27** [comment]
yes

**Comment by andar27** [comment]
Hi @fcamara7 
Generally, I think it looks good. However, I noticed two things :

SUPER_8  88..06-90.14 Mb should be placed at the beginning of SUPER_8
SUPER_20 0-28.46 Mb should be inverted ? (the telomere will be in the middle, but I think the contacts look better.)

Thanks, 
Adama

**Comment by diegomics** [comment]
Hi @fcamara7 
Cool assembly this one, nice! Please check and comment on the review of @andar27
My comments:
Very helpful curator notes and pipeline information, much appreciated!!
You have several unloc, it would be **really** helpful if they were placed at the beginning or the end of the respective scaffold accordingly.
Also, you have a lot of chaff at the end, did the assembly metrics worsen if purging? Just wondering, the BUSCO dup is low, not that you need to improve that.
SUPER_19 @49,6: Do you think it belongs there?

**Comment by diegomics** [comment]
Also, out of curiosity, BUSCO mollusca db was not good?

**Comment by fcamara7** [comment]
> Very helpful curator notes and pipeline information, much appreciated!!
> You have several unloc, it would be **really** helpful if they were placed at the beginning or the end of the respective scaffold accordingly.
> Also, you have a lot of chaff at the end, did the assembly metrics worsen if purging? Just wondering, the BUSCO dup is low, not that you need to improve that.
> SUPER_19 @ 49,6: Do you think it belongs there?

@andar27 we made the suggested changed and the pretext contacts do look better, thanks for the insight! 
@diegomics well spotted! We moved that contig to SUPER_3 as an unloc.

Since our cluster is having major problems and we are in a rush to meet the end of October deadline we are only sharing the pretext plus the appropriate save states directory (below). Let me know if you have access and can see the changes. If you approve we will regenerate the appropriate pretext, produce the new stats and create a new blobtools report on the approved assembly plus a final EAR report:

https://ccnag-my.sharepoint.com/:f:/g/personal/tyler_alioto_cnag_eu/EmKbPuhek_RJp9pinjPGnKoBLkTSwardfMLO6VK61CJVoQ?e=fxpLhE

**Comment by andar27** [comment]
Thanks @fcamara7, sounds good to me!

**Comment by diegomics** [comment]
Hi @fcamara7
Thanks for implementing the changes in the savestate. Btw, we are going to implement this proceeding of sharing savestates when possible in the PR chat to expedite the process, regenerating the EAR only when all is agreed. I will update the wiki in the coming days with all the changes that we are implementing.
I'm not sure about the SUPER_20 flip at the beginning. Does it really look better? Is this also the consensus from the other curators in CNAG? It doesn't look clearly better for me, and now the Telo signal off-terminal. Please let me know what conclusion you reach about this at CNAG so we can close this review.

**Comment by fcamara7** [comment]
@diegomics can you confirm that you are fine with the changes as well? We would like to upload this one to the ENA asap. I will subsequently send you a new EAR report. I am just waiting for the HiC remapping to finish but as I mentioned before we have been having major cluster issues as of late.

**Comment by diegomics** [comment]
I'm only not sure about the SUPER_20 flip, so I leave this to you guys at CNAG. Please reply with your decision so @andar27 can approve

The proceeding will be as follows (I'm updating the wiki with all this):
. You can opt to share the savestate to speed up the process
. If that's the case, then the reviewer can approve the PR based on the savestate, and you can upload it to ENA
. The PR will be merged only when the EAR is regenerated

**Comment by fcamara7** [comment]
> 0-28.46 Mb

Thanks @diegomics ! I looked at @andar27 suggestion with @talioto and he agreed as well so we will go with that. By the way, we believe the update to the EAR review protocol is positive and will reduce some overhead. As for this particular case the HiC remapping should be done today and we will resubmit the EAR report by tomorrow at the latest. In the mean time we will work on submitting the assembly to the ENA as well. Thanks to both of you yet again for the review and insights.

**Comment by diegomics** [comment]
Nice, thanks guys. @andar27 please approve the PR if no further comments

**Comment by fcamara7** [comment]
@diegomics I surmise he already did with his comment after I sent the link to the pretext and save states but perhaps I misunderstood him(?)

**Comment by diegomics** [comment]
Yes, but the reviewer needs to **approve**! Until then...
Please @andar27, click on the green buttons `Add your review` and then in `Review changes` to approve

**Review by andar27 — APPROVED** [review]

**Comment by diegomics** [comment]
Thanks! @fcamara7 you are good to go to upload this one to ENA, please regenerate the pdf so I can merged the PR and release the reviewer. Nicely done @andar27 !

**Comment by fcamara7** [comment]
@diegomics EAR report updated and assembly uploaded to the ENA yesterday.

**Comment by diegomics** [comment]
Nice! Please notice that you placed the new PDF in an incorrect folder. You have the old PDF in the correct folder and the new one in the incorrect one, threfore you are trying to merge two files

Screenshot 2024-10-16 at 12 47 47

Fix that so we can merge it :)

**Comment by fcamara7** [comment]
wait I will try again sorry.

**Comment by diegomics** [comment]
Awesome, final EAR looking great. Merging this one, congrats!

**Comment by diegomics** [comment]
@fcamara7 Sorry, I reverted this since you remove both files. As you can see, now you have 0 files changed in this PR

You need to update this one:
Assembly_Reports/Stigmatoteuthis_arcturi/xcStiArct1/xcStiArct1_EAR.pdf

And you need to remove this one:
Assembly_Reports/xcStiArct1/xcStiArct1_EAR.pdf

**Comment by diegomics** [comment]
@fcamara7 Don't worry, I'm fixing it for you :)

**Pull request merged**
