### PR TITLE
Added Pinctada radiata / xbPinRadi1

### PR DESCRIPTION
**Pull request by bistace**
## Assembly review request

- ToLID: xbPinRadi1
- Species: Pinctada radiata
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @bistace, thanks for sending the EAR of _Pinctada radiata_.
I added the corresponding tag to the PR and will contact a reviewer ASAP. I'm assigning myself as supervisor.

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-07-10 16:48

All Eligible Candidates:

Github ID     | Full Name       | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
----------------------------------------------------------------------------------------------------------------------------
epaule        | Michael Paulini | Sanger      | 0             | NA          | Y      | N    | 1001          | 1101          
SarahPelan    | Sarah Pelan     | Sanger      | 1             | 2024-03-22  | Y      | N    | 1000          | 1050          
joannacollins | Jo Collins      | Sanger      | 1             | 2024-03-27  | Y      | N    | 1000          | 1050          
DomAbsolon    | Dom Absolon     | Sanger      | 1             | 2024-04-22  | Y      | N    | 1000          | 1050          
additive3     | Jo Wood         | Sanger      | 2             | 2024-06-15  | Y      | N    | 999           | 1049          
tommathers    | Tom Mathers     | Sanger      | 2             | 2024-07-08  | Y      | N    | 999           | 1049          
tbrown91      | Tom Brown       | IZW         | 9             | 2024-07-05  | Y      | N    | 993           | 993           

Selected reviewer: Michael Paulini (epaule)
The decision was based on:
- different institution ('Sanger')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1101)
- Highest adjusted calling score.
```

**Comment by diegomics** [comment]
Hi @epaule, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 17-JUL-2024 at 16:55 CET.

**Comment by diegomics** [comment]
Hi @bistace, while we are waiting for the reviewer response, two things (one critical)
. I cannot open the .pretext file link. I also tried wget and the file doesn't download. Please take a look to what can be happening to the link, this is critical for the review.
. what's the coverage of the HiC data? You are only showing HiFi in the PDF

**Comment by epaule** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).

**Comment by bistace** [comment]
Hi,

I'm sorry for the problems, it's the first time we submit here for a review. I thought that the maps would be accessible to people outside the lab. We will be working on a solution with our IT team and come back to you as soon as possible!

**Comment by bistace** [comment]
Hello,

I have changed the link to the Pretext map and added the Hi-C coverage so it should be good now!

**Comment by epaule** [comment]
SUPER_1: hap @ 79.78, scaffold_36 goes to the end of the chromosome
SUPER_2: hap @ 2.32, 3.42, 39.84, 73.32
SUPER_3: hap @ 41.77, 56.24, 46.13, Possible hap @ 61.77. Hap @ 83.70.
SUPER_4: flip 3.7 - 2.5
SUPER_5: scaffold_27 flips and goes in gap @ 67.85, flip 66.7-end, flip 66.7-66.9
scaffold_24, _25 and _28 are haps
SUPER_6: hap @ 14.3s, scaffold_34 joins the end, split scaffold_26 at 406 and join in reverse, last bit is hap, scaffold_39 joins at the end of scaffoldd_26
SUPER_7: small hap @ 28.21, scaffold_40 inserts at 35.18 in reverse
scaffold_32 is a hap
SUPER_8: small hap @ 39.60. Need to break @ 61.55 and flip end, also remove a small piece of hap. Flip 0-1.8, 1.8-2.26 is a hap
SUPER_9: hap @ 56.63- 56.98
SUPER_10: flip 0-4.2, 4.2-5.8 goes to the start of the chroosome in plus, 5.8-6.3 is a hap
SUPER_11: I think there needs to be a break @ 420, from 1-420 flips, also looks like a small piece of hap dup will need removing once the flip os made.  @ 2.91 appears to be hap dup based on coverage. hap @52.0
SUPER_12: hap @ 5, 8.22, 33.5, from gap @ 32.31-32.50 appears to be hap. scaffold_44 goes to 5.1, scaffold_40 next to it, scaffold_38 is part of the repeat at 26.1, flip 44.9 - end
scaffold_31 is a hap
SUPER_13: 1-130 locates somewhere around 6.35 but not sure if you can place as no gap, might need tagging as unloc. hap @ 15.33. The region 38.38-40.12 looks like hap but coverage not conclusive, see what you think. SUPER_13_unloc_2 goes to 29.4 , hap 53.2-end. SUPER_13_unloc_1 would be a hap based on the coverage together with scaffold_15 0-203.
SUPER_14: hap@ 21.5, scaffold_33 goes in reverse at 37.38,
scaffold_14: hap 478-end, rest would be an unloc of SUPER_14
scaffold_41, _22, _23, _29 are haps

**Comment by bistace** [comment]
Hello @epaule and thanks a lot for your review! 

I agree and can see why you are suggesting most of these changes but for some of them I do not understand what made you come to this conclusion. You have a lot more experience doing this than I have so you are most certainly right and so I would like to understand these to improve my curation skills for the future maps that we will submit. 

As an example, on the SUPER_2 scaffold at 3.42Mb you are suggesting that there is an haplotypic duplication but I can only see a very small cross with no contacts. Could you please explain why you see a duplication there? image

Here is another example on SUPER_2 at 73.32Mb that looks a bit like the previous one. Could you please explain that one too? 
image

**Comment by epaule** [comment]
the first one has this characteristic double-V shape with a drop in coverage
the second one has a drop in coverage without it being repetitive and the HiC coverage also goes down, so it would be a stretch that is haplotypic ... plus it also shows a cross shape.

The first one looks very much like a hapdup, whereas the second one is a stretch of heterozygous sequence that was merged in (so you could argue that the second one could be left in, as it extends the sequence, but then the cross shape also hints towards a potential inverted duplication of the heterozygous sequence and a suboptimal join in between the two bits.

**Comment by bistace** [comment]
Hello and thank you for your explanations,

I applied most of the requested changes (47 edits) and left the ones that I did not feel confident applying, mostly because they are very small and cutting precisely here is hard. I updated the EAR report and the Pretext map. 

Here is the list of suggested changes that I did not do:
  - SUPER_2 at 73.32Mb
  - SUPER_3 at 46.13Mb, 56.24Mb and 83.73Mb
  - SUPER_11 1-420kb - made the flip but did not remove the duplication
  - SUPER_13 38.38Mb - I let it in the assembly as I was not sure it was an haplotig

**Comment by epaule** [comment]
As they are too small to edit, i think it is fair to leave them in. So I am happy to sign it off for merging

We use HiGlass for zooming in beyond what Pretext can do, but it is not trivial to get running.

**Review by epaule — APPROVED** [review]
As they are too small to edit, i think it is fair to leave them in. So I am happy to sign it off for merging

We use HiGlass for zooming in beyond what Pretext can do, but it is not trivial to get running.

**Comment by diegomics** [comment]
My eyes are way less accute than yours @epaule 
All changes placed by @bistace look great to me, only thing is this one:
SUPER_10: flip 0-1,59
Can you confirm it?

**Comment by epaule** [comment]
yes, would also vote for flipping the start of SUPER_10

**Comment by bistace** [comment]
Contacts look indeed a bit better but there is a telomeric repeat that gets moved to the inside of the scaffold. Do you still think that we should flip it?

**Comment by diegomics** [comment]
Screenshot 2024-07-17 at 13 31 35
You can flip it right after the telomeric segment

**Comment by bistace** [comment]
I am in the process to generate the final map and EAR but this is taking a bit more time than expected because we are testing some scripts to ease up the process at the same time. 

@epaule I am a bit curious about your HiGlass usage, is there any way to convert the info in a pretext map to a format that is understandable by HiGlass?

**Comment by diegomics** [comment]
FYI @bistace 😉
Here, we use HiGlass in Galaxy on the web. To use it, you need to upload your .mcool file and run the interactive tool.
To generate both .pretext and .mcool files, you can use @tbrown91 nice Snakemake workflow: https://workflowhub.eu/workflows/795
Soon™ we'll be realising a Galaxy workflow to do the same together with a guide

**Comment by bistace** [comment]
Hello,
thank you @diegomics, we are testing the mcool generation commands to improve our reviewing process. @epaule, if you have additional informations about converting a Pretext map to import it in HiGlass we would be glad to benefit from your knowledge but otherwise I won't be bothering you with that again.
 
I updated the EAR and the Pretext map with the requested change.

**Comment by diegomics** [comment]
Thanks @bistace. From my side, I think all points were addressed. I still see an off-telomeric signal at the end of SUPER_14. Please @epaule, would you give the new pretext file a last look?

**Comment by epaule** [comment]
looks good to me. The telomer is also now at the correct place.

**Comment by diegomics** [comment]
This is the one I'm pointing out:
Screenshot 2024-07-24 at 12 19 45

I don't know if it is enough at this resolution

**Comment by epaule** [comment]
I think the HiC contacts look worse if you flip it, but there is a gap and a telomer signal, but maybe @bistace could flip it, remap the data and see how pretext looks afterwards, as sometime the HiC pattern changes.

**Comment by bistace** [comment]
Hello,

I have updated the EAR and the map. I think that the map looks a bit better without flipping but I will do what you think is better.

**Comment by diegomics** [comment]
I think this is ok, the only way of getting a better idea is to use HiGlass or remap after doing the flip to check if the signal gets better. You can keep this version.

Thanks @epaule for the review.
I will add a new reviewed species for you to the table after merging the PR ;)

Congrats on the assembly @bistace! First one from Genoscope!!!
After the merging, you can [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission)

**Pull request merged**
