### PR TITLE
mApoAgr2 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
Assembly review request
---

ToLID: mApoAgr2

Species: Apodemus agrarius

Project: ERGA-BGE

Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @fcamara7, thanks for sending the EAR of _Apodemus agrarius_. I added the corresponding tag to the PR. I will contact a reviewer ASAP.

**Comment by JoannaCollins** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D

I appointed you as the EAR reviewer. I will change your status to `Busy` until you finish this review. Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something, and contact the PR assignee for any issues.

**Review by JoannaCollins — COMMENTED** [review]
Hi Francisco,

This assembly is looking in pretty good shape and matches the published karyotype.

There are just a few regions that I think need reviewing,  I will list these so you can inspect them:

SUPER_3: Region 1-~797Kbp looks from HiC like it might be possible haplotypic  duplication - there is a gap and the coverage drops here as well. Is it possible to do an alignment against self to see if you can confirm this? Also the whole end looks to break off at the gap @ 9.89Mb and this whole chunk (minus the little piece on the end that is possible hap dup) appears to go in the gap @ 78.27Mb.

SUPER_4: needs break @ gap ~149.92Mb and the end needs to be in the other orientation.

SUPER_13: needs a break @ gap ~83.77Mb and the end needs to be in the other orientation.

SUPER_19: Looks to need a break @ 38.69Mb and the needs to be in the other orientation.

SUPER_21: Looks like the end needs to be broken off from the gap @ 54.17 and placed in the gap @ 49.38Mb. 

SUPER_23: needs breaking @ gap @ 17.8Mb. The piece that has been broken off then joins to the right-hand end of the chr in the +ve orientation.

Any questions just let me know,

Thanks very much

Jo

**Comment by tbrown91** [comment]
Hi @JoannaCollins, thank you for the thorough review!

I think all of these would be classified as "clear and obvious" changes, apart from maybe the first on SUPER_3. I would be interest to know how it looks once Francisco plays with the assembly a bit. @fcamara7 could you please have a look at how the suggested changes affect the assembly, re-create the EAR and update the pull-request? We will then have a look at how this affects the telo-tracks and overall images.

@JoannaCollins we are currently viewing an "Approve" as an indication that the assembly is finished, so in the future it would be helpful if you could only do this once you feel no more changes need to be made to the assembly.  We are testing having the second reviewer as more of a "moderator" at the moment.

Many thanks both and great to see this working so smoothly.

Tom

**Comment by fcamara7** [comment]
Thanks a lot for the suggestions @JoannaCollins ! @talioto is in the process of implementing the suggested changes and when this is done we will re-submit the EAR report for this species with a link to the directory with the pre-final curation pretext map and and a save state corresponding to the changes. I will also regenerate the stats, merqury & busco even though I do not expect things to change much if at all. We could also re-map the hic data to the modified assembly but this could take a few days.

**Comment by JoannaCollins** [comment]
Hi @fcamara7, thats great, thanks for letting me know.

Best Wishes

Jo

**Comment by fcamara7** [comment]
mApoAgr2 report updated to address suggestions by the reviewer.

[mApoAgr2_EAR.pdf](https://github.com/ERGA-consortium/EARs/files/14758102/mApoAgr2_EAR.pdf)

**Comment by diegomics** [comment]
Hi @fcamara7
To update the PR, replace the file `EARs/Assembly_Reports/Apodemus_agrarius/mApoAgr2/mApoAgr2_EAR.pdf` in your branch `fcamara7:fcamara7-mApoAgr2` with the **new** `mApoAgr2_EAR.pdf` file

**Comment by tbrown91** [comment]
Hi @fcamara7 Unfortunately I am not able to download the pretext file from your link, it is asking me for a login. Is there a chance you could make the link public or place it in an open location?

**Comment by fcamara7** [comment]
It should be updated now. Sorry I did not realize I was in my main branch rather than in the correct one.

**Comment by fcamara7** [comment]
> Hi @fcamara7 Unfortunately I am not able to download the pretext file from your link, it is asking me for a login. Is there a chance you could make the link public or place it in an open location?

Ok @tbrown91 , let me fix that. Sorry.

**Comment by tbrown91** [comment]
It's working now

@JoannaCollins could I ask you to please give the map a look over once more? Then following your approval we will merge and the genome should be final

**Comment by fcamara7** [comment]
Sorry, got the link for the wrong file @tbrown91 . Will re-do it now.

**Review by JoannaCollins — APPROVED** [review]
Hi @fcamara7 and @tbrown91 , i have reviewed the changes and the assembly all looks good now.

**Comment by tbrown91** [comment]
Thank you both!

It's great to see another genome on the way to ENA

**Review by tbrown91 — APPROVED** [review]

**Comment by tbrown91** [comment]
@bot nudge

**Comment by diegomics** [comment]
Thanks @JoannaCollins for doing the review. I will add a new reviewed species for you to the table when @tbrown91  merges the PR ;)

**Pull request merged**
