### PR TITLE
EAR upload for wsMarCava1.

### PR DESCRIPTION
**Pull request by tommathers**
## Assembly review request

- ToLID: wsMarCava1
- Species: Marifugia cavatica
- Project: ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by tommathers** [comment]
Curated by @tommathers

**Comment by diegomics** [comment]
Ok

**Comment by diegomics** [comment]
Yes

**Comment by diegomics** [comment]
Another complex annelid assembly, pacbio ultra low, hi-c from different individual, noisy... my respects to the curator, the assembly looks good.
Can you comment on the following:
- What's the BUSCO database? (I will make a fix for these kind of cases in the next version of the EAR)
- It's a little surprise to see that from the 11 big scaffolds, 3 are assigned to Annelida and the other 9 as Mollusca/Brachiopoda
- SUPER_1 @ 0.64-0.72
- SUPER_3 has a terminal section with little contact signal after the telomeric signal. Are those non-telomeric repeats after the telomere? The repeat density also seems to drop a little
- SUPER_4 @ 143.34-143.496 can be unloc SUPER_3?
- SUPER_5 @ 70.1 may belong to SUPER_3 around 17 Kbp?
- SUPER_7 @ 30.1
- SUPER_7 @ 100.8 are those non-telomeric repeats?

Again, complex curation, shout-out to the Sanger team.
Thanks!

**Comment by tommathers** [comment]
Hi, thanks for looking at this. Just waiting for a new EAR to be generated then will upload.

RE. suggested changes: 

_What's the BUSCO database? (I will make a fix for these kind of cases in the next version of the EAR)
It's a little surprise to see that from the 11 big scaffolds, 3 are assigned to Annelida and the other 9 as Mollusca/Brachiopoda_

Not sure about the BUSCO versions for generating the EAR. 

_SUPER_1 @ 0.64-0.72_ 

This is not gapped, probably a difference between HIC and pacbio samples. 

_SUPER_3 has a terminal section with little contact signal after the telomeric signal. Are those non-telomeric repeats after the telomere? The repeat density also seems to drop a little_

Not supported by HiC and there is a gap so I have moved this chunk in shrapnel.

_SUPER_4 @ 143.34-143.496 can be unloc SUPER_3?_

This is not gapped so possibly difference between the pacbio and HiC samples. The HiC also hits to multepl other locations so no unambiguous alternative. I suggest leavaing as is. 

_SUPER_5 @ 70.1 may belong to SUPER_3 around 17 Kbp?_

Again, not gapped so I suggest leaving as is. 

_SUPER_7 @ 30.1_

As above.

_SUPER_7 @ 100.8 are those non-telomeric repeats?_

I have chopped this off and moved to shrapnel.

**Review by diegomics — APPROVED** [review]
Thanks @tommathers, I'm happy with the responses. I will approve this now so you can export the fasta and start uploading to ENA. But I will wait until you regenerate the pdf with new gfastats values since that should be the only thing that will change from the old report to the new one. Does it sound ok for you?

**Comment by tommathers** [comment]
Yes great, thanks.

**Comment by diegomics** [comment]
Hi @tommathers please remember to regenerate the PDF so we can merge this one

**Comment by additive3** [comment]
It's being produced now! :)

**Pull request merged**
