### PR TITLE
fValHis1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
## Assembly review request

- ToLID: fValHis1
- Species: Valencia hispanica
- Project: ERGA-BGE
- Affiliation: CNAG

### CODE REVIEW

**Review by diegomics — CHANGES_REQUESTED** [review]
Hi @fcamara7 

I fixed something in the make_EAR code to round certain values properly. Could you create the fValHis1 EAR again and update the PR? You don't need to open another PR, just update the pdf file in the `fcamara7-fValHis1` branch. Let me know of you need help :)

**Review by diegomics — APPROVED** [review]
Thanks @fcamara7 all good now. @tbrown91 will proceed with the review

**Review by tbrown91 — APPROVED** [review]
Hi Francisco,

Looking very nice, congrats on the ace assembly.

Tom

**Comment by diegomics** [comment]
All good, congrats to the CNAG team!

**Pull request merged**
