### PR TITLE
added Culex laticinctus / idCulLati1

### PR DESCRIPTION
**Pull request by epaule**
## Assembly review request

- ToLID: idCulLati1
- Species: Culex laticinctus
- Project: ERGA-BGE
- Affiliation: WSI

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @epaule, thanks for sending the EAR of _Culex laticinctus_.
I added the corresponding tag to the PR and appointed @tbrown91 as the [assignee](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) to supervise.
I will contact a reviewer ASAP.

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-05-30 13:31

All Eligible Candidates:

Github ID | Full Name             | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
------------------------------------------------------------------------------------------------------------------------------
jesgomez  | Jessica Gomez Garrido | CNAG        | 0             | NA          | Y      | N    | 1007          | 1107 
gitcruz   | Fernando Cruz         | CNAG        | 0             | NA          | Y      | N    | 1007          | 1107                   
tbrown91  | Tom Brown             | IZW         | 8             | 2024-02-21  | Y      | N    | 993           | 993           

Selected reviewer: Jessica Gomez Garrido (jesgomez)
The decision was based on:
- different institution ('CNAG')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1107)
- randomly chosen to break a tie among the finalists
```

**Comment by diegomics** [comment]
Hi @jesgomez, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 06-JUN-2024 at 13:42 CET.

**Comment by jesgomez** [comment]
> Hi @jesgomez, do you agree to review this assembly? Please reply to this message only with **Yes** or **No** by 06-JUN-2024 at 13:42 CET.

yes

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Comment by jesgomez** [comment]
I reviewed the assembly and it looks good to me. The total number of gaps is a bit high because the contig N50 is slightly low, but in overall it is a good assembly and the pretext map looks fine, the three chromosomes have been properly reconstructed. Good work!

**Comment by tbrown91** [comment]
Hi @jesgomez, thank you for the review. If you "accept" the genome, can you please "add your review" at the top of the page to indicate that you are happy for the genome to be submitted to ENA

**Comment by tbrown91** [comment]
@epaule If you did the curation, hats off to you, because this looks like a nightmare. It's great to see more diverse species coming through ERGA though, so thank you and congrats on the work

**Review by jesgomez — APPROVED** [review]
I reviewed the assembly and it looks good to me. The total number of gaps is a bit high because the contig N50 is slightly low, but in overall it is a good assembly and the pretext map looks fine, the three chromosomes have been properly reconstructed. Good work!

**Review by tbrown91 — APPROVED** [review]

**Comment by epaule** [comment]
thanks :-)

**Pull request merged**
