### PR TITLE
added Culex modestus / idCulMode1

### PR DESCRIPTION
**Pull request by epaule**
## Assembly review request

- ToLID: idCulMode1
- Species: Culex modestus
- Project: ERGA-BGE
- Affiliation: WSI

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @epaule, thanks for sending the EAR of _Culex modestus_.
I added the corresponding tag to the PR and appointed @tbrown91 as the [assignee](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) to supervise.
I will contact a reviewer ASAP.

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-05-30 16:44

All Eligible Candidates:

Github ID | Full Name             | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
------------------------------------------------------------------------------------------------------------------------------
gitcruz   | Fernando Cruz         | CNAG        | 0             | NA          | Y      | N    | 1007          | 1107          
jesgomez  | Jessica Gomez Garrido | CNAG        | 0             | NA          | Y      | N    | 1007          | 1107          
tbrown91  | Tom Brown             | IZW         | 8             | 2024-02-21  | Y      | N    | 993           | 993           

Selected reviewer: Fernando Cruz (gitcruz)
The decision was based on:
- different institution ('CNAG')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1107)
- randomly chosen to break a tie among the finalists
```

**Comment by diegomics** [comment]
Hi @gitcruz, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 06-JUN-2024 at 16:52 CET.

**Comment by gitcruz** [comment]
Yes, I'll be happy to review it.

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something.
Contact the PR assignee for any issues.

**Comment by epaule** [comment]
i added @SarahPelan , as she is the one who did the curation.

**Comment by tbrown91** [comment]
@gitcruz Have you had a chance to look at the assembly? It would be nice to get a through more through the BGE process.

Many thanks

**Comment by gitcruz** [comment]
Hi @tbrown91 

Thanks for the reminder, my sincere apologies for the delay.

I had reviewed the assembly, my congratulations to @epaule and @SarahPelan dor the great work. These are my comments:

- **Contamination**  could you confirm that the hits to other phyla (different than insecta or no-hit) are false positives forund by blobtools?. I bet they are, as they are small an within the same range of GC and coverage of other insecta contigs of similar size.
- **Curation** great work i general makes sense and you recover centromere-telomere and T2T interactions. However in SUPER_2 I can see some translocations:
1) sequence around 84.58-84.7MB could be moved to 74.25Mb and it wold be well localized there.
2) around 93-93.99Mb I would place these sequence as Unloc
3) same for sequence at 97.9-98.28Mb

Please go over it and tell me if you and @tbrown91 agree on this.

Best regards,
Fernando

**Comment by gitcruz** [comment]
Hi @diegomics

I have been receiving notifications for other assemblies thta I am not reviewing and for which I did not even add comments. Would it be possible to adjust the notifications in a way that they are resticted to the last two cases (reviewed or commented by me)? 

I'd appreciate reducind the email trafffic to he strictly necessary.

Thanks!
F.

**Comment by diegomics** [comment]
@gitcruz are you receiving all activity? If so, please adjust your notifications to participating and @mentions 👇



Screenshot 2024-06-18 at 16 00 35

**Comment by tbrown91** [comment]
Some comments:
The "avg_coverage" track appears to be zero everywhere, is this working as intended?

The coverage is so erratic that it is very difficult to tell if there are any duplications, especially with the resolution of this image.

Given the number of contigs, it's pretty amazing that it looks this good. 

Some small things I have noticed. Maybe some of them should be unlocalised, but I don't think they are correct where they currently are:

SUPER_1 29.2Mb-29.3Mb - localises to SUPER_1 @ 137.6Mb

SUPER_2 29.6Mb-29.8Mb - localises to SUPER_1 @ 206Mb
SUPER_2 54.4Mb-54.7Mb - duplication or inversion? difficult to see from the map
SUPER_2 84.8Mb-85.3Mb - I agree with Fernando, something weird is going on here
SUPER_2 29.6Mb-29.8Mb - localises to SUPER_2 @ 74.0Mb
SUPER_2 93.6Mb & 99.0Mb - again something weird - does it look biological in the higlass map. e.g. repeat sequence, potential translocation between the two haplotypes?
SUPER_2 113.5Mb-113.7Mb - are you sure this belongs in SUPER_2?
SUPER_2 115.0Mb-115.2Mb - belongs in SUPER_3 centromere
SUPER_2 193.8Mb - localises to SUPER_1 @ 78.4Mb

SUPER_3 55.8Mb - localises to SUPER_2 @ 26.4Mb
SUPER_3 56.7Mb - localises to SUPER_1 @ 231.4Mb
SUPER_3 59.2Mb - localises to SUPER_1 @ 50.7Mb

Given the number of contigs, this is really picking. It's amazing to have such a fragmented assembly in chromosomes like this. Great job to @SarahPelan

**Comment by gitcruz** [comment]
Thanks @diegomics!!
 it took me a while to find it. Went to manage notifications>watched repositories>unwatch and then selected "Participating and @mentions"

**Comment by tbrown91** [comment]
Sorry, I forgot my role as supervisor.

@epaule Can you please look through the highlighted areas and in particular address @gitcruz's comments regarding possible contaminants?

Many thanks,

Tom

**Comment by SarahPelan** [comment]
@tbrown91 am currently looking through the comments, @epaule has looked at contaminants and we should have new files soon....
Thanks,
Sarah

**Comment by tbrown91** [comment]
Thanks @epaule and @SarahPelan 

This is looking pretty amazing. @gitcruz can I ask you to give the map one last look through, and then I'm happy to merge

**Review by tbrown91 — APPROVED** [review]

**Comment by epaule** [comment]
The non-arthropoda blobs in the last report are false positives, as we went through the ones without HiC contacts to the parent and they came back as insect hits in blast & NCBI-GX.

**Comment by diegomics** [comment]
Thanks @gitcruz for the review.
I will add a new reviewed species for you to the table after merging ;)

Congrats on the assembly @epaule! (and @SarahPelan and team)
After the merging, you can [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission)

**Pull request merged**
