### PR TITLE
mRupRup1 EAR

### PR DESCRIPTION
**Pull request by fcamara7**
Assembly review request
---

ToLID: mRupRup1

Species: Rupicapra rupicapra

Project: ERGA-BGE

Affiliation: CNAG

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @fcamara7, thanks for sending the EAR of _Rupicapra rupicapra_. I added the corresponding tag to the PR. I will contact a reviewer ASAP.

**Comment by additive3** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing :D

I appointed you as the EAR reviewer. I will change your status to `Busy` until you finish this review. Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something, and contact the PR assignee for any issues.

**Review by additive3 — APPROVED** [review]
Hi Francisco, 

I've checked the mRupRup1 assembly and find no issues with it.
Great job.

Best,
Jo

**Comment by diegomics** [comment]
Thanks @additive3 for doing the review. I will add a new reviewed species for you to the table when @tbrown91 gives thumbs up and merges the PR ;)

**Comment by tbrown91** [comment]
Congrats on the assembly @fcamara7! You are good to go to [upload the assembly to ENA](https://github.com/ERGA-consortium/ERGA-submission).
Thanks all, merging now.

**Comment by fcamara7** [comment]
> Hi Francisco,
> 
> I've checked the mRupRup1 assembly and find no issues with it. Great job.
> 
> Best, Jo

Thank you!

**Pull request merged**
