### PR TITLE
add Anisus vorticulus

### PR DESCRIPTION
**Pull request by epaule**
## Assembly review request

- ToLID: xgAniVori1
- Species: Anisus vorticulus
- Project: ERGA-BGE
- Affiliation: Sanger

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @epaule, thanks for sending the EAR of _Anisus vorticulus_.
I added the corresponding tag to the PR and will contact a supervisor and a reviewer ASAP.

**Comment by diegomics** [comment]
Hi @tbrown91, do you agree to [supervise](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) this assembly?
Please reply to this message only with **OK** to give acknowledge.

**Comment by tbrown91** [comment]
Ok

**Comment by diegomics** [comment]
```
*****
EAR Reviewer Selection Process
Date: 2024-08-19 18:12

All Eligible Candidates:

Github ID | Full Name      | Institution | Total Reviews | Last Review | Active | Busy | Calling Score | Adjusted Score
-----------------------------------------------------------------------------------------------------------------------
gitcruz   | Fernando Cruz  | CNAG        | 1             | 2024-07-15  | Y      | N    | 1008          | 1058          
tbrown91  | Tom Brown      | IZW         | 9             | 2024-07-05  | Y      | N    | 999           | 999           
diegomics | Diego De Panis | IZW         | 9             | 2024-07-05  | Y      | N    | 997           | 997           

Selected reviewer: Fernando Cruz (gitcruz)
The decision was based on:
- different institution ('CNAG')
- active ('Y')
- not busy ('N')
- highest adjusted calling score in this particular selection (1058)
```

**Comment by diegomics** [comment]
Hi @gitcruz, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 26-AUG-2024 at 18:14 CET.

**Comment by gitcruz** [comment]
Yes

**Comment by diegomics** [comment]
Thanks for agreeing!
I appointed you as the EAR reviewer.
I will keep your status as _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).
Contact the PR assignee for any issues.

**Comment by gitcruz** [comment]
Hi @epaule, 

Great job!! I examined the contact map and I fully agree with the decissions made. Some things are particualrly challenging but are well resolved. For example, the last block of SUPER_6 (53-60Mb) looks better where you have placed it. There are strong T2T interactions between SUPER_18 and 17 and 11 that can be explained, etc

Regarding contaminants, I think those flagged by BTK are false positives corresponding to repeats or with distant homology. Could you tell me if these blobs correspond to weak hits to Uniprot found with diamond? We often found these kind of "false positive" contaminants.

Unless I'm wrong with my interpretation about the contaminants, is good to go and uploaded to ENA.

Thanks!
Fernando

**Comment by tbrown91** [comment]
Thanks @gitcruz 

@epaule this is looking really nice. I just have a couple of questions that maybe you've already thought about.

SUPER_2_unloc_2 looks like it might be a hapdup. Do you think this should be removed?
Same for scaffold_47, which looks to be a hapdup with SUPER_11
SUPER_14_unlock_1 looks like it also has interaction with SUPER_18 - I wonder if it would be best to leave it as a scaffold
I think could place SUPER_2_unloc_1 at the end of SUPER_2 in the reverse orientation, based on the fact the unloc sequence has a telomere at the beginning.

Please have a look at the potential false-positives in the blob plot that @gitcruz highlighted, and then hopefully we can sign this off soon.

**Comment by epaule** [comment]
@gitcruz i checked just them, and they look like false positives
@tbrown91 good catch. I did the changes and hopefully send a new EAR your way soon

**Comment by tbrown91** [comment]
Hi @gitcruz can I ask you to look through the new EAR please?

**Comment by gitcruz** [comment]
Hi @tbrown91  and @epaule,

I had a look at the new contact map and I do have some comments:

1. SUPER_1_unloc_1 could be placed next to a gap near 50.5Mb of SUPER_1 (inside a region that looks heterochromatic, maybe a centromere?). Think about it or leave as unloc
2. The first 2Mb of SUPER_17 can be broken at a gap and move to the end of SUPER_18 (there are strong contacts there and with other scaffolds). This will imply breaking SUPER_18 at position 35.8Mb. But to me it looks like is a separate chromosome compartment. 

I insert here a screenshot after these second set of edits. 
xgAniVori1_smallest_SUPER

I also copied the quick edits i did to the clipboard (although the way pretext record them is often a bit strange).
[Edits_xgAniVori1_review2.txt](https://github.com/user-attachments/files/16948497/Edits_xgAniVori1_review2.txt)


With regard to the contaminants, is nice to see a clean blobplot now. But I'm surprise that now some of the blobs previously matching other phyla are idnetified as no-hit. What is the reason? Is just because in this second run of btk you only ran blastn against nt. That means you have not ran diamond when that's the case (no-hit in using blastn). I'd like to understand it.

For future reviews, it would be nice to have the unlocs right after their scaffold this can be done using the option _--sortby nosort_ while generating the PretextMap. Otherwise one needs to drag this contigs along the map and find the corresponding SUPER.

Hope this helps.
Fernando

**Comment by epaule** [comment]
I do believe we updated our BTK pipeline, which could explain the differences. And I am building a new report with an alternate proposal for the subtelomeric repeats.

**Comment by gitcruz** [comment]
Hi Michel,

@epaule: 

Thanks for clarifying the btk results, I would appreciate if you follow up on this and send me the details about the differences by email. It would be helpful for me, sometimes these false positives are very distracting.

I had another look at the pretext map and I see that there are many repeat-2-repeat contacts . I agree with you, these scaffolds shouldn't be merged with the "subtelomeric repeats" (high coverage and repeat density):
- I take back the suggestion of introducing a SUPER_18. These repeats were contigged together with the previous sequence.
- Leave the rest of the scaffolds interating with these huge subetlomeric repeat as unplaced

I think you made a really good job with this gemone assembly. But I am to 100% sure about a couple of things, I'd like to know the opinion of @tbrown91 too:

 - The first contig(~ 2Mb) of SUPER_17. There is a gap right after it, and i think the scaffolder was fooled with repat-to-repeat contacts. In my opinion, this should also be unplaced or at the most unloc of SUPER_17. That's more conservative and prudent.
 - I leave up to you localizing the SUPER_1_unloc_1 could at the gap near 50.5Mb of SUPER_1 (inside a region that looks heterochromatic, maybe a centromere?). I personally think it fits over there

We can discuss it here before generating a new EAR.

Hope it helps,
Fernando

**Comment by tbrown91** [comment]
Thanks for reuploading @epaule and looking through the assembly @gitcruz 

I moved the first 2Mb of super_17 around the genome and I am reasonably convinced that it belongs where it is at the moment. It has low interaction with other chromosomes and a nice gradient of signal between the two corners.

With super_1_unloc_1 I think I could say where it goes, but not the orientation. I am always more on the conservative side, so would leave it as is.

For me, this is a great assembly of a funky little species that I would consider complete. 

@epaule could you share your btk pipeline with us, maybe in the ERGA_assembly slack? In particular I would like to see the databases used and alignment commands.

Thank you both

**Comment by gitcruz** [comment]
Thanks @Tom Brown ***@***.***> ,  you're right about SUPER_17.

According to this, I think we should approve it for upload to ENA.

I don't think we need to wait for the details about the btk pipeline for
this.

Best,
Fernando

**Comment by DLBPointon** [comment]
Hi all,

The most recent version of the EAR report was generated with the sanger-tol/ear pipeline that I have written, this uses the sanger-tol/blobtoolkit pipeline which in turn uses blobtoolkit: 4.3.9. These pipelines are in nextflow and differ quite a bit from the prior snakemake pipeline which uses blobtoolkit: 2.6.5, and generated the first version of the report.

So the two reports use pretty different versions in terms of both software and structure. However, we would like to use the sanger-tol/ear pipeline going forward to at least semi-automate the whole process.

**Comment by tbrown91** [comment]
@DLBPointon This is amazing: https://github.com/sanger-tol/ear/tree/dp24_testdata thank you

@gitcruz If you are happy, could you then please "Approve" the changes, then I can merge

@epaule great job

**Comment by eeaunin** [comment]
This is the link to the old BlobToolKit Snakemake pipeline: [https://github.com/blobtoolkit/pipeline](https://github.com/blobtoolkit/pipeline). The Snakemake pipeline run for Anisus vorticulus was done with these BUSCO lineages: `lepidoptera_odb10 endopterygota_odb10 insecta_odb10 arthropoda_odb10 metazoa_odb10 eukaryota_odb10 bacteria_odb10 archaea_odb10 viridiplantae_odb10 fungi_odb10 apicomplexa_odb10 euglenozoa_odb10 diptera_odb10 alphaproteobacteria_odb10 mycoplasmatales_odb10 proteobacteria_odb10 nematoda_odb10 rickettsiales_odb10`.
I think the larger number of BUSCO lineages used in the Snakemake pipeline run probably explains why it was able to classify some sequences that were no-hit in the run with the newer pipeline.

**Comment by tbrown91** [comment]
Thanks all

**Comment by eeaunin** [comment]
@gitcruz Hello. In BlobToolKit pipeline V1 (which is  what the the diagram depicts) BUSCO gene models were not used as input for Diamond. But in BlobToolKit Snakemake pipeline V2 and in the Nextflow version of the BlobToolKit pipeline the input for Diamond blastp depends on the results of the BUSCO runs

**Comment by gitcruz** [comment]
Thanks a lot for the quick response @eeaunin,

I'll definitely try out  V2 as soon as I can. I guess it yields a lot less faslse positives.

Cheers.
Fernando

**Comment by rjchallis** [comment]
Hi @gitcruz, the snakemake pipeline code moved to the [blobtoolkit/blobtoolkit](https://github.com/blobtoolkit/blobtoolkit) repo, which should be linked from the archived blobtoollkit-pipeline README and is up to version 4.x. You can create an issue over there, or even better head to [sanger-tol/blobtoolkit](https://github.com/sanger-tol/blobtoolkit) for a nextflow implementation of the pipeline, which will be the preferred way to run it going forward.

**Comment by gitcruz** [comment]
Hi @rjchallis, Thanks for the quick off-channel response!

Makes sense to switch to nextflow then. 

Best,
Fernando

**Pull request merged**
