### PR TITLE
add Albinaria teres / xgAlbTers5

### PR DESCRIPTION
**Pull request by ldemirdj**
## Assembly review request

- ToLID: xgAlbTers5
- Species: Albinaria teres
- Project: ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by diegomics** [comment]
Hi @tbrown91, do you agree to [supervise](https://github.com/ERGA-consortium/EARs/wiki/Assignees-section) this assembly?
Please reply to this message only with **OK** to give acknowledge.

**Comment by tbrown91** [comment]
Ok

**Comment by diegomics** [comment]
Hi @DomAbsolon, do you agree to review this assembly?
Please reply to this message only with **Yes** or **No** by 01-AUG-2024 at 17:47 CET.

**Comment by DomAbsolon** [comment]
Yes


From: Diego De Panis ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Thursday 25 July 2024 at 16:47
To: ERGA-consortium/EARs ***@***.***>
Cc: Dominic Absolon ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] add Albinaria teres / xgAlbTers5 (PR #51) [EXT]


Hi @DomAbsolon [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DomAbsolon&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=8hWaKIttONHFNzuLYDd2YuJUwqKGeV487Dnt5avhNSg6h6GmxCCPNkMV9Ga_DYSU&s=J-3C3vo2_eKm57ie9qSsqT1RoMT8WFHo0FHyvxLrFMs&e=>, do you agree to review this assembly?
Please reply to this message only with Yes or No by 01-AUG-2024 at 17:47 CET.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_51-23issuecomment-2D2250747360&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=8hWaKIttONHFNzuLYDd2YuJUwqKGeV487Dnt5avhNSg6h6GmxCCPNkMV9Ga_DYSU&s=fyvSgMwOKFG_iYrkIU5UVRniGtC8n0b-y0GRwSTm04s&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BCJBKID4UBTPI52IWMS3BBDZOEM2BAVCNFSM6AAAAABLOWY2FKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJQG42DOMZWGA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=8hWaKIttONHFNzuLYDd2YuJUwqKGeV487Dnt5avhNSg6h6GmxCCPNkMV9Ga_DYSU&s=h-d_GCpb-F6hva-W2iIeNELEQpqgx42vg-MjCYgS1dY&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by diegomics** [comment]
Thanks for agreeing :D
I appointed you as the EAR reviewer.
I will change your status to _Busy_ until you finish this review.
Please check the [Wiki](https://github.com/ERGA-consortium/EARs/wiki/Reviewers-section) if you need to refresh something (and remember that you must download the EAR PDF to be able to click on the link to the contact map file!).
Contact the PR assignee for any issues.

**Comment by DomAbsolon** [comment]
Hi, I just wanted to double check the correct, curated, map was uploaded ?

**Comment by tbrown91** [comment]
Hi @ldemirdj 

The assembly needs a more thorough curation and review before posting. I have highlighted some of the issues that should be addressed, but please use this as a guide to get started, rather than an exhaustive list of changes to be made. Please @DomAbsolon have a look through my list and see if there are any glaring errors I have missed or areas that I should not have mentioned. 

scaffold_6 1-750kb should be inverted and placed at 1.95Mb
scaffold_6 7.42Mb-8.49Mb should be inverted
scaffold_19 1-19.4Mb  should be inverted
scaffold_19 6.1Mb-6.6Mb remove hapdup
scaffold_19 20.6Mb-20.8Mb remove hapdup
scaffold_27 7.8Mb-8.7Mb remove hapdup
scaffold_27 8.7Mb-11Mb should be inverted
scaffold_22 36.6Mb-36.8Mb should be placed at 39.2Mb - need a higher resolution image to tell for sure the orientation

scaffolds 39,40,41 hapdups remove
scaffold_27_unloc_2 hapdup remove
scaffold_19_unloc_1 hapdup remove

@ldemirdj please re-upload the EAR with a new assembly and HiC map once a further round of revisions have been made

**Comment by ldemirdj** [comment]
Hi @tbrown91 and @DomAbsolon, 
Sorry for the delay, I was on vacation. I came back this week and there seems to be a problem with my pretext map. I'll solve it as soon as possible and keep you posted.
Thanks!

**Comment by tbrown91** [comment]
Hi @ldemirdj have you been able to fix your pretext map? It would be nice to get another genome finished

**Comment by tbrown91** [comment]
More assemblies == happy coordination team

Thanks for the update, looking forward to seeing everything coming through

**Comment by ldemirdj** [comment]
Hi @tbrown91 and @DomAbsolon, I’ve just uploaded the new EAR report.

**Comment by tbrown91** [comment]
Thanks @ldemirdj do you know if the telomere track is correct, or if this species has a different telomere motif? It seems like there are telomere sequences all over the genome, but they don't seem to correspond to places I would want to break the scaffolds

@DomAbsolon could you please have a look through the assembly?

Thank you both

**Comment by ldemirdj** [comment]
Hi @tbrown91, thanks for your message. After checking, it doesn't seem like there's an error with the telomere track, nor any other apparent motifs. However, I agree with you, I also wouldn’t recommend breaking the scaffolds, as we have repeats at the beginning and end of the scaffolds. It’s possible that the genome contains telomeric sequences scattered throughout.

**Comment by DomAbsolon** [comment]
Hi, sorry for only just getting to this, we have a new starter I have been training. Anyway, I have found a couple of things I think needs changing in the map: 

There is a region on chromosome 5 from ~6,421-7,178 Kbp which I think belongs in the gap at 1,513 Kbp. 

On chromosome 6 I believe there needs to be a flip from ~22,056-23,961 Kbp (gap) and then a subsequent flip of 22,030-22,395 Kbp 

Finally I think that the unlock piece of chromosome 25 can be placed at the start of the chromosome. 

Hope these make sense, let me know if not

**Review by DomAbsolon — APPROVED** [review]
All looks good now

**Comment by tbrown91** [comment]
Thank you both!

**Pull request merged**
