### PR TITLE
add xgMetNove1 (Metafruticicola noverca)

### PR DESCRIPTION
**Pull request by duprats**
## Assembly review request

- ToLID: xgMetNove1
- Species: Metafruticicola noverca 
- Project:  ERGA-BGE
- Affiliation: Genoscope

### CODE REVIEW

**Comment by tbrown91** [comment]
ok

**Comment by DomAbsolon** [comment]
Yes

From: "erga-ear-bot[bot]" ***@***.***>
Reply to: ERGA-consortium/EARs ***@***.***>
Date: Tuesday 8 October 2024 at 14:08
To: ERGA-consortium/EARs ***@***.***>
Cc: Dominic Absolon ***@***.***>, Mention ***@***.***>
Subject: Re: [ERGA-consortium/EARs] add xgMetNove1 (Metafruticicola noverca) (PR #88) [EXT]


Hi @DomAbsolon [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DomAbsolon&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=PtA3NN7X-d6u9ditod3bUwcdMoJAteBaTqDjecTZUoNupyRGyqz781V2F0jlUKYB&s=-l1qwFMW2bi9_yED7iYXayKvL3IhBovdS8CYlG2V3F4&e=>, do you agree to review this assembly?
Please reply to this message only with Yes or No by 15-Oct-2024 at 15:07 CET

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ERGA-2Dconsortium_EARs_pull_88-23issuecomment-2D2399800544&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=PtA3NN7X-d6u9ditod3bUwcdMoJAteBaTqDjecTZUoNupyRGyqz781V2F0jlUKYB&s=SON5F14ND_H9uxi_hA0bmN4qwCI9zDRmG9-c7PbWx-Y&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BCJBKIG7HQ2QWIR6GCKGG2LZ2PKMNAVCNFSM6AAAAABPSFIKC6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJZHAYDANJUGQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=HMo-nEncpJD-Huct-h6WEs_n6mFGlpSnfDTSEb1TwXE&m=PtA3NN7X-d6u9ditod3bUwcdMoJAteBaTqDjecTZUoNupyRGyqz781V2F0jlUKYB&s=8eJqTFZMOk0pCNO_0acH6Joz121fdcF-kUhc00u1EQE&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by tbrown91** [comment]
Hi @DomAbsolon have you had a chance to look through the assembly? I have a few areas where I'm not sure and think you will be best placed to make an informed decisions

I'm not sure about the placement of some of the unlocs, especially at SUPER_2 - could this fit just as well in SUPER_3?
Potential hapdups at the start of SUPER_11 and middle of SUPER_14
Centromeres of SUPER_20 and SUPER_25 appear to be at the end and there is a strong telomere signal in the middle. However based on the Hi-C map I'm not sure where/if to invert or move sequences

Please let me know what you think

**Comment by tbrown91** [comment]
and @duprats there are some bacterial scaffolds in the TAPAS map, have these already been removed from the assembly?

**Comment by duprats** [comment]
Hi,
-  I had moved  SUPER_21[0.00 bp -- 2.15 Mbp]   to    SUPER_21[13.59 Mbp]

I agree with you on these : 
-  there are still  12  bacterial scaffolds in the TAPAS map, that I must remove   from the assembly
- I can suppress 'unloc' tags  on SUPER_2_unloc_1,SUPER_2_unloc_2 ; they look like to be  centromeric regions with contacts  on all chromosomes, but with some more contacts with SUPER_2 (but never mind)
- I  wondered too how to invert or move sequences on SUPER_20, SUPER_25 ( but also   Super_23 end Super_26 have telomere signal in the middle  )

(for information , I made around  700 edits on the original map and new haplotigs appears on this map )

**Comment by DomAbsolon** [comment]
I have to say, the HiC data is relatively low quality so this is not an easy curation and makes it hard to say with absolute certainty what if ay changes should be made but I think these are what should be done:

I think the SUPER_2 unlocs are fine, they have raised background signal compared to all the other centromeres. 

SUPER_10 flip from ~13,185-15,876

SUPER_11 I think the following needs changing: cut into five blocks 

A - Start-4,330
B - 4,330-14,719
C - 14,719-19,697
D - 19,697-27,636
E- 27,636-End

The order then goes B(+) -> A(-) -> D(+) -> C(-) -> E(+)

SUPER_14 flip ~24,084-27,743 then remove one copy of the haplotypic duplication. 

SUPER_20 - I think there may be a flip required ~2,421-4,493 although this is not very clear. Regarding the centromere, I think it breaks from ~48,700-End and then this places ~26,667 in reverse orientation. 

I think the repeat array on SUPER_21 (first ~2,000 Kbp) should break off and insert ~13,589

SUPER_25 is a similar situation to SUPER_20. Break around 33,771-End and insert that chunk around 18,000 kbp.

SUPER_26 flip from start-31,753 

All the coordinates stated are as they appear on the tool tip in PretextView (i.e. Kbp).

**Comment by tbrown91** [comment]
Hi @DomAbsolon thank you for looking through the assembly and the thorough review.

Do you have a savestate that you could share? That would certainly speed us along if you have it to hand

**Comment by DomAbsolon** [comment]
Git hub doesn't seem to like save state files so here is a wetransfer link https://we.tl/t-suS1BzJCnN

**Comment by tbrown91** [comment]
@duprats hopefully a quick fix for you. If possible, it would be great to see the EAR again by the end of this week

**Comment by duprats** [comment]
of course ;   but  coverage (for tracks)  is still running

**Comment by tbrown91** [comment]
Hi @DomAbsolon 

Have you had a chance to look through the updated assembly? I had a look through and am generally happy at the higher-level organisation.

My only query was whether the unloc on SUPER_6 could be placed in reverse orientation at ~8.5Mb:

image

Let me know what you think. Hopefully we can get this wrapped up and submitted soon.

**Comment by ldemirdj** [comment]
Hi @tbrown91, 

Simone is on vacation this week, so I'll be stepping in to continue her work and aim to finalize the genome by the deadline. I may run into some challenges as I’m not fully familiar with all the specifics of her progress, but I'll do my best to ensure everything is wrapped up on time.

@DomAbsolon , what are your thoughts on the latest EAR?

Thanks! 

Lola

**Comment by DomAbsolon** [comment]
Hi, yeah a couple more small changes I think need to be done. As Tom says the super_6 unloc could be placed. I also spotted some small miss placed chunks: 

image
SUPER_4 55,724-56181 moves to ~64,465
SUPER_17 44,967-44,590 should unloc to SUPER_19 

Sorry to pick these up only on the second round. The HiC data makes it difficult to spot everything. But after this I think it should begged to go.

**Comment by ldemirdj** [comment]
Hi @DomAbsolon, @tbrown91, 

I’ve made all the requested changes to the best of my understanding, including adjusting the unlocking of super_6 and repositioning SUPER_4 and SUPER_17. I’ve re-run the EAR report generation, and the updated map should be ready tomorrow for a final review.

Thanks again for the thorough review!

Best, 

Lola

**Comment by ldemirdj** [comment]
Hi everyone, 

Despite my attempts to take over this genome, it has proven to be too complex, and I believe it’s best to wait for Simone’s return to continue. Given tomorrow's deadline, it won’t be possible to submit this genome on time. I am awaiting Simone's feedback for a final review, and we will submit it once that’s completed. 

Thank you for your understanding.

Best, 

Lola

**Comment by tbrown91** [comment]
Thanks @duprats

I'm pretty happy with this now. Any last thoughts, @DomAbsolon ?

**Comment by DomAbsolon** [comment]
Maybe I am missing something but the version of the EAR I can see, look like it is from 3 weeks ago?

**Comment by duprats** [comment]
Hello sorry  , I forgot to click on 'commit' !

**Comment by duprats** [comment]
Hi, I made these edits :/SUPER_6[16.44 - 16.60 Mbp ] => haplotig

  /SUPER_10[43.49 Mbp] to SUPER_10[42.27 Mbp]   inverted and moved to       SUPER_10[39.52 Mbp]
   SUPER_10[42.27 Mbp] to SUPER_10[39.55 Mbp]   inverted and moved to       SUPER_10[42.33 Mbp]

  /SUPER_14 : insert   scaffold_233[0.00 bp-237.94 kbp]        at       SUPER_14[65.94 Mbp]
   
  /SUPER_15[2.56 - 2.46 Mbp]       => haplotig 
  /tag  scaffold_245    => haplotig with      SUPER_15 [ 396.57 kbp -713.83 ]

  /SUPER_18[47.61 Mbp] to SUPER_18[32.33 Mbp] inverted and moved to SUPER_18[32.31 Mbp]  (telomere)
 cf   scaffold_182 => SUPER_18_unloc

**Review by DomAbsolon — APPROVED** [review]

**Comment by DomAbsolon** [comment]
Looks good

**Comment by tbrown91** [comment]
Thank you @DomAbsolon 

And thank you for all the hard work @duprats

**Comment by duprats** [comment]
Thanks  very much for your help

**Pull request merged**
